### ISSUE TITLE
How to filter all the movies in the search page?

### ISSUE THREAD

**Issue by Maxstgt** [blockframes/blockframes#1271]
Since we got algolia now, the question might be how we can make the most of it in the movie search page. Or should we filtering the movies on the client-side and use something like `Fuse.js' because we only got 10 movies on our DB. 
And how should be the user flow, only showing movies depending on his search results? Could save us some processing power.
It might be good to have a look here.

**Comment by Jackseed** [comment]
We have a paid account on Algolia including 50K records & 250K operations and we should be able to afford more if needed. 
Since the search bar should include movie titles, movie directors and keywords (for now) and certainly more in the future, I believe it's best to use the same tool for all the searches. 
Currently we have only 10 movies in our DB but we should count on thousands, keywords for instance being average 5 to 10 par films, we should count on hundred of thousands records to work on. 
I believe we should save us time and don't reinvent the wheel, especially since expectations on research from users are very high. So I'll go for Algolia for all the searches.
