### ISSUE TITLE
Security strategy to store node password

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1372]
Think of a strategy to store node password and avoid the user fill it everytime

**Comment by lsenta** [comment]
@GrandSchtroumpf @pldespaigne can you share some context for this one?

Which part of the infra / app is this used for? What's the password used for? Who sets the password?

**Comment by GrandSchtroumpf** [comment]
Following the first test using Kaleido, when you create a node you need to set app credentials (a node could be accessed by many app, each of them have a username + password).
So basically when you communicate with the node you need to do : `https://username:password@url-of-the-node`. Which means that it doesn't make sense to create a centralized server, and that whenever a user need to do something with the node he has to specify the password (we could keep the username on the database).
By default the password is managed by the IT person in the organization. But I'm wondering if we could find a better way to manage it.
Once you have the password & username you have access to the wallet and the txmanager, so you can read private tx + sign.

**Comment by lsenta** [comment]
Is it different, in term of security & critical-ness, from keeping a user's private key?

**Comment by GrandSchtroumpf** [comment]
Yes, for me this is the same issue as private keys. Maybe we could use the same architecture as we already have with the private key. @pldespaigne what do you think ?

**Comment by pldespaigne** [comment]
It's more complex than how we handle private keys right now.
In Blockframes the user are responsible for storing their keys, meaning they can lose their keys.
But it's ok because the smart-wallet architecture address this exact problem.

Here in quorum it's EOA private key, meaning that a loss cannot be recovered...

**Comment by lsenta** [comment]
I'll recap a few facts from your comments, correct me if I'm wrong:

- As critical as a wallet's private key => it should not be stored in a way that lets our organization access it.
- Managed by the organization's IT => we don't have to worry about losing the key

- We want to store this info so that access to the organization's node is convenient
- Basically, letting the user record this in their localstorage  & encrypt would be good enough.

I can draft a plan & an MVP in a few hours if that's the direction we want to go to.

**Comment by GrandSchtroumpf** [comment]
@pldespaigne Technically they CAN create a new credential from Kaleido interface (delete app credential & create a new one).
@lsenta There is no "organization's IT" in many companies we're going to work with.

Maybe more context here:
The current process to get the password is to "create a new app credential" from Kaleido interface. But this password is written only once, so they have to store it somewhere (paper or file system, for most of the company I guess). What I expect is that each time they are going to do a transaction they'll look for this password (if ever they remember what it is). And they might ends up calling us to remember how to do it. This is the behavior I would like to avoid.

@pldespaigne Maybe you can walk Laurent through the Kaleido interface to better understand it.

@lsenta localstorage seems like a good idea because it could be reused even when if we get rid of Kaleido.

**Comment by Jackseed** [comment]
I did not get that using Kaleido would force the user to use their interface so we cannot "link" it to our apps. Since it's critical for us that users use our interface for every apps & transactions, this architecture will remain for the POC and we will use Kaleido only with known beta testers we can help & assist. 

Thus I think it's not necessary to make any more implementation than what is needed for the POC scenario. So let's keep the password strategy to pen and paper for now, we'll see how we can improve it when we'll plug it to our apps.

**Comment by lsenta** [comment]
Moving to Icebox after @Jackseed confirmation
