### ISSUE TITLE
Add film page - Main - page 2

### ISSUE THREAD

**Issue by Maxstgt** [blockframes/blockframes#1407]
https://projects.invisionapp.com/d/main#/console/19020838/398261743/preview
ref blockframes/storymapping#14
On Zeplin :
https://app.zeplin.io/project/5ca741b3ed21e79faa266664/screen/5e0b144c41df769a14f55c1e

location of this files: 
libs/movie/form/main
libs/movie/display/main

name: stays the same as existing one
MovieFormMainComponent - needs refactoring!
MovieDisplayMainComponent - needs refactoring!

Things that changed
- [ ] Update Movie model
- [ ] new toggle button feature
- [ ] merge festival prizes
- [ ] Add button should update the current form and render new inputs, see `festival-prizes.form - addPrize()` for example.
- [ ] link with IMDB for Principal Cast Member
@vwmathilde 
![Screenshot from 2019-12-16 16-39-32.png](https://images.zenhubusercontent.com/5d19e757a91f961fd8457e0f/6949ffdc-97b5-43db-95b8-766f1148a32a)
What is it going to be when you click on it?
For devs it would be good if it is going to be like mat-chip component. 
![Screenshot from 2019-12-16 16-24-55.png](https://images.zenhubusercontent.com/5d19e757a91f961fd8457e0f/3f29e478-40e0-4098-bf74-0ea0e6d5e0d0)
New coomponent?
![Screenshot from 2019-12-16 16-47-58.png](https://images.zenhubusercontent.com/5d19e757a91f961fd8457e0f/d417dece-f533-4029-8661-dcd9d138084a)
How is the affected component going to look like if the toggle is set to disable?

**Comment by vwmathilde** [comment]
@Maxstgt I don't know. Maybe you should ask Anastasiia, she will probably know more than me :)

**Comment by Maxstgt** [comment]
@2amarkina Do you have a clue about it?

**Comment by Jackseed** [comment]
We've updated the country of origin component so it's not a select but a text input with autocomplete. 
About the add button, all fields will have the same behavior which is to create a new same field below the first one and the add button from the first one will become a delete button like this:
![image](https://user-images.githubusercontent.com/14964443/71087026-7ed8b400-219b-11ea-9272-71e61178e5d3.png)

**Comment by Mussuranae** [comment]
Content Type card :
Content Type and Freshness are enum, and are currently hardcoded. I don't know how to manager with enum and even if François gives me some code, I didn't success to use it.
The rest of the card is ok.

Directors card :
When we have no director yet, inputs don't appear and you have to click on the add button, but the form is ok

Country card :
Domestic distributor (distributor of county of origin) doesn't exist on the data model, so I skip this input.

Genre card :
Genre/Running time input are okay
Principal cast isn't in the movie.main section, so I skip it too for now
The principal difficulty here is that the specific genre input doesn't exist in the data model and we just can't add the data received from the user in the existed genre array. We need to know which genre is in the static model (so the selected genre input) and which is a genre registered by the user (the specific input).

Theatrical release/Festivals card :
Not done yet, because it's not in the movie.main section (in the data model)

**Comment by Jackseed** [comment]
- [ ] For Director, create a default one
- [ ] domestic distributor Country of origin component
- [ ] Specific genre
- [ ] Cast member
- [ ] Premiere festival

**Comment by Mussuranae** [comment]
DATA :
Content Type -> movie.main.workType
Freshness -> movie.main.storeConfig
Production Status -> movie.main.status
Original Title -> movie.main.title.original
International Title -> movie.main.title.international
Reference -> movie.main.internalRef

Directors -> movie.main.directors.firstname/lastname
Director profile -> movie.main.directors.shortBiography

Country of Origin -> movie.main.originCountries[]
Distributor in Country of Origin -> (need to be created)
Original Language -> movie.main.originalLanguages[]

Theatrical Release -> movie.salesInfo.theatricalRelease
Release Date in country of Origin -> movie.salesInfo.originCountryReleaseDate

Genre -> movie.main.genres[]
Specify -> (need to be created)
Running Time -> movie.main.totalRunTime
Principal Cast Members -> movie.salesCast.credits[] (need to add a role field to specify the role of the cast, see how to deal with research on IMDB)

Festival name -> movie.festivalPrize.prizes[].name
Award or Selection -> movie.festivalPrize.prizes[].prize
Year -> movie.festivalPrize.prizes[].year
Premiere -> (need to be created)

**Comment by Jackseed** [comment]
@Mussuranae as just discussed, there is a modification in the UI: Theatrical release component is deleted and merged with Country(ies) of origin. Each input must be independent so they are all a component. 
Re data model @phpgeekfr is working on changing the originalRelease parameter so you can use it for that
