### ISSUE TITLE
Choose for a user log library

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1630]
Ref #8

- capture important user events with the app  (log in, CRUD on any objects, ...)

Use Sentry Events ?

**Comment by lsenta** [comment]
The ticket #8 was about logging for dev / production mode, so that as developpers we can log info for debugging, which would be disabed in production.

Vincent's request looks more like tracking all the changes & operations produced by users so we can replay event and eventually resolve user issues (not directly related to debugging code).

Looking into sentry events atm.

**Comment by lsenta** [comment]
@Jackseed lets use analytics events, we already have all of those in the client and they are designed for this use case.

The basics is to:
create new events, define them in the front as enums
`Event.movieCreated`, `Event.applicationRequested` 
and send these from our analytic library, it'll contains info about user ids, etc.

estimation:
1 day to define & create the events we want to capture,
2 days to send them from relevant places in the codebase (akita services).

@Jackseed I can take care of this. I do believe this should be done by the frontend team which already knows how services, etc are implemented.
