### ISSUE TITLE
Update version model

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#1887]
This issue is here to reference all piece of code that need to be changed if we put versions inside the contract documents. And discuss how to update the model.

Initial thought: 
we can have a "archive" sub-collection for immutables versions, but at least the last version should be on the document.

---------------------------------

Todos:

- [x]   When a new contract is created, licensee can be set automatically (but can be overrided) with auth.user.orgId. => use akita-ng-fire for this
- [x]   Update front code
- [x]   When a new contract of type mandate is created/updated, the tiltleDetails.price.commissionBase must be set to grossreceipt.
- [x]   When a new contract of type sales is created/updated, the parties can be set automatically with the contract of type mandate of the titles included in contract. The contractParents or the current contract and the contractChild of the contract parent can be updated (only if != draft?).
- [x]   Keep the existing publicContract creation process
- [x]   Add titlesIds to contract.titleIds[] automatically when contract.titles is updated.
- [x]   Add partieIds to contract.partieIds[] automatically when contract.parties is updated and when contract status is not Draft and when parties have an orgId defined.
- [x]   Clean contract signDate, parties signDate and status when a new version is created.
- [x]   don't forget to document everything!
- [x]   check @todo (#1887) in code
- [x]   do we need to create separate collection for each contract type ?
- [x]  ContractVersion are archived only under certain circumstances, for example, contract status must be !== Draft to avoid polluting database.
- [x] Migration script :  moved to #2335

**Comment by phpgeekfr** [comment]
We will have the same kind of issues with `FinancialReport` and `FinancialReportVersion`. 

Added comments `@TODO (#1887)` in code to identify problems.

**Comment by GrandSchtroumpf** [comment]
Here are my arguments about the contract version : 

_If we want all versions on the frontend + frontend can update all versions_ 
There is not reason to have a subcollection. And we just make the code harder to build/maintain. Then we should put the versions on the contract document.

_If we want only the last version on the frontend + frontend cannot update a version_
There is a good reason to have a subcollection. And we need to improve the way we use it : 
- option 1: Have a mutable "version" key on the "contract" document and add it to the "versions" subcollection when we want to make it immutable (archived ?).
- option 2: Query only the latest "version" document from the subcollection with the contract document on the frontend, and frontend should only be allowed to update the latest version.

Personally I prefer option 1 as it makes query + rule much easier to write/maintain. Also it doesn't require any automation on the backend to create a version with the contract. But maybe I'm missing other key points here.

**Comment by phpgeekfr** [comment]
Notes after call between @GrandSchtroumpf & @phpgeekfr : 
To make the front developments more easy, developers shouldn't have to handle both `contracts` and `ContractsVersion` given that it is already hard enough since we also have to add `distributionDeals` and link them to the contract.

For not having to handle  `contracts` and `ContractsVersion` a solution could be:
_On the front side:_ only **one** model that is a merge of contract and version.
For example :
```
+id: string
+type: ContractType;
+parentContractIds ?: string[]
+childContractIds?: string[]
+signDate?: Date
+parties: ContractPartyDetails []
+titleIds: string[]
+partyIds: string[]
+documents: {
  invoices: LegalDocument[],
  expenses?: LegalDocument[],
}
+ lastVersion: {
    +id: string
    +status: ContractStatus (enum)
    +scope: Terms
    +creationDate?: Date
    +titles : { [titleId: string]: ContractTitleDetail}
    +price: Price
    +paymentSchedule: PaymentSchedule[]
    +customPaymentSchedule: string;
    +paymentTerm: Terms
    +renewalConditions: string
    +terminationConditions: string
    +AuthorizedRecoupableExpenses?: string
}
```
_On the back/functions side:_ on `Contract` write: a function is handling the version archiving automatically in subcollection. Archived versions are readOnly. ContractVersion are archived only under certain circumstances, for example, contract status must be !== `Draft` to avoid polluting database.

Independently off the futures choices we make (use backend functions or front), here is some logic to think about:

- When a new contract is created, licensee can be set automatically (but can be overrided) with auth.user.orgId. 
- When a new contract of type `mandate` is created/updated, the `tiltleDetails.price.commissionBase` must be set to `grossreceipt`.
- When a new contract of type `sales` is created/updated, the parties can be set automatically with the contract of type mandate of the titles included in contract.
- Keep the existing `publicContract` creation process
- Add titlesIds to `contract.titleIds[]` automatically when `contract.titles` is updated.
- Add partieIds to `contract.partieIds[]` automatically when `contract.parties` is updated and when contract status is not `Draft` and when parties have an orgId defined.
- don't forget to document everything!


Regarding the `distributionDeals` creation:

Current flow:
1. distribution deals are added to cart (on localStorage only @phpgeekfr  update draw.io ) with no id nor contractId.
2. cart is submitted: we now have to save distributionDeals and to create the associated contract.

The contract type will be `sales` so we can set the various parties automatically (but can be overrided) with the mandate contract associated to titles in the cart (if archipel content is the only 'mandate' org @Jackseed can you confirm?).

This currently lead to circular dependencies issues because contract need distributionDeals and distributionDeals need contracts..

We can choose to do it in front to save the number of write on db or do this in backend functions.
Functions could automatically (on contractWrite and distributionDealsWrite) do the appropriates updates on contract and distributiondeals documents. For example, a distributionDeal creation without any contractId specified could create/update the associated contract and link it .
Doing so could avoir circular dependencies issues.

In any cases, here is the logic to adopt when saving a batch of `distributionDeals` :
```
createSale(titles: { [titleIds: string]: Deal[] } = {}) {
  const batch = this.db.firestore.batch();
  const contractId = this.db.createId();
  // Inititalize parties
  const party = query.getActive();
  const parties = [
    createPartyDetails('licensee', { orgId: org.id, displayName: org.name }),
    createPartyDetails('licensor') // We want at least two parties
  ];
  // Intiialize titles
  const version = createContractVersion({ titles: {}, status: 'draft' });
  for (const movieId in titles) {
    // Create deals
    const deals = titles[movieId].map(deal => ({ ...deal, contractId });
    const distributionDeals = await dealService.add(deals, movieId, batch);
    version.titles[movieId] = createContractTitleDetail({ distributionDeals  });
  }
  const partyIds = [org.id];  // on draft we want only the creator
  const titleIds = Object.key(titles);
  const contract = createContract({ parties, partyIds, version, type: 'sale' });
  contractService.add({ id: contractId, ...contract }, batch)
}
```

When doing the issue, remember the various entry points:

- cart
- deal list on marketplace
- deal list on dashboard
- contract tunnel
- admin panel

**Comment by Jackseed** [comment]
> The contract type will be sales so we can set the various parties automatically (but can be overrided) with the mandate contract associated to titles in the cart (if archipel content is the only 'mandate' org @Jackseed can you confirm?).

Yep I confirm
