### ISSUE TITLE
cnc logo is not visible on dark mode

### ISSUE THREAD

**Issue by fritzschoff** [blockframes/blockframes#2142]
![Screenshot from 2020-03-04 16-03-57.png](https://images.zenhubusercontent.com/5d19e757a91f961fd8457e0f/b285bcee-730c-408d-add8-68277adfb855)
we need a new logo for dark mode

**Comment by maltmayer** [comment]
Everything dark doesn't show actually. Even if I know that the default mode is light so that shouldn't happened a lot to users. But as I usually log in and out, my browser keeps the dark mode parameter even when I'm logged out. and sometimes I get to pages like this. The person in the dark screen is a bit scary to be honest aha.
![image](https://user-images.githubusercontent.com/55785823/75996530-445ef780-5efe-11ea-8499-63a4fbc7207a.png)

**Comment by Maxstgt** [comment]
seems like wrong image for dark theme. Can be fixed with this issue

**Comment by Jackseed** [comment]
done by @Hugo-Hontans
