### ISSUE TITLE
New Archipel release 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2241]

**Comment by lsenta** [comment]
Quick notes from call with Hugo:

Create develop branch,
update github config to make this the default merge branch.
define merge as default action
modify ci to use develop when relevant (instead of master)

Then freeze features and prep release: create the release branch and train the team.
update the ci to build master and release branches when relevant.

**Comment by lsenta** [comment]
TODO:
- [ ] verify that we can't push to master.
