### ISSUE TITLE
Add a load more button on All titles page

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2631]
## Description
We need to limit titles display per page to avoid loading issues. 

## Acceptance criteria
- [ ] Add paginator on bottom right corner of the page, below the film cards
- [ ] Options should be 10, 25, 50, 100 and 50 by default

**Comment by GrandSchtroumpf** [comment]
@2amarkina What's the best user experience here : 
- add pagination
- load on scroll
- other ?

What would be a good amount of item to load at once maximum ? Currently we are limited to 50 items.

**Comment by 2amarkina** [comment]
For the researches conducted for the e-commerces sites the "Load more" button with the set from 25 to 75 titles is preferable.  Also this format is much better for the mobile version (but in such case is better to limit the set from 15 to 30 titles). So as for me this is the best solution. Also we need to implement an explanation text such as "You’ve viewed 30 titles from 200".

**Comment by fritzschoff** [comment]
Hey @2amarkina , do you have an idea where to put the text `You’ve viewed 30 titles from 200` ? Like below or above the button?

**Comment by 2amarkina** [comment]
@fritzschoff  it should be above. Something like 
![image](https://user-images.githubusercontent.com/55499036/86226903-9d792800-bb8c-11ea-8cdb-6978a6004f2b.png)

**Comment by fritzschoff** [comment]
alright, and for the button a mat stroked button should be good?
![image](https://user-images.githubusercontent.com/39312833/86227253-0bbdea80-bb8d-11ea-934b-605efd5e1ad9.png)

**Comment by 2amarkina** [comment]
as for me yes, @stephanie-cascade8 what do you think ?

**Comment by fritzschoff** [comment]
So there is a lot of question needed to be answered. Let me try to sum them up.
![image](https://user-images.githubusercontent.com/39312833/86337023-daa6ee00-bc50-11ea-8bd6-bccf3ebc3b4b.png)

- [ ] the sortBy filter is empty by default, so the movies will be displayed as they arrive. What should happen, when the user chooses a sortBy parameter, will it has an effect on the upcoming results? If yes, this is not really maintainable.
- [ ] What about the number on the top right corner that displays all the available movies. If a user filters some movies by genres for instance. Should it stay the same? Or should it change in terms of available movies that matches the query. Cause it can happen, that you filter on some parameters but you didn't loaded all the movies. 
- [ ] What about the number over the progressbar. Should it also display the total amount of movies or should it be dynamic in terms of of the filter query that the user has choosen? 
- [ ] DEV: we really need to find a way to work with aloglia only in this page. Otherwise it is an absolute mess with getting the data from algolia checking with akita etc.

**Comment by 2amarkina** [comment]
1. SortBy filter - Ideally if a user chooses sort by a director for exemple, the "load more" should adapt to it... 
2. Actually, it is a really great idea to say something like " 555 results for "Drama" ", BUT we've got to many parameters (filters) and if we start to precise all of them that wouldn't be ok. General solution : " 55 titles according to your search ". 
3. Should be dynamic according to the searching parameters / filters

**Comment by fritzschoff** [comment]
https://www.algolia.com/doc/guides/managing-results/refine-results/sorting/ just for me @fritzschoff how maybe a sorting can work

**Comment by Jackseed** [comment]
Solution needs to be find:
```
Hey @canal, I just had a quick chat with Pierre about algolia and how we can sort our movies. By title or by directors. This question appeared because I got an issue about a load more button  that loads more movies to the movie search page. Yesterday afternoon, I was reading the documentation and found out, that you can't pass a sortBy parameter to your algolia query in order to receive the movies ordered by titles for instance. You need to work with replica indicies. Meaning, you need to sort the indicies when you instantiate them. So if we then say in the UI, please give me movies sorted by titles  and then clicking on the load more button it will switches the index and query the movies from a different index that got the movies sorted by titles (alphabetically).
This will result then for our movie index in two new indicies, 3 in total then. One original one, one sorted by titles and one sorted by directors. We also then need to make sure that all these indicies are synced. Which require a script and would need some maintenance if we update a facet or a filter. I know that Anastasia says that it is really important for the UX to have a sort by functionality but I guess we need to evaluate if this is possible for us to maintain such indicies.
```

**Comment by fritzschoff** [comment]
thanks @Jackseed . But who is canal? :D

**Comment by Jackseed** [comment]
@RemcoSimonides following our discussion, you can move on with this issue implementing a load more button as Anastasiia explained it above.
In the meantime to avoid too much complexity we get rid of the sort by button and will implement it again following #3584
