### ISSUE TITLE
Admin invite problem

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#2638]
- [ ] when you're admin on Archipel and you invite someone to join your org, it works the first time. But if you decide to delete the invitation. And for some reason you want to invite the same person again, it doesn't work, they never receive the other email(s).

**Comment by phpgeekfr** [comment]
@maltmayer @Jackseed Is this still an issue ?

**Comment by Jackseed** [comment]
Yes I tested it again and it's still there

**Comment by Mussuranae** [comment]
After investigation, it seems that the email isn't sent more than one time because the user already exists in the authentication part of firebase. When we remove the invitation, it delete the invitation but not the user in the authentication.
So I wonder if we can have a talk after holidays about the authentication, when we create an user, when we delete one, do some cleaning, etc....

**Comment by Mussuranae** [comment]
Ok I did a fix that removes the user in the users collection and in the authentication of Firebase **ONLY IF** the user hasn't already an orgId and if there is no other invitation to join an organization for his/her account.
But is it intentional to let user invite someone who already belongs to an org ?

**Comment by maltmayer** [comment]
I'm I think we'd better have a talk as this was not the issue. I don't think we should remove the user either from the user collection or authentication.
The problem is not that the user doesn't receive logins (which is normal as authentication already exists) but that he just doesn't receive the invitation email.
