### ISSUE TITLE
Discuss player implementation details

### ISSUE THREAD

**Issue by pldespaigne** [blockframes/blockframes#2653]
- [ ] choose the best strategy about the length of expiring player links (to watch the video) @Jackseed @GrandSchtroumpf @pldespaigne

- [ ] choose the best strategy about the length of expiring upload links (when we give a download link to JWPlayer to create video) @Jackseed @GrandSchtroumpf @ioaNikas @pldespaigne 

- [x] find a way to store JWPlayer IDs (for full-movie & trailers) inside the movie object in firestore @phpgeekfr @ioaNikas @Mussuranae @pldespaigne 

- [ ] find a way to hook the JWPlayer function at the end of a firebase storage upload event @ioaNikas @pldespaigne

**Comment by Jackseed** [comment]
@pldespaigne @GrandSchtroumpf 
1.` choose the best strategy about the length of expiring player links (to watch the video)`
After discussion with @maltmayer best would be to give user the choice. Would it be possible? 
In any case since this would mean update UX & UI, I would personally recommend to first arbitrary fix it to something around 5 to 10 hours so we allow people to pause the film if necessary and watch it during the day. 

@ioaNikas 
2. ` choose the best strategy about the length of expiring upload links (when we give a download link to JWPlayer to create video)`
So we're talking of the upload links generated by firebase to JWPlayer? 
If so, is it possible for JWPlayer to create an event when the upload is completed so firebase catch this event and terminates the link?
+ maybe a protection so if JWPlayer never succeed in downloading the film after a certain amount of time, we terminate it

**Comment by pldespaigne** [comment]
@Jackseed
1) It's possible to ask the user for the duration of the link but it require front & back changes along with deciding what is the max authorized length *(to prevent the user to set duration to 99...99 years)*.
I think it's a good solution to start with 5 hours. Also keep in mind that as long as the event is not finished the user can just refresh the re generate a 5 hour link

2) Yes we are talking about Firebase storage -> JWPlayer.
JWPlayer cannot create an event for us, but we could check for the video status every `x` minutes.
In any case once the link is created we cannot destroy it anymore it will just expire at the given time.
IMO there is almost no chance we can get hacked this way as it's server to server communication through TLS. Best solution would be to set the expiration to something like 2-3 hours to be sure and then check every 20-30min to see if the download has succed and retry with a new link in case of error.

**Comment by Jackseed** [comment]
@pldespaigne, looks all good to me!
1. I created a ticket for letting the user decides (#2732), meanwhile go for 5h. 
2. Let's go for it! mb ask @GrandSchtroumpf still to be sure
