### ISSUE TITLE
Implement image-set directive to load the right size of image in the component

### ISSUE THREAD

**Issue by ioaNikas** [blockframes/blockframes#2655]
[Ressource](https://css-tricks.com/responsive-images-css/)

**Comment by GrandSchtroumpf** [comment]
## Current state
There is 4 directives that deal with images : 
- `ImgAsset`: Load local image asset into a `img` tag depending on the current theme
- `BackgroundAsset`: Set background with local asset depending on the current theme
- `ImgReference`: Load Firestorage reference image into an `img` tag (+ fallback on local asset)
- `BackgroundRef`: Same but for background image.

> This issue focuses on the `ImgReference`, but should lead to a unified version to deal with one or two directive max in the end.

Currently the `ImageReference` directive get the original image from Firestorage. Instead it should use the `srcset` property to load the right size.

## Use ImgRef object
Each document stores the reference to their images through the `ImgRef` object interface. It provided several sizes (generated by a backend function): original / xs / md / lg.
The goal it to update the `ImageReference` directive to use `srcset` instead of `src`. 
For `srcset` to work we need to specify the size of the image we are using, this depends on the "type" of the image.

Here is how it should looks like in the end : 
`<img [imgRef]="profile" asset="empty_profile" size="xs" />`

This means : 
- If profile existes, check it's type (logo, avatar, banner, poster, still) & the size to get the width
- Set `srcset` with url & width of the image
- Else, use the asset in the local project `empty_profile.webp`, depending on the current theme.

## Future
In this end we should have only two directive to deal with images : 
`<img [imgRef]="profile" asset="empty_profile" size="xs" />`
& 
`<div [bgRef]="banner" asset="empty_banner" size="lg"></div>`

If we want to display an asset (and not a reference), we should only write : 
`<img asset="empty_profile" size="xs" />`
Currently local images are not resized, but this is a future work we'll need to do
