### ISSUE TITLE
Let the user decides for screening url termination

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2732]
Following discussions on #2653 we should let the user decides when the screening url is destroyed. 
To be clear: 
- the user can already decides how long buyers can call a screening url through the event duration
- here we are talking of the duration of that link. e.g. once the buyer has the link, how long does he has to watch the film?

@maltmayer @2amarkina I feel that we can add a simple number input on the [screening form](https://projects.invisionapp.com/d/main?origin=v7#/console/19607961/412244898/preview?scrollOffset=2716.666748046875). Do you have recommandations on text or input style?

@phpgeekfr @Mussuranae @GrandSchtroumpf we should update the data model accordingly, any advice?

**Comment by maltmayer** [comment]
Yes, a simple number input on screening form works for me :) But they should also have the choice between minutes / hours. (They might chose between 15 min and 48 hours.)

**Comment by Jackseed** [comment]
@maltmayer following discussions with Yannick & Fred, we will pause this as they don't think it's important for users. 
@pldespaigne we keep with arbitrary 5 hours.
We still may need additional explanation for the user to understand how the screenings work, @maltmayer you can work on a wording for that: explaining that the time they set for the screenings it the timeframe while the buyers can load the screening and then they have 5hours to play the film

**Comment by maltmayer** [comment]
The screenings on Archipel Market are live sessions (they’re limited to a timeframe), but they’re also flexible for buyers (during the determined timeframe, buyers will be able to launch the screening at any time).
The timeframe you set here for your event will be the time during which buyers will be able to start their screening. Outside of this timeframe, the screening session will be closed to all users. 

(I don't think we need to specify that they have 5 hours to play the film)

**Comment by pldespaigne** [comment]
When we display the video, jwplayer require us to decide for how long the video will be "active".

- if the user try to see the screening outside of the event timeframe, we simply told him that it's not possible (and we don't even ask jwplayer anything).
- if the user is in the event timeframe, then we will ask jwplayer to "acitvate" the video for a given amount of time.
- Now if the "activated" time is over but we are still in the event timeframe : the user can just refresh the page and get again the screening for the duration of the "activate" time.
- if the "activated" time is over and the event is also over, the user cannot see the video anymore.

I hope it's clear, don't hesitate to ask if not!

From my point of view it's useless to ask the user for the duration of the "activated" time.
1) it requires us to explain
2) we need to decide for a max "activated" time otherwise every body could just set the end date to 01/01/3999 or whatever
3) if we set a max, the user will probably think "I will just put the max just to be safe". So we can prevent the burden by just putting max time ourselves.
