### ISSUE TITLE
sanitize user name doesn't produce a 1 - 1 mapping for user names

### ISSUE THREAD

**Issue by lsenta** [blockframes/blockframes#279]
https://github.com/blockframes/blockframes/blob/master/libs/auth/src/lib/%2Bstate/auth.service.ts#L113-L117

Ticking time bomb: some combination of user names will produce the same output and introduce bugs, use a mature encoding ala base64, keccak hash, encodeURIComponent, etc.

**Comment by pldespaigne** [comment]
fixed in #261

**Comment by lsenta** [comment]
Reopening, I won't trust this before I looked at the code or we're using a sane encoding function!

**Comment by pldespaigne** [comment]
You can see the code here #277 , my function is not perfect but I challenge you to find a collision 😉 

We cannot use encodeUri since it will produce forbiden chars like `%`, and I'm against using base64 (that also produce forbiden `=` chars and uppercase chars) or keccak hash because it will replace human readable names like `laurent-senta.blockframes.test` by `bGF1cmVudC1zZW50YQ==.blockframes.test` or `898d809d9aeaaea54c5462ebbb776581e41290a2f8b0b17be199ba17573f97df.blockframes.test` and this defeat the whole purpose of using ENS in the first palce.

**Comment by lsenta** [comment]
After discussion with PL: the real issue around name collision is ENS hijacking. We trust the user to provide their ens name anyway, and the probability for collision is very low.
=> We'll accept the risk of collision, stick to this encoding
=> We'll make sure double deploy is forbidden for ENS contracts.
