### ISSUE TITLE
UX Review Archipel Market

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2964]

**Comment by maltmayer** [comment]
Just a general comment for UX:
We should distinguish the buyers' platform and the buyers' available to sales agents. 
1. there should be a switch back to the dashboard (so that they're not "stuck" on the marketplace if they don't have the reflex to enter the dashboard url)
2. sales agents shouldn't be able to do everything a buyer can do (ask acces to screenings, have a wishlist, etc)

**Comment by 2amarkina** [comment]
@maltmayer Ok, thanks Marie ! So do I understand right that sales agents have access only to their own films ?

**Comment by maltmayer** [comment]
Non they can access all the marketplace and navigate through it. But not "act" on it
