### ISSUE TITLE
[E2E] "All Films" page query

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3172]
For Mano (tag him when he got an account)

## Description
We should be sure that the films existing on firebase, corresponding to specific app queries, are loaded correctly.
For example on festival we load only films that have an `accepted` status and an appAccess festival set to `true`. 

Write the E2E test for that.

## Acceptance criteria
- [ ] Replicate films from Firebase 
- [ ] Replicate the query used on the All films page (Algolia)
- [ ] Add query parameters (e.g. for festival status accepted && appAccess festival)
- [ ] Verify that the result is what we expect

**Comment by xmano** [comment]
For the acceptance criteria mentioned in the issue - the steps actually happen when running E2E against the served app. There is nothing special to be done for that. However, the specific steps can be converted to a unit-testing scenario but again there are many components involved so it is complicated.

The create-bucket spec looks for created Movie and it covers this specific use case in E2E so we do not need any thing new except it is for content app. 

If needed we can add a query in Festival App for searching for some movie. Checking with @Jackseed

**Comment by RemcoSimonides** [comment]
The data model has been reworked a bit but I think the purpose of this issue is to test whether the titles page on catalog only shows movies that have
`app.catalog.access == true` and `app.catalog.status = ='accepted'`
same for festival: only movies with `app.festival.access == true` and `app.festival.status = ='accepted'` should show up
same for financiers: only movies with `app.financiers.access == true` and `app.financiers.status = ='accepted'` should show up.

This I think can be done both with a unit-test or with a e2e test. You can choose which fits best.

**Comment by Jackseed** [comment]
Yep exactly, also we should check that the amount of movies loaded is the same as what should have been loaded. Mb more a unit test thing..
