### ISSUE TITLE
Issues regarding production database and storage

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3175]
- [x] 1. Delete old notification & invitations (<14 days) except pending invitation to become a member of an organization.
- [x] 2. Delete notification & invitation from doc that doesn't exist anymore.
- [x] 3. Delete the last image ref artefacts

Checkout #3047

**Comment by GrandSchtroumpf** [comment]
Production database and storage are a mess, and a cleaning is needed.

Todo/ To check : 

- [ ] DistributionRight object in movie root instead of sub-collection
- [ ] 89 files with name too long in storage
- [ ] check the `movie` dir (which should now be `movies`)
  this is caused by the `presentation_deck` and other pdf files that are not uploaded to the good directory, we should merge them back into the good `movies` folder
- [ ] watermarks are stored in the root at `watermarks/` _(with an `s`)_ where they should be not in the root but in `users/<ID>/watermark/` _(without an `s`_), so we need to move them
  *Alternatively we can also just delete them all, and re generate them with the updated backend function, it shoudl create them in the good folder.*
- [ ] keep only the used images: some folders can have 2 to 5 images 
- [ ] check if number of user in `Authentication` is the same as in db
- [ ] at the end of the cleaning : delete every folders/files that are not in the good place/doesn't have the good name

**Comment by phpgeekfr** [comment]
- [ ] check if a permission cleaning is needed

**Comment by phpgeekfr** [comment]
- [ ] docsIndex collection with undefined document in it

**Comment by phpgeekfr** [comment]
- [ ] create a migration script for remaining files that are correctly linked in DB but not in the good folder.
- [ ] update front so the resources are saved in the right directory
