### ISSUE TITLE
Notification and Invitation Page should share the same design

### ISSUE THREAD

**Issue by fritzschoff** [blockframes/blockframes#3266]
At the moment these pages are sharing almost the same feature and could be merged into one. Also these pages are used in every app. Festival, Catalog and media financiers. 
It would be better to maintain one page then 2 pages in every app, that also got split up in marketplace and dashboard.

# Dev
make sure only notifications and invitations are shown specific to the user AND to the app.

**Comment by 2amarkina** [comment]
Absolutely agree ! Actually before we didn't have this separation between notifications and invitations. if you remember, it was a general space that was called "Activity Feed". 

As for me, it would be nice to merge these two parts (moreover, it will also help us to win some space on the toolbar !)

**Comment by 2amarkina** [comment]
I'm really sorry ! I didn't understand correctly your question. François just explained me that it was not about having one page instead of two (notifications and invitations on one page), but really about sharing the same page between Dashboard and Marketplace parts. 

So, as the users are not the same, the notifications / invitations should be different. Really sorry for my misunderstanding !

**Comment by fritzschoff** [comment]
All good! Don't worry!

**Comment by Jackseed** [comment]
@fritzschoff ok to close that issue?

**Comment by fritzschoff** [comment]
@Jackseed yes. But lets have an issue about reusability. Notifications and Invitations in a perspective to the app. Also depends on the design. We can find a way to also reuse this component in marketplace and dashboard, although the users are not the same
