### ISSUE TITLE
Yandex Metrica to setup

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3317]

**Comment by 2amarkina** [comment]
Yandex Metrika functions with the Tag Systems. To make it work we needed to do some actions from the back-office (all info on 1password). 

So I created two counters : Content and Market (Market is our priority).

So as Market is priority for now, here is the list of things being done : 
- tag number :  65689861 
- domain tested : www.archipelmarket.com

There are two main methods to integrate the generated code : HTML, CMS / builders. I imagine that we need an HTML one :) 

**Code spinnet :** 


<script type="text/javascript" >
   (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
   m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
   (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

   ym(65689861, "init", {
        clickmap:true,
        trackLinks:true,
        accurateTrackBounce:true,
        webvisor:true
   });
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/65689861" style="position:absolute; left:-9999px;" alt="" /></div></noscript>



**Supplementary notes (taken from the site):**
Insert the code snippet in the HTML code of all the site's pages. Place the snippet inside the <head> </head> or <body> </body> tags, as close to the top of the page as possible. This allows it to load faster so that it can send data to Yandex.Metrica even if the user closes the page right away.

If you change the tag settings after installing the code snippet on the site, you must update the snippet on all the pages.

**Comment by fritzschoff** [comment]
Guess we also need this for every app. We can put the different code snippet in the different index.html files at the root of very app

**Comment by phpgeekfr** [comment]
@Jackseed do we still need Yandex Metrica since we now use analytics and other BI tools ?

**Comment by fritzschoff** [comment]
I thought we are using yandex for the heat map ?

**Comment by Jackseed** [comment]
@fritzschoff I confirm

**Comment by fritzschoff** [comment]
@phpgeekfr guess he still need it then

**Comment by RemcoSimonides** [comment]
- [x] Yandex should receive data again
- [x] Yandex now collects data separate for catalog, festival and financiers app
