### ISSUE TITLE
Image are uploaded on every form submit even when they were already uploaded before

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#3327]
Reproduce in any form with cropper component:
- Select an image
- Submit form (images are uploaded)
- Submit form again (images are uploaded again)

If you delete the image on the second submit, the image will be uploaded and deleted at the same time causing chaos both in firestore and storage.

link to main issue #3084

**Comment by pldespaigne** [comment]
Also check every possible case (create, update, delete) without reloading the page.

**Comment by pldespaigne** [comment]
when the document is updated in firestore, the changes are sent back to the front-end, we can see the updated movie in akita collection service

but we do not forward those change to the forms

I think the good way to fix the issue is to :
- [ ] on document update also update the form
- [ ] reset media forms with the new document values
