### ISSUE TITLE
Determine how we should handle pdf (presentation_deck, scenario)

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#3576]
Currently, img-ix can be used to display a pdf (If you know the filename). This is an unwanted side effect but for security reasons we should be able to prevent that.

- [x] we need to check how to exclude pdf content from img-ix 
- [x] we also need to think about storage rules regarding private files such as pdf. 

Also, we can currently upload pdf from movie tunnel but can we download them somewhere in front @Jackseed ?

**Comment by Jackseed** [comment]
@phpgeekfr we discussed that but I'll write here as a reminder of what we said:
- imgIx seems a good solution for pdf also since they have a way to protect file access through token
- re front, currently pdf are downloadable through the movie page in the marketplace, there are actions buttons to allow that 
- in the near future we would like to have a dedicated invitation system to pdf files (meaning only invited users can download the file), that's important to keep that in mind for our current choices
