### ISSUE TITLE
Test bigQuery extension for Firebase

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#3772]
The goal is to have all data (firebase, sendgrid, analytics ...) into a single db engine that we can query easily to performs BI or analytics queries.

First step is to check if bigQuery extension for Firebase can be setup easily.

**Comment by RemcoSimonides** [comment]
I think BigQuery is the way to go in order to achieve this goal.

Steps to setup:
- Add a BigQuery extension for each Firestore Collection you want to export to BigQuery.
- The extension only sends updates to BigQuery, so we need to export the already existing data to BigQuery using this script: https://github.com/firebase/extensions/blob/master/firestore-bigquery-export/guides/IMPORT_EXISTING_DOCUMENTS.md
- Then it's needed to create a schema for each collection in order to query the data properly. e.g.
```json
{
  "fields": [
    {
      "name": "id",
      "type": "string"
    },
    {
      "name":"ownerId",
      "type": "string"
    },
    {
      "name": "isPrivate",
      "type": "boolean"
    },
    {
      "name": "type",
      "type": "string"
    },
    {
      "name": "title",
      "type": "string"
    },
    {
      "name": "start",
      "type": "timestamp"
    },
    {
      "name": "allDay",
      "type": "boolean"
    }
  ]
```
- At last, BigQuery can be easily connected with Google Data Studio in order to visualize the data.

**Comment by phpgeekfr** [comment]
@RemcoSimonides can we close this one ?

**Comment by RemcoSimonides** [comment]
ye
