### ISSUE TITLE
Export events to external calendar

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4045]
## Description
To facilitate users' life we want to enable them to export/import events from in-app calendar to their regular calendar (Google Calendar, Outlook,..). 
This should be enable either for a specific event or for their whole personal calendar. We should also enable event email invitation to have an export button so users can add it directly to their calendar from the email. 

### Calendar
- Add a button that exports all the events in one file to import
### Event view
- Add a button to export the event as an .ics (?) file
### Emails
- Add a button that enables the import of the event to external calendars

**Comment by fritzschoff** [comment]
closed it while working on the roadmap

**Comment by RemcoSimonides** [comment]
Estimation
UX: 2 days
UI: 1 day

**Comment by phpgeekfr** [comment]
Dev estimate (Bruce)

- create ICS file from an event  : 0.5 day
- download it from event : 0.5 day
https://stackblitz.com/edit/create-and-download-event-ical?file=src%2Fapp%2Fevent-download.utils.ts

- add file into invitation emails as attached file :  2 days

https://stackoverflow.com/questions/67149571/how-to-send-ics-calendar-invite-through-sendgrid-so-that-it-renders-in-email-cl

As I like to double my estimations by two : **6 days**

**Comment by 2amarkina** [comment]
[Work in progress can be found here](https://www.figma.com/file/5QXJh2VKlKdWN6RfZhxKK9/%5B-Export-Events-to-Calendar-%5D?node-id=0%3A1)

**Comment by 2amarkina** [comment]
Ready for UI

**Comment by phpgeekfr** [comment]
- [ ] I still need to do more researches but it looks like that we cannot have a single button to export either to iCal / Outlook or Google Calendar because they don't work the same way:

- click on iCal button should download an `ics` file to import it into calendar
- click on Google Calendar button is a link to `https://calendar.google.com/calendar` with event parameters in URL. It can also support `ics` files but users will need to click on settings => parameters => import and this does not looks like really user friendly..

So maybe we will need to change button into a select, or with a popin, or let the user configure his preferences in the profile area ?

An example can be found here : 
https://www.crypto-lyon.fr/event/projets-crypto-apero

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/66bce19f-822b-4b0b-a7ba-9482b86e106a)

- [ ] I also don't know if multiple events can be exported in a single click, I need to check if this is possible for both iCal and Google. I'm quite positive to the fact that it is possible in a single `ics` file but for Google calendar, users will need to import it as described above.

- [ ] Regarding emails, I think that putting an `ics` file as attachment is enough for both Google and iCal.
It would look like this :
top : 
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/ac3b6194-7c6e-45f5-92da-d319ed87fe41)

bottom : 
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/604e5bca-5d39-433b-b3b3-1cb72e205df6)


@2amarkina @cams-goussale  I'm available to discuss about this and will confirm what I just said beginning of next week

**Comment by 2amarkina** [comment]
Following the last discussion, we can go for this representation: 
Solution 1 : Keep up with the basic version and "simply" download the calendar not regarding the format. 

The following solutions are more advanced: 
### Calendar view Dashboard and Marketplace 
Seems to be good to have a Select

![Marketplace.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/9f534460-b7cc-4e8b-a218-c4a0ce19ceef)

![Marketplace.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/2b276a75-b143-494f-80f0-344fc57a848a)

P.S. Here we need to keep an empty field or "-" to let user choose nothing. 
When clicking on the "Google, iCal, Outlook" the download starts directly.

### Screening list
Seems to be more "heavy" visually (on export per screening), also knowing that we want to introduce a "Make an Offer" button here too. 
Here is a version with Select + new "Make an offer" btn. 
![Screening List.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/9f9ca588-ecab-4547-9cb1-37e68e16ad23)

Here is another proposition, using the icons of mentioned calendars. On UI level we'll need to see if we can introduce more homogeneous representation.
![Screening List (1).png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/478e17a9-487a-4afc-b4f6-440341d9b8f2)

### Event Page
Same remarks concern the Event page. 
The two new propositions are the following: 
v1. use the cal icons near the events privacy settings 
![Снимок экрана 2021-12-23 в 18.26.26.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/65ed1a61-d389-466a-94b8-19eedc2988e1)

v2. same, cal icons, but on the right top 
![Снимок экрана 2021-12-23 в 18.26.49.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/847f421f-c874-4a4a-a09b-a0139816eba4)

v3. Select field on the right 
![Event View.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/9103cceb-a7e0-4afc-b8be-898b062e7e80)


### Dashboard 
Event creation form 

v1. ![Снимок экрана 2021-12-23 в 18.32.14.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/7b989e99-f2c9-40ba-a087-a62af068a743)

v2. ![Presentation (1).png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/e6090959-b5c2-49c3-8712-d7740ff18e76)

v3. the select on the right
![Снимок экрана 2021-12-23 в 18.41.39.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/7ebb166a-c7f8-4f3a-82bf-c01c740b2541)

### Invitations
Introduce all the possibilities
![Снимок экрана 2021-12-23 в 18.42.21.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/d0ab8dd3-e8f7-4df6-bb72-6862f6657d77)


Imho, i would propose to go with the basic version at the beginning, see if there any clicks etc.
cc: @cams-goussale

**Comment by cams-goussale** [comment]
Hello @2amarkina 

**Calendar view Dashboard and Marketplace**: selector looks good
**Screening list**: if we can go for the logos (v2), it's great. If not, could we introduce just the 3 dots like we have in the Notifs? I fear we're giving too much importance to the Export option and not enough to the Make an offer in v1.
**Event page**: preference for v2 here to keep consistency of having download buttons on the top right corner. Same question as previously: what about a 3 dots menu in this page?
**Event form**: same, I think we should keep it on the top right corner.

The 3 dots could also allow us to add more interactions in the future. What do you think?

**Comment by 2amarkina** [comment]
For the logos / icons, if possible maybe we could apply our colors to make it more "homogenous" and like that the "make an offer" button will be quite visible. But that's true if we keep up with the colored versions it might take too much attention. 

I made some tests with the dots. Indeed, there is a big advantage that we could add many actions inside. The thing that bothers me is that that icon is not very explicit, but here some tests and other ideas: 

1. Three dots could be always put next to "privacy settings" (and on screening list and on the event page) and on the right side for dashboard 

![Event View (1)](https://user-images.githubusercontent.com/55499036/147341884-8132796e-abb0-478e-9cbb-57f94d6c3b6b.png)

<img width="239" alt="Снимок экрана 2021-12-24 в 10 45 20" src="https://user-images.githubusercontent.com/55499036/147341958-1cda6884-ea14-40aa-8543-464ed2750122.png">

<img width="371" alt="Снимок экрана 2021-12-24 в 10 47 23" src="https://user-images.githubusercontent.com/55499036/147341979-44a43790-4be9-4c39-83a4-41a7fe8d85ba.png">


2.  But in such case I guess that it would be better to use the download icon instead of dots. The behavior might be the same, but i think it would be easier for user to see what is hidden by this icon
![Event View (2)](https://user-images.githubusercontent.com/55499036/147342388-a35869ef-e6d8-4245-ba4d-77f4dfc29dc2.png)

<img width="335" alt="Снимок экрана 2021-12-24 в 10 47 35" src="https://user-images.githubusercontent.com/55499036/147342407-bb28258a-ad3e-49d3-8a5f-c1f28d789a1b.png">

<img width="240" alt="Снимок экрана 2021-12-24 в 10 45 30" src="https://user-images.githubusercontent.com/55499036/147342432-a9df6d9c-9e55-4fb3-a277-95cfb0114164.png">

**Comment by 2amarkina** [comment]
[Updated wireframes with the last decision can be found here. ](https://www.figma.com/file/5QXJh2VKlKdWN6RfZhxKK9/%5B-Export-Events-to-Calendar-%5D?node-id=0%3A1)

**Comment by phpgeekfr** [comment]
- [ ] create ICS file from an event 
- [ ] download button
- [ ] add file into invitation emails as attached file
- [ ] add button to export all ongoing and upcoming events to calendar (dashboard, marketplace)
- [ ] add button to invitation list (marketplace only)
- [ ] add button to screening list (export all and single)
- [ ] add button to event view (x2)
- [ ] add button to event form 
- [ ] check if attachment is needed for all event related emails (notif accepted, rejected etc)

**Comment by phpgeekfr** [comment]
- [ ] ask if "export event" on invitation list is only available for marketplace or only for invitations (that should normally be sent to `buyers` only - ie marketplace)

**Comment by phpgeekfr** [comment]
- [ ] add export event and export all on org list ? 
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/f91a53cb-837a-47ea-8b02-ad6a7c890dd7)



- [ ] same for title view
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/cc73ce63-c779-4419-b426-96a1672f7877)

**Comment by 2amarkina** [comment]
- [ ] provide tooltips for export calendar 
- [ ] update "make on offer" to "request asking price"

**Comment by 2amarkina** [comment]
tooltip text proposition: Export ongoing & upcoming events 
@Jackseed @cams-goussale @maltmayer

**Comment by phpgeekfr** [comment]
- [ ] on calendar pages, disable export button if nothing to export
- [ ] add tooltips on button
- [ ] screening list: move export button like in event view
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/25ca99b1-3b57-48b1-8620-1582208d6302)

- [ ] screening list: add sentence "there are xxx screenings" at same level as export button (like title list) + use mat-button instead of mat-flat-button on both PDF & calendar export

- [ ] make list of emails that currently contains the event as attachment and ask where it should be kept ( for now: reminders, invitation, accepted request)
- [ ] use @stephanie-cascade8's mock-ups 
- [ ] implements drop-down on buttons for single events ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/2e9855e8-01a3-4991-be10-59684461c0b2)

**Comment by stephanie-cascade8** [comment]
@phpgeekfr let's keep a mat-button as we said and icon on the left. If you want a disabled color use foreground-600 in the builder.

**Comment by phpgeekfr** [comment]
I started with :
Email list that contains the ics as attachment: 
- [x] `inviteUsers` Invite a list of user by email (to new users).
- [x] `sendReminderEmails` Send a reminder email 24h or 1h before event starts.
- [x] `sendRequestToAttendEventUpdatedEmail` Send an email when an request to access an event is updated (to user that made the request) **accepted**.
- [x] `sendInvitationToAttendEventCreatedEmail` When an invitation is sent (to existing user)

let me know if I need to change this.

**Comment by cams-goussale** [comment]
hey @phpgeekfr it's all good, the list you did is perfect. The rest of the emails don't need the ics!
