### ISSUE TITLE
Consent update - User cookie preferences 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4099]
Change cookie preferences header in the user settings page to match this [wireframe](https://www.figma.com/file/3QXUWVIigMVBxLL5il4iG2/RGPD-wireframes)
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/75aa138e-cab8-487c-a665-e79b8b4ac619)
Keep google on top of the page in the necessary cookies but:
- [ ] Add the "General Cookie Preferences" title
- [ ] Remove the text 
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/61d6f2d9-e6b7-44d9-b21d-afa4e917cabf)

**Comment by Mussuranae** [comment]
For this issue, @Jackseed decides that we can let it like that for now, because if we change the form here, it will also change the form inside the modal (when you are not log in and you click on "changes preference" button in banner). 
So, as it has to change soon to become app-specific and it's not a high priority, we will change it when the design and the behavior will be review by Anastasiia and Stéphanie.

**Comment by Jackseed** [comment]
Let's just close it, it's not a priority
