### ISSUE TITLE
Movie form debug 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4338]
- [x] Prod status label should be aligned
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/283d588b-dc0a-4fff-90d4-3ca4c3130c58)

- [x] Sales pitch: we also need a video upload box here named « Sales Pitch video » 
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/e08db6dd-ab22-48f7-96a9-3538b34e0b59)

- [x] [Not for this release] Video section: what happened to all the videos pre-typed ? 
1. They should be added:
Teaser
Trailer
Clip
Promo Reel
2. Other video need an input to add a name to that video
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/7f862c56-d4b8-46d0-9144-f8ba9b8b6b8a)

**Comment by Mussuranae** [comment]
I added an input for the title of the other videos. See PR #4628 

But for teaser/trailer/etc, I asked Anastasiia what to do, and we had a discussion about a solution to display link and video uploader in the same time IF we want to use link again.
There are some points here we have to discuss after the holydays :
- Do we want to use link again ? Or do we remove them once for all ? (for dev : you will need to clean the DB)
- Anastasiia doesn't want 10 file uploader on this page because it will become super ugly and stuffy for the user, so I propose to add a select to choose which type of video they want to upload (teaser/trailer/other/etc), and we can let also a title for every video.
- Next question will be how we display them in marketplace movie view ? But that is for later I guess

Here is a screen she made quickly during our discussion, with a possibility to upload a video or to add a link, depending on what we want.
<img width="669" alt="screen-video" src="https://user-images.githubusercontent.com/48033264/103088213-6723df00-45ea-11eb-80a1-849e0780fe69.png">
