### ISSUE TITLE
Festival Dashboard - Event calendar + small event form

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4434]
Tester: @phpgeekfr  
Bug fix: @GrandSchtroumpf

**Comment by phpgeekfr** [comment]
@GrandSchtroumpf 
Everything seems to work well.

Few remarks:
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/e21db074-7bc4-4c86-bae4-1f513d5f939b)

All day and private checkboxes can be checked by mistake because the clickable zone is taking all the width of the component.

The "More details" button could be changed to "add more details"

**Comment by phpgeekfr** [comment]
Also, start date can be higher than end date:

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/296a6e5a-6bda-4b3c-8e02-0a0b3bc58439)

console : 
```
angular-calendar Event `start` property occurs after the `end` 
Object { id: "dUJuFocYobDYRk8IzsjS", title: "New event", ownerId: "bCHWl9QAtX5vm4OmWgcq", isPrivate: true, type: "meeting", allDay: false, isOwner: true, start: Date Thu Dec 24 2020 05:00:00 GMT+0100 (heure normale d’Europe centrale), end: Date Wed Dec 09 2020 23:00:00 GMT+0100 (heure normale d’Europe centrale), meta: {…}, … }
```

**Comment by Jackseed** [comment]
+1 for "Add more details" and the other feedbacks

**Comment by stephanie-cascade8** [comment]
I'm currently making my design review for **Meetings** here:
https://docs.google.com/document/d/1w96ykUZR92qCWa1xXt_1XcyCAokIihXksnNucAZEpQ4/edit#

**Comment by phpgeekfr** [comment]
Unnecessary vertical scroll bar in https://staging.archipelmarket.com/c/o/dashboard/event

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/7a05ada7-7bc5-49a1-969e-788f8eab9298)

**Comment by stephanie-cascade8** [comment]
I'm currently making my design review for **Meetings** here:
https://docs.google.com/document/d/1w96ykUZR92qCWa1xXt_1XcyCAokIihXksnNucAZEpQ4/edit#

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/101781592-4cd10800-3af8-11eb-8589-cab0f429a663.png)
Looks like Event title (here "New event") is part of the event type list
(I can't open Stéphanie's review so maybe that already in it)

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/101790924-42683b80-3b03-11eb-9657-1eddc81f0715.png)
"Title" between the arrow shows "Thursday December 17". This is a weird behaviour. Might be because today is Thursday so on this week's calendar, it shows today's date 'Thursday December 10". But when I change week it stays on Thursday which is a weird behaviour I think. Should show the week as a title, like "December 13-19"

**Comment by RemcoSimonides** [comment]
Done
