### ISSUE TITLE
Add video quality & sound parameters on meetings

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4496]
This settings should be enabled for both buyers & sellers. Video quality & sound should only concern the shared video, not visioconf.

Specs from @jdrns to be contact if questions:

We won't be making mock ups for this issue (the mock ups we have are too different from what's on prod and it would take a lot of time to make it again) so you can have a look at [the wireframes](https://www.figma.com/file/vBJGpcE68Fyc8IPNEi5slY/Media-Ressources?node-id=0%3A1) (under sound parameters). 

Things that need to be changed/added: 
- [ ] Add icons allowing user (on both seller and buyer side) to [mute](https://drive.google.com/file/d/1sSW3Lu34ebyaMKIQn21EUjJ30QR98vby/view?usp=sharing) and [unmute](https://drive.google.com/file/d/1CbFjSVW5u4eXkVmdyxBGGBm3YRKwFEeb/view?usp=sharing) the shared video (with tooltip) 
- [ ] Slider to modulate sound 
- [ ] On hover over our correspondant 'screen', we currently have the eye icon in order to stop someone's camera. Change it to the camera icon to [turn off](https://drive.google.com/file/d/1MjnRTYn_CqcliFjUeX5Gf_hnQl51tUmI/view?usp=sharing) and [turn back on](https://drive.google.com/file/d/1CPvufKzVl3kHjMDDd-Dg6kEoh8LOX5pl/view?usp=sharing) the other person's camera (same as the one used to stop your own camera).

**Comment by Jackseed** [comment]
ok let's forget the video quality thing then

**Comment by Jackseed** [comment]
There is also an open UX question regarding to sound: if users don't have headphones, it multiplies video sound xParticipant which is pretty annoying and ruin the experience.
Could be resolved by sound parameters on both shared video and videoconference

**Comment by Jackseed** [comment]
Comment from retro 48: sound settings must be enable for both sellers & buyers, thus should be near the full screen button below shared video

**Comment by jdrns** [comment]
Wireframe is done [here](https://www.figma.com/file/vBJGpcE68Fyc8IPNEi5slY/Media-Ressources?node-id=0%3A1) at the bottom under sound parameters

**Comment by jdrns** [comment]
We won't be making mock ups for this issue (the mock ups we have are too different from what's on prod and it would take a lot of time to make it again) so you can have a look at [the wireframes](https://www.figma.com/file/vBJGpcE68Fyc8IPNEi5slY/Media-Ressources?node-id=0%3A1) (under sound parameters). 

Things that need to be changed/added: 
- [ ] Add icons allowing user (on both seller and buyer side) to [mute](https://drive.google.com/file/d/1sSW3Lu34ebyaMKIQn21EUjJ30QR98vby/view?usp=sharing) and [unmute](https://drive.google.com/file/d/1CbFjSVW5u4eXkVmdyxBGGBm3YRKwFEeb/view?usp=sharing) the video (with tooltip) 
- [ ] Slider to modulate sound 
- [ ] On hover over our correspondant 'screen', we currently have the eye icon in order to stop someone's camera. Change it to the camera icon to [turn off](https://drive.google.com/file/d/1MjnRTYn_CqcliFjUeX5Gf_hnQl51tUmI/view?usp=sharing) and [turn back on](https://drive.google.com/file/d/1CPvufKzVl3kHjMDDd-Dg6kEoh8LOX5pl/view?usp=sharing) the other person's camera (same as the one used to stop your own camera).

**Comment by pldespaigne** [comment]
I'm not sure it's relevant, but we can already mute/unmute meeting attendees. This feature existed from day 1 of the meetings

**Comment by jdrns** [comment]
The idea here is only to mute the sound from the video that is on your screen, but that would allow you to continue commenting it, so everybody could watch it without the sound and talk about it

**Comment by pldespaigne** [comment]
Oh ok ! so if I understand correctly, it's only for the media sharing videos on the left side of the meeting (not for attendees visio)

**Comment by jdrns** [comment]
Yes exactly, that bit is about it 
> * [ ]  Add icons allowing user (on both seller and buyer side) to [mute](https://drive.google.com/file/d/1sSW3Lu34ebyaMKIQn21EUjJ30QR98vby/view?usp=sharing) and [unmute](https://drive.google.com/file/d/1CbFjSVW5u4eXkVmdyxBGGBm3YRKwFEeb/view?usp=sharing) the video (with tooltip)
> * [ ]  Slider to modulate sound

And this bit may have been confusing. This already exists, we just want to change the icon to make it clearer
> * [ ]  On hover over our correspondant 'screen', we currently have the eye icon in order to stop someone's camera. Change it to the camera icon to [turn off](https://drive.google.com/file/d/1MjnRTYn_CqcliFjUeX5Gf_hnQl51tUmI/view?usp=sharing) and [turn back on](https://drive.google.com/file/d/1CPvufKzVl3kHjMDDd-Dg6kEoh8LOX5pl/view?usp=sharing) the other person's camera (same as the one used to stop your own camera).

**Comment by Jackseed** [comment]
Thanks @jdrns that's all good for implementation, I switch that issue to dev board
