### ISSUE TITLE
User deletion consequences on event

### ISSUE THREAD

**Issue by Mussuranae** [blockframes/blockframes#4898]
Bruce cleaned the invitation fields and the event field, after we finished our rework of the notification. We have now on the event the `ownerOrgId` that is the organization that organized the event, but for the meeting we have also an `meta.organizerUid` who is the user who created and really organized the meeting.
In CRM, we can delete user, and it will "clean" the `meta.organizerUid` on event of type `Meeting`. But what happens to the event at this moment ?

I don't know how meetings begun, but I guess the organizer is needed. If a meeting has no organizer, can the other people invited to the event access it ? They will received reminder emails and notification if they didn't turn it off.

What do we do with this orphaned event ? Do we delete it ?

The case can occure when we delete someone on CRM but also if admin removed a member of their organization.

**Comment by Jackseed** [comment]
Indeed, I just tested it and it created 2 issues:
[- Nothing found at path: users/userId ](https://sentry.io/organizations/cascade-8/issues/2495370293/?referrer=slack)
[- Cannot read property 'uid' of undefined](https://sentry.io/organizations/cascade-8/issues/2382395267/?referrer=slack)

Since it's only an admin feature to delete a user I would delete the related meetings if it happens so we don't have broken events.

**Comment by Mussuranae** [comment]
And if the user is removed from its org, that won't cancel the meeting, but the organiser won't be able to access and launch the meeting (except if he join a new org ?). Is it ok here ?

**Comment by Jackseed** [comment]
We should test it to be sure of what will happen but I guess if the user is not completely deleted the event will be fine since user object will still be in db

**Comment by phpgeekfr** [comment]
may be related to #6460

**Comment by Jackseed** [comment]
> And if the user is removed from its org, that won't cancel the meeting, but the organiser won't be able to access and launch the meeting (except if he join a new org ?). Is it ok here ?

I tested that use case and it works well: no error spawned and I was able to attend the meeting with both buyer & seller because every other org members are considered as organiser and may accept the buyer to the meeting

**Comment by phpgeekfr** [comment]
definitely related to #6460

**Comment by phpgeekfr** [comment]
Given that removing an user is only allowed by an admin via CRM and since the "deletion simulator" will display `XX meetings event(s) will have no organizer anymore`, also given that removing an user from an org does not create any issues cf @Jackseed's  previous comment, I think we can close this issue.
@Jackseed can you confirm ?

**Comment by Jackseed** [comment]
Yes let's close this
