### ISSUE TITLE
Movie import improvements

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5162]
Some columns are missing
- [x] Logline
- [x] Review critic's name
- [x] Positioning 
- [x] Social Responsibility Goals 
- [x] Sales pitch 

Versions are not working
- [x] Original version Authorized (column BC in current file)
- [x] Columns BD to BG with versions neither 

- [x] Company stakeholders are not recognized (columns N to P)

Admin version
- [x] Add a orgId owner to attach movie to another org

Excel used
[https://app.zenhub.com/files/165818079/df29bc8f-5e1f-4975-b8ce-313b5e25b1a5/download](https://app.zenhub.com/files/165818079/df29bc8f-5e1f-4975-b8ce-313b5e25b1a5/download)

**Comment by SamirTouira** [comment]
@Jackseed how did you get this excel template please? We don't seem to have the same basic excel template, I have this:

![image](https://user-images.githubusercontent.com/52285231/119690544-1428af00-be4a-11eb-9e8a-d8f8ebae7af6.png)

instead of (your excel link in this issue):

![image](https://user-images.githubusercontent.com/52285231/119692101-6c13e580-be4b-11eb-8706-234de5d009d3.png)

I cannot import this and continue my tests since I have added some new columns. Otherwise, on my side, everything is almost done and I finish this today 👍
