### ISSUE TITLE
Marketplace movie view - Broken images

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5215]
url staging https://staging.archipelmarket.com/c/o/marketplace/title/c8e3k3RhlE1oQK2RWMJ3/main
url prod https://www.archipelmarket.com/c/o/marketplace/title/c8e3k3RhlE1oQK2RWMJ3/main
user dev+carson-yck@blockframes.io

Promotional images at the bottom of the page are all empty though there are some on prod (not all of them..). 
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/cd9edb89-75cc-49f0-b957-103135a6abcc)
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/a34a75a1-7270-4cf9-9394-d2e18c8dc3da)

**Comment by pldespaigne** [comment]
I checked prod & staging.
The issue is that images exists in db but not in the storage, so it's normal that ImgIx is not able to display them.

I have no idea about why/how it happened, it could be that the owner as deleted the image but the delete code hasn't ran correctly or it can also be a storage ops problem.

**Comment by Jackseed** [comment]
Alright I close this, I guess it's an issue from media on prod
