### ISSUE TITLE
Mat buttons -> transform to link + icon

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5228]
This issue has to be done in 2 steps:
- [x] List where to implement that component
- [x] Design the new component
See below for expected changes

**Comment by jdrns** [comment]
- Content 
###  Invitation 
- [ ] Icon + Accept All 

### Notification 
- [ ] Icon + Mark all as read

### Dashboard / My titles / Title page 
- [ ] Icon + Edit 
- [ ] Icon + See on marketplace

### Marketplace / Home
- [ ] See all + Icon

### Marketplace / Library / Movie page
- [ ] Icon + Add to/Remove from Wishlist
- [ ] Icon + Watch Presentation Deck
- [ ] Icon + Add to/Remove from Script

### Footer 
- [ ] About us
- [ ] Contact us 
- [ ] Legal Terms
- [ ] Privacy Policy




- Market 
###  Invitation 
- [ ] Icon + Accept All 

### Notification 
- [ ] Icon + Mark all as read

### Dashboard / My titles / Title page 
- [ ] Icon + Edit 
- [ ] Icon + See on marketplace

### Marketplace / Home
- [ ] See all + Icon x9

### Marketplace / Library / Movie page
- [ ] Icon + Add to/Remove from Wishlist
- [ ] Icon + Watch Presentation Deck
- [ ] Icon + Add to/Remove from Script

### Marketplace / Screening List
- [ ] Icon + Request Access

### Marketplace / Screening List / Screening Page
- [ ] Icon + Request Access

### Marketplace /Calendar / Meeting Page ??? (pas sur)
- [ ] Icon + Request Access

### Footer 
- [ ] Contact us 
- [ ] Legal Terms
- [ ] Privacy Policy





- Financiers
###  Invitation 
- [ ] Icon + Accept All 

### Notification 
- [ ] Icon + Mark all as read

### Dashboard / My projects / Project page 
- [ ] Icon + Edit 
- [ ] Icon + See on marketplace

### Marketplace / Home
- [ ] See all + Icon

### Marketplace / Library / Movie page
- [ ] Icon + Add to/Remove from Wishlist
- [ ] Icon + Watch Presentation Deck
- [ ] Icon + Add to/Remove from Script

### Footer 
- [ ] Contact us 
- [ ] Legal Terms
- [ ] Privacy Policy

**Comment by jdrns** [comment]
After discussion with @stephanie-cascade8, here are the conclusions we reached:
### Movie Page
[Here](zpl.io/blKQozk) is the new button ready to implement on the movie page with its [hover state](zpl.io/2yg45Qp) and [selected state](https://zpl.io/Vk4gLl8) (Wishlist only). For the button "Add to Wishlist/Remove from Wishlist", the new icons can be found [here (outline)](https://drive.google.com/file/d/1S8t-Nq4fBEguMkUXtYxLwHozRirHoIQV/view?usp=sharing) and [here (filled)](https://drive.google.com/file/d/13NK-DTtPtAfYa1iaX8i8VNJdU-SYX6Cb/view?usp=sharing), for the rest, no changes, we should use the same icons as previously.

### In text links
As for (in-text) links, they all should be displayed underlined. The underline style should be reserved to links only. On hover, the underline should move downward a little bit. We checked with @GrandSchtroumpf and the property text-underline-position could potentially be used (not final, can be discussed after tests, need to check if this animation doesn't make the whole page move because of paddings or else). 
**Expected animation:** 
![Kapture 2021-03-29 at 09 28 21](https://user-images.githubusercontent.com/79836137/112807253-f7edd900-9077-11eb-9ff9-9c4d8af420f4.gif)

**Where it should be visible:**
- [ ] Sign up page / Terms and conditions + GDPR
- [ ] Dashboard / My Events / More information / My File page
- [ ] Dashboard / Financial elements / Financing plan / Budget Page
- [ ] All Upload boxes / browse

### Buttons updates
Finally, some buttons were lacking styling: 
- [ ] Log in page / Forgot password? --> Should be a basic button with basic colour
- [ ] Dashboard / Home / Import in bulk / Need help? --> Should be a basic button with basic colour

**Comment by Jackseed** [comment]
Perfect thanks @jdrns @stephanie-cascade8, I'll pass that issue directly to devs as everything is listed and validated

**Comment by RemcoSimonides** [comment]
This issue seems not to have been implemented properly

**Comment by stephanie-cascade8** [comment]
WIP Just have a new button in the movie header. The css is the same as the classic current mat-button with this variant:
------------------------------------------
- [ ] padding: 14px 24px;
- [ ] background: #ffff ;
- [ ] opacity: 0.4; 

Hover state

- [ ] opacity: 0.6

**Comment by stephanie-cascade8** [comment]
[Zeplin component ](https://zpl.io/bPyAjgx)

**Comment by RemcoSimonides** [comment]
Created new issue for the button #6497
Closing this one
