### ISSUE TITLE
Contract excel import - Support discontinued mandates

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5267]
Some edge cases may include mandates that have 2 time period, let's say:
- PTV France 2020-2025
- break
- PTV France 2027-2030
With the current import we can't handle this edge case and have to create 2 mandates instead of one. 
Dashboard users may not understand that + it will create unnecessary sales. 

We need a way to create this edge case as one and only mandate instead of 2.

**Comment by fritzschoff** [comment]
For the future dev who will work on that: The issue is about the when. 
- If a sale is going to be imported before the mandate from which the sales originated, You would safe the ID somewhere and when you come across the mandate, you would update the contracts accordingly. But how do you know that the sale is from a mandate? You could check for the parentTermId column, but this would be empty? Or if there is something in in this column, you would need to parse it and say, this is a ref to a row in the same excel sheet or it is already on the database and you would need to fetch the mandate and upate the sale? If parsing data is involved with the excel sheet this could always lead to bugs, because the excel sheet somethimes puts numbers as string depending on the configuration of the clients excel program.
