### ISSUE TITLE
Urgent theme corrections

### ISSUE THREAD

**Issue by stephanie-cascade8** [blockframes/blockframes#5405]
**This task is a draft**
After the end of our partnership with ScreenDaily, we should update the app with corrections on some colors and typefaces 
that were implemented with the new builder. 

To do : 

- [x] change padding on mat-buttons from [14px 32px] to [12px 8px] globally.(Clélia)
- [x] Replace primary color by accent on the mat-button bellow "sign up" or sign-in... on the login pages.(Clélia)
- [x] Replace the link "forgot password" by a basic mat-button. (Clélia)
- [x] Replace all h1 by h2 (except landing pages and first h1 in each page) (Remco)
to test live with a dev!
- [ ] Test new illustrations behaviour (with builder colors inside to make them dynamic in other themes)
I'll present what we could do during this next design sprint review (Tuesday 13th. of april)
[Notion](https://www.notion.so/cascade8/Dynamic-Illustrations-67bb6d780bed4b9d8a65d9c680557ffc)

- [x] update colors association to components in the builder (François)
https://www.notion.so/cascade8/Theme-Color-Builder-b3c2b1bdcfc74e5eafe1ad7a452912fd
(see the mention [corrected] on css lines that have to be changed in the code.
file to change in the css : 
https://github.com/blockframes/blockframes/blob/develop/styles/themes/blockframes.scss
**/!\ Check with Stéphanie before merging for live review**

- [x] update background .svg login with the right background positions and sizes. (Clélia)
———————— 
background-image: url(assets/images/dark/rocket_background.svg);
background-size: 70%;
background-position: bottom right;
————————
- [x] correct login html and css (some position absolute on logo and other elements make the page weird , it should be scrollable such as any other page) (Clélia)

**Comment by RemcoSimonides** [comment]
- [ ] Make h2 a bit bigger:
`font-size: 26px;
font-weight: 700 (bold)`
Suggestion from @stephanie-cascade8 so when finished please show her

**Comment by RemcoSimonides** [comment]
@RemcoSimonides create new (cleaner) issue for this one

**Comment by Jackseed** [comment]
@Mussuranae could you update on this issue? I think it's deeply related to #4489, mb even a duplicate since it's only about illustrations and builder now

**Comment by Mussuranae** [comment]
There two things here :
- Images are updated since I merge my PR about the issue #4489 and they will change from dark to light if we change the theme.
- The builder we talk about in this issue isn't ready yet. It's a specific builder for images and not our current theme builder. it will be deeply link to the theme, and I guess we will have at the end  only one image for all theme we want. That means we won't have two times the same image anymore (one for dark theme, one for light theme).

But this builder will take a lot of time to be created and settled. Maybe if we have an issue about it in the design dashboard, we can close this one. For more information about the images builder, there is this notion [page](https://www.notion.so/cascade8/Illustrations-system-67bb6d780bed4b9d8a65d9c680557ffc), and you can ask @stephanie-cascade8 also for the detail

**Comment by RemcoSimonides** [comment]
[This comment](https://github.com/blockframes/blockframes/issues/5405#issuecomment-822445702) is also open @Mussuranae

Looking at the [notion page,](https://www.notion.so/cascade8/Illustrations-system-67bb6d780bed4b9d8a65d9c680557ffc) it looks like a lot of 'design' has already been done. We just need to add the colors to the builder and use those colors in the illustration, right? What else do you need from design?

**Comment by Mussuranae** [comment]
Stéphanie needs to talk about it with François. At this moment I have no green light to do it, and maybe we will have to replace all SVG again (because we will need to replace colors inside SVG by variables ? I don't know).
I can do the last comment quickly, but for the illustration builder, please check with François before.

**Comment by RemcoSimonides** [comment]
Created new issues for left-over tasks
