### ISSUE TITLE
RELEASE MVP: Movie CRUD, list, view, wishlist 

### ISSUE THREAD

**Issue by fritzschoff** [blockframes/blockframes#5407]
TEST:
Movie list
Movie view => tabs (all apps)
Movie filters (all apps) 
wishlist (check the CRM delete movie implications)
Delete: CRM

**Comment by Jackseed** [comment]
- [ ] Marketplace title list, update "Format" filter list with the same as movie form ordered alphabetically i.e. 
- Documentary
- Feature Film
- Flow
- Short Film
- TV Film 
- TV Series
marketplace
![image](https://user-images.githubusercontent.com/14964443/113005787-0bcb3500-9175-11eb-959a-30bc2af373f3.png)
vs movie form
![image](https://user-images.githubusercontent.com/14964443/113005801-0ff75280-9175-11eb-91e2-b52da162867d.png)

**Comment by fritzschoff** [comment]
@phpgeekfr I see in the code you did something to the component, is this issue done?

**Comment by phpgeekfr** [comment]
I did the first "checkbox" but I did not closed it so we can ad new bugs if any

**Comment by fritzschoff** [comment]
alright

**Comment by Jackseed** [comment]
user vchoukroun+1@cascade8.com
url https://staging.archipelcontent.com/c/o/dashboard/title
- [ ] Small UI bug on empty catalog dashboard, button text are a bit different on empty "My Titles" than the empty Dashboard page. The space from empty dashboard is the good one

dashboard:
![image](https://user-images.githubusercontent.com/14964443/113126720-391cef00-9218-11eb-9ee1-f0de32fa7f21.png)

my titles
![image](https://user-images.githubusercontent.com/14964443/113126735-3de1a300-9218-11eb-9080-2614725bb3a1.png)

**Comment by fritzschoff** [comment]
done

**Comment by Jackseed** [comment]
### Dashboard 
#### Archipel Market
- [ ] Change text "Import Movies" to "Import Titles"

#### Archipel Content
**My Titles**

- [ ] Add "Import Titles" button and "+" for adding one title as it's in Market 

- [ ] Align the title and the buttons (same as Market)

from ![Снимок экрана 2021-03-31 в 10.34.01.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/db2a50a1-fea4-4959-8beb-86f5dbf2acbd)

to 
![Снимок экрана 2021-03-31 в 10.34.20.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/1c36583e-f764-484c-9a91-9c79f42939af)

**Comment by Jackseed** [comment]
@phpgeekfr yes please

**Comment by Jackseed** [comment]
### Movie form
- [ ] Main Information -> if choose TV series, change wording from "Season**s** Number" to "Season Number" 
![Снимок экрана 2021-03-31 в 10.40.49.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/7f6a9e66-279f-4c71-9b19-00d79c41d54e)

/// Not sure if doable for that release but would be great:
- [ ] **on applications that have a validation process** (ie movie.storeConfig.status from draft to submitted > catalog + financiers):
1. Summary Page -> Change CTA text from "Publish to Marketplace" to "Submit for validation" 
![Снимок экрана 2021-03-31 в 11.33.48.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/1c131dd6-7496-4286-a4af-f272e34329fb)
2. Change snackbar from "Movie online !!!" to "Title successfully submitted."

**Comment by phpgeekfr** [comment]
> If possible - List only movie that has a storeConfig.appAccess === true for the current app. ie don't list movies that don't have a catalog appAccess in catalog

Yes this is already the case for other apps

**Comment by phpgeekfr** [comment]
> Change snackbar from "Movie online !!!" to "Title successfully submitted."

@Jackseed on MF it is `Your title was successfully submitted!` should I use this also for catalog & content or do we use your sentence everywere ?

**Comment by Jackseed** [comment]
@phpgeekfr yes please change it also for MF to "[ Title name ] was successfully submitted." (same as catalog)
also can you change festival text "Movie online !!" for "Title successfully published." plz?

**Comment by Jackseed** [comment]
### Movie form
- [ ] Don't know if possible but can we pre-select "Released" on catalog for the movie form production status?
![image](https://user-images.githubusercontent.com/14964443/113280455-98e0cc00-92e4-11eb-9fb6-2891b617ccc1.png)

### Dashboard My Titles
- [ ] Sorting filters are not all working 
![1](https://user-images.githubusercontent.com/79836137/113003710-46cc6900-9173-11eb-9eb9-016fc9cfa4ca.gif)

**Comment by Jackseed** [comment]
- [ ] Catalog - Marketplace movie list: add the same clear all filters button than festival and financiers
![image](https://user-images.githubusercontent.com/14964443/113281179-81561300-92e5-11eb-9dce-035bc77b6fdf.png)

**Comment by Jackseed** [comment]
- [ ] Marketplace title list: country of origin filter only looks for the first word of a country so compound words doesn't work (e.g. "States" for United States of America or "Korea" for South Korea)
 ![6](https://user-images.githubusercontent.com/79836137/113115260-8abf7c80-920c-11eb-9d2d-b0515540215c.gif)

**Comment by Jackseed** [comment]
- [ ] Marketplace movie view, video section - Use the video type below the video to describe it if there is no video title
<img width="724" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/14964443/113292104-53c49600-92f4-11eb-87b3-bf88052b96ea.png">

**Comment by Jackseed** [comment]
user: dev+bryana-csh@blockframes.io
url: https://staging.archipelmarket.com/c/o/marketplace/title/5Z7LhR6CqRLdQ1ARS2qG/main
- [ ] Marketplace movie view, director component:
1. If director's category is empty, display nothing but keep the same size for the header. E.g here remove "Director's Category: Director"
![image](https://user-images.githubusercontent.com/14964443/113292515-e7966200-92f4-11eb-9b05-f84249f58350.png)
2. If director's description is really long user can click on it to open a dialog with full text. On that dialog, remove the director's status (eg here "confirmed)
![image](https://user-images.githubusercontent.com/14964443/113292668-1ad8f100-92f5-11eb-8a02-3f3d30324fdd.png)

**Comment by Jackseed** [comment]
user dev+marlon-qgu@blockframes.io
url https://staging.archipelmarket.com/c/o/dashboard/tunnel/movie/5Z7LhR6CqRLdQ1ARS2qG/reviews
https://sentry.io/organizations/cascade-8/issues/2298657112/?project=1540126&referrer=slack
Movie form
- [ ] Can't save the form if I de-select a festival premiere. This sentry error looks related 
```
Error: Uncaught (in promise): FirebaseError: [code=invalid-argument]: Function WriteBatch.update() called with invalid data. Unsupported field value: undefined 
````
![Kapture 2021-04-01 at 14 26 48](https://user-images.githubusercontent.com/14964443/113293708-68099280-92f6-11eb-837c-73fa51cb1a9e.gif)

**Comment by Jackseed** [comment]
**Small text changes**
- [ ] Dashboard movie view - Other Videos - If the video type is promo reel it should be written "Promo Reel" instead of "Reel"
![image](https://user-images.githubusercontent.com/14964443/113296995-66da6480-92fa-11eb-96a3-afbf175cecf2.png)

- [ ] Movie form other videos change "Upload other videos such as trailer, teaser promotional clip, etc..." to "Upload other videos such as a trailer, teaser, promo reel, etc."
![image](https://user-images.githubusercontent.com/14964443/113297252-ac972d00-92fa-11eb-9461-1fb51d6ddf1c.png)

- [ ] When leaving the form with unsaved changes, change the dialog texts:
"You are going to leave the Movie Form." >> "You are about to leave the form."
"Pay attention, if you leave now your changes will not saved." >> "Some changes have not been saved. If you leave now, you will lose these changes."

**Comment by Jackseed** [comment]
- [ ] Miss a space after the first coma when there are more than 1 director. Just between 1 & 2, between 2 & 3 it looks good...
![image](https://user-images.githubusercontent.com/14964443/113309861-e0c51a80-9307-11eb-9161-0a2f427d8e05.png)

**Comment by Jackseed** [comment]
### MARKETPLACE MOVIE LIST
- [ ] All apps - Remove s from "Genre" filter (should show "Genre" not "Genres")
![image](https://user-images.githubusercontent.com/55785823/113309344-58467a00-9307-11eb-9329-51e42e36bddd.png)
- [ ] Festival - Remove s from "Sales Agents" filter (should show "Sales Agent" not "Sales Agents")


### CATALOG MARKETPLACE MOVIE VIEW
- [ ] Banner component should show the seller logo with a link to the public org view, same as festival
![image](https://user-images.githubusercontent.com/55785823/113308795-cdfe1600-9306-11eb-9187-dfc1ed8f0c9b.png)

### CATALOG MARKETPLACE ORG VIEW
- [ ] If possible to do it only for catalog and not the other apps, change first tab name & title to "Catalog" instead of "Line-up"
![image](https://user-images.githubusercontent.com/55785823/113308930-f423b600-9306-11eb-8e29-1af938332876.png)
- [ ] Same thing, if possible to do it only for catalog, show X films in catalog here (instead of line-up)
![image](https://user-images.githubusercontent.com/55785823/113308907-eec66b80-9306-11eb-8af8-51319d859be4.png)


### Whishlist
- [ ] Whishlist titles should be filtered according to movies appAccess > display only festival movies on festival whishlist and catalog titles on catalog whishlist


### DASHBOARD MOVIE FORM
- [ ] Add capitals to: International Title / Original Title
- [ ] Update Running time hint to: "Please specify your title's duration."
- [ ] Running Time field appears red as soon as I arrive on the page. I don't think that is normal behaviour
![image](https://user-images.githubusercontent.com/55785823/113309981-00f4d980-9308-11eb-829f-6a46fb4487c1.png)

**When Content Type = TV Series:**
- [ ] Add capital to: "Number of Episodes"
- [ ] Update hint to: "Please specify the number of episodes in this season."
- [ ] Delete the "s" in "Season Number"
- [ ] If it's simple, I think it'd be more logical to interchange the 2 fields (1. Season Number 2. Number of Episodes) but it's not of major importance obviously.
![image](https://user-images.githubusercontent.com/55785823/113310384-782a6d80-9308-11eb-89b0-40f02f802adf.png)
- [ ] Update Runtime Title/Placeholder to "Average Episode Running Time" (only for TV Series if that's possible, otherwise don't change)
- [ ] Update hint to: "Please specify the average duration of an episode."
![image](https://user-images.githubusercontent.com/55785823/113310826-ec651100-9308-11eb-921a-0a3087ece572.png)

- [ ] Update "Other Genre" hint: Please fill in genre(s) yourself if you did not find the relevant genre(s) above."
![image](https://user-images.githubusercontent.com/55785823/113311115-3e0d9b80-9309-11eb-98aa-8316c7458dd1.png)

- [ ] Update the following titles with an "s": Selection**s** **&** Review**s** / Festival**s** **&** Award**s** / Other Festival**s** **&** Award**s** _(in the movie form, the movie form side bar, the dashboard movie view and the marketplace movie view)_
![image](https://user-images.githubusercontent.com/55785823/113311868-06532380-930a-11eb-94c5-cca93b5cc616.png)
![image](https://user-images.githubusercontent.com/55785823/113312148-43b7b100-930a-11eb-9bfd-04f388627db6.png)

- [ ] Festival Name field has a strange behaviour: hint disappears when the field is in error mode (red)
- [ ] Replace "Custom Festival" to "Other Festival & Awards"
![image](https://user-images.githubusercontent.com/55785823/113311361-862cbe00-9309-11eb-9c4f-6913ec3f87ad.png)
![image](https://user-images.githubusercontent.com/55785823/113311392-8dec6280-9309-11eb-8fd7-e1f4ae6ce049.png)

- [ ] Add spacing before "Other Videos" in dashboard movie view
![image](https://user-images.githubusercontent.com/55785823/113312269-6944ba80-930a-11eb-8799-697be9667b3c.png)
![image](https://user-images.githubusercontent.com/55785823/113312286-6d70d800-930a-11eb-85b7-7f1b5d880853.png)

**Comment by Jackseed** [comment]
- [ ] Add "Animation" in the format/content type list & update excel import templates accordingly 
users: [import-title-template-customer.xlsx](https://github.com/blockframes/blockframes/files/6257599/import-title-template-customer.xlsx)
admin: [import-title-template-admin.xlsx](https://github.com/blockframes/blockframes/files/6257601/import-title-template-admin.xlsx)

(I've also added the new genres to templates)

**Comment by Jackseed** [comment]
@fritzschoff I think you made the fix for the wishlist, do you think we can update the navbar icon number according to the titles listed from the current app? Currently it makes that strange 4 (navbar) vs 3 in fact listed
![image](https://user-images.githubusercontent.com/14964443/113582404-9f46af00-9628-11eb-9993-f3b45c065938.png)

**Comment by Jackseed** [comment]
- [ ] Marketplace title view - review card: image is zoomed in
![image](https://user-images.githubusercontent.com/14964443/113590371-d8841c80-9632-11eb-9339-765a9d411822.png)

**Comment by fritzschoff** [comment]
the image is zoomed is because it is a different version than in the light version. Need to check with Stephanie

**Comment by Jackseed** [comment]
- [ ] If someone has an open PR: change "All projects" tab name on catalog dashboard title list for "All" instead

**Comment by fritzschoff** [comment]
gonna do that

**Comment by Jackseed** [comment]
Thanks, one another small UI change if you got time
- [ ] change the icon in the marketplace movie view, inside the banner there are action buttons "view presentation deck / scenario / moodboard" currently it uses the play icon but instead it should be the pdf one `document.svg`. The play icon should remain for the "view trailer / other videos " button
![image](https://user-images.githubusercontent.com/14964443/113710200-b4344880-96e3-11eb-822c-7949dbdc975e.png)
