### ISSUE TITLE
Watch time

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5412]
### Description 
We need a way to display watch time per users for screenings. These stats will be saved and always displayed so we shall keep it. 

### Specs
- unity: min
- saved and loaded from firebase

### Acceptance criteria
- [x] First, validate count strategy 
Then implement on event form
- [x] New screening stat column with watch time per user
- [x] Average watch time on a screening

![image](https://user-images.githubusercontent.com/14964443/112961859-0acedf00-9146-11eb-87fc-dfe0a127819b.png)

**Comment by pldespaigne** [comment]
Here are the way we can count watch-time, ordered from simplest/fastest to longest/more complex:
- (A) Measure only watch time when the user leave the screening: super simple but we can loose the data if the user close tab/browser instead of "normally" leaving the screening
- (B) Measure watch time every X seconds or minutes (depending on needed precision (lower X = more update = greater cost) ): a little more complex but if user "hard" leave we still get a precise watch-time modulo X

**Note**: with the (A) & (B) methods above we only get the "raw" watch-time = number of time a user spend on a screening but we don't know which part of the screening was seen. *For example if we have a screening with a duration of 2min and we measure a watch-time of 4min we don't know if the user has seen the entire screening twice or just the 1st minutes 4 time in a row.*

- (C) Measure watch time associated with the position in the video: pretty complex although pretty precise measurement, we could still lost the entire watch time or the last slice if the user "hard" leave.
- (D) Same as above but with a continuous measurement every X seconds or minutes: the most precise but also the most complex and costly solution

**Note**: with the (C) & (D) methods we get a really precise watch time but it will be more costly and take more space in db. Moreover to be really insightful for sellers the methods (C) & (D) will probably require a better ui (maybe something like the pic bellow) than "just" a duration in seconds/minutes
![image](https://user-images.githubusercontent.com/5858657/112991377-55ad1e80-9167-11eb-9da8-11ec826baaef.png)

**Comment by Jackseed** [comment]
@pldespaigne thanks for the recap!
Re the (B) solution, could X be a variable of content length like 10% of the full video duration? or does it have to be "5min"?

**Comment by pldespaigne** [comment]
A fixed static X will be more simple, we can easily go fro something like 30s or 1min (should be fairly precise and not too costly).
A dynamic (like X = 10% of duration) is still possible although more complex.
You can consider dynamic X as (B.bis) & (D.bis) solutions

**Comment by Jackseed** [comment]
@pldespaigne ok let's go for solution B with a 1min X. 
Also please consider not counting "pause" time as watch time

**Comment by GrandSchtroumpf** [comment]
@pldespaigne where do you want to store the measurement ? On firestore or indexedDB / localstorage ? It might cost a lot to push to firestore every min

**Comment by pldespaigne** [comment]
Indeed plan to store watch-time in firestore, I don't think it will cost a lot (we can still increase the update duration if needed)

My estimation is that a screening with a video of 10h viewed by 10,000 users will cost us ~$30 at most

Here is the calculation if you want:
firestore writes : $0.18 / 100K = $0.0000018 / writes
10h = 600 minutes = 600 updates for one user = 6M updates for 10,000 users
6M x $0,0000018 = $10.8
lets triple the cost to take into account storage and network (of a single integer value) = $32.4

**Comment by Jackseed** [comment]
OK cool we can definitely handle that cost
