### ISSUE TITLE
RELEASE MVP: CMS + homepages

### ISSUE THREAD

**Issue by fritzschoff** [blockframes/blockframes#5418]

**Comment by Jackseed** [comment]
- [ ] Still an undefined when no image on the banner I thought it was fixed by someone already 
![image](https://user-images.githubusercontent.com/14964443/113120188-9e211680-9211-11eb-830c-c4e847e7ea63.png)
![image](https://user-images.githubusercontent.com/14964443/113120220-a5482480-9211-11eb-9f45-89a2abcec536.png)

**Comment by RemcoSimonides** [comment]
@Jackseed It was fixed on festival only ^^ good thing you tested catalog

**Comment by Jackseed** [comment]
- [ ] New illustrations to implement as fallback when stats are empty (one per stat - views / promo elements / wishlist)
[illustrations-empty-stats.zip](https://github.com/blockframes/blockframes/files/6242615/illustrations-empty-stats.zip)

**Comment by Jackseed** [comment]
- [ ] Change link from the "+" button to the movie tunnel instead of excel import > `/c/o/dashboard/title/lobby` change also the tooltip for "Add a new Title"
![image](https://user-images.githubusercontent.com/14964443/113278949-d2b0d300-92e2-11eb-802d-186f1fbef55f.png)

- [ ] Add  "Add a new Title" tooltip on that same "+" button in `c/o/dashboard/title` 
![image](https://user-images.githubusercontent.com/14964443/113278967-d80e1d80-92e2-11eb-93c1-91e3caf83ee6.png)
