### ISSUE TITLE
Thinner toolbar

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5558]
Following [design improvement list](https://docs.google.com/spreadsheets/d/1Eh7TtguUz212ahReXIzEnYdbYLODKFrFaq7BCCjmjsc/edit?ts=604f787d#gid=0), toolbar could be thiner everywhere. 

We need design proposition to check what's possible

**Comment by stephanie-cascade8** [comment]
We should reduc the toolbar's height from 80px to 68px if possible.
In order to be able to do that, we need to reduce the padding of filled &:or stroke buttons inside the toolbar. 
Some have a line-height that should be reduced to 16px. Padding-top and bottom inside buttons dhould be 8px. (can we have that exception only for buttons inside the toolbar?)

**Comment by stephanie-cascade8** [comment]
after doing some research on the responsive and grid system. The latter might impact the toolbar ratio. Let's pause this subject untli we test the grid layout?

**Comment by jdrns** [comment]
After various tests with @stephanie-cascade8, we figured that the size of the toolbar was mostly problematic on the library page. Work is being done on [that issue](https://github.com/blockframes/blockframes/issues/5559) in order to create a new component for the search bar and filters. 

If it is validated according to plan, we don't need to rework the toolbar

**Comment by Jackseed** [comment]
Ok let's close it then
