### ISSUE TITLE
Create a component for filters and film research

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5559]
A lot has been said on that topic though not reported on any issue. Mainly filters take too much space when scrolling down on the title list. It worths creating one component that includes the search bar and the filters as it's used in many list pages (org, titles, events).

We now need UI propositions to check what's possible. This issue is linked to #5558

**Comment by Jackseed** [comment]
Following user tests, we also noted that filters are not really visible for buyers. Same for the search bar, especially after user scrolls in the page

**Comment by Jackseed** [comment]
- [ ] Add the same we used to have "there are XXX results"

**Comment by stephanie-cascade8** [comment]
**Check out of current situation**
list of problems to solve by UI.

- The whole filters area takes too much space on the height
- Filters shouldn’t look like buttons (not the same use)
- Filters are too big
- Unnecessary spaces: 
  under the field caused by the invisible hint
  under filters buttons
  on top of the field component (place for label?)
- When filters are selected they are primary (wrong use of this color here)
- When filters change but results remain the same for this search, 
nothing happens in the results list. It gives the wrong impression that nothing happened.
- Remake refresh button (improve shape and affordance)
- Find something better on mobiles and tablets that would 
enable avoiding the horizontal scrollbar

**Comment by stephanie-cascade8** [comment]
**UI Solution (technical review needed)**

[Zeplin component](https://zpl.io/aNYZ1D9)

**Comment by stephanie-cascade8** [comment]
[Zeplin here ](https://zpl.io/VKBDvN7)

**Comment by Jackseed** [comment]
Ok great I think you answer pretty much all the problems listed above in a nice way! 

I 100% approve the new banner & filters (& so do Marie) but I still have 1 concern about telling the user that data has been refreshed. I saw the new filter state within the filter but I'm not sure it's enough. 

Some propositions for your consideration:
- What about adding an animation on loading for the list?
- Adding "There are XXX titles" (just below the banner as it used to be)?

But anyway this component looks good and ready to go 👍

**Comment by stephanie-cascade8** [comment]
> Ok great I think you answer pretty much all the problems listed above in a nice way!
> 
> I 100% approve the new banner & filters (& so do Marie) but I still have 1 concern about telling the user that data has been refreshed. I saw the new filter state within the filter but I'm not sure it's enough.
> 
> Some propositions for your consideration:
> 
> * What about adding an animation on loading for the list?
> * Adding "There are XXX titles" (just below the banner as it used to be)?
> 
> But anyway this component looks good and ready to go 👍

Yeah sure! Something is planned on animating the results reload (even when results of the search remain the same) and haaving the counter move in the results sentence. I'm doing it separately (still need to discuss that with François ;))

**Comment by Jackseed** [comment]
@RemcoSimonides this one is ready for dev, it will be updated with this new issue later related to animation #6441

**Comment by RemcoSimonides** [comment]
Created dev issue: #6474
