### ISSUE TITLE
Invitation emails (org & events) - Pre-fill email address & invitation pass

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5674]
For both org & event invitation emails, when including credentials, the "Activate Account" should be linked to a pre-filled identity page with email address & invitation pass. 

![image](https://user-images.githubusercontent.com/14964443/116560703-ebbc9c00-a901-11eb-81fd-315868594622.png)

@phpgeekfr I'm pretty sure we could do it by adding parameters in the linked url but could you confirm?

**Comment by phpgeekfr** [comment]
@Jackseed  This is because the button does not use the good variable in both "credentials templates" 
```
    credentials: {
      attendEvent: 'd-ce3e57248a694cefacad49bc4c820078', 
      joinOrganization: 'd-f0c4f1b2582a4fc6ab12fcd2d7c02f5c' 
    },
```

![image](https://user-images.githubusercontent.com/1194344/116669741-393b1680-a99f-11eb-99e0-46335576d84b.png)


Template need to use `pageURL` variable that leads to auth/identity with password and email included .
