### ISSUE TITLE
Square around logo

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#5716]
- [ ] I still get this square around the logo. It's not super important to correct I guess, we can live with it but it looks weird.
Remco: I can't reproduce it on Brave. Check other browsers for it.
![image](https://user-images.githubusercontent.com/55785823/117010507-28ffa000-aced-11eb-9b85-e2ea30145447.png)
https://images.zenhubusercontent.com/165818079/54c3857e-3f9f-48d7-a1b7-864f22bbecda/enregistrement_de_l__cran_2021_05_04___16_38_03.mov

**Comment by SamirTouira** [comment]
@RemcoSimonides did you tested on staging? I tested to trigger this on staging in Browserstack but this issue doesn't appears.
I added this css property to fix this in my localhost: 
`.outline-logo {
  outline: none;
}`

And if I remove this CSS property, I see this blue rectangle.

Sorry I really have no way to resolve this since it works in my side

![image](https://user-images.githubusercontent.com/52285231/117184666-41e57f80-add9-11eb-939b-69f14a8e82e5.png)

![image](https://user-images.githubusercontent.com/52285231/117189405-760f6f00-adde-11eb-9eec-d3bad8f3eaf9.png)

**Comment by RemcoSimonides** [comment]
Sorry, I don't understand what you said 😅 You cannot reproduce it on staging but on localhost you can?

Is it possible you've fixed this in your PR with Safari issues already? Because this issue was written before that PR was deployed to Staging.

**Comment by SamirTouira** [comment]
No problem it happens and I may have misspoken. Maybe this is because we need to re-deploy to staging to see this fix but even if i go to staging on Safari I still don't see the blue rectangle around the logo 🤔

**Comment by RemcoSimonides** [comment]
Okay, I guess it's all good then ;)
