### ISSUE TITLE
Event banner / Accept & decline buttons

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5849]
Invitation accept & decline buttons were to be changed but they are also used in other event components. 
We shall have solutions for every accept & decline buttons before changing that meaning:
- Screening list, event item
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/022e87b8-24d7-4a60-ae92-a16e6ed89295)

- Screening view, on the banner ![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/1790ffcc-f556-40b7-9d3f-8ef0b1e827f9)

**Comment by jdrns** [comment]
New mock up for accept/decline buttons for the event banner on [screening list](https://zpl.io/agmpNeZ) and the [event page](https://zpl.io/2Zw7zLd). 

Attention, buttons on the invitation list will be different from these. 

Status 'accepted' and 'declined' need to be re-worked because they do not stand out enough as of today. [An issue](https://github.com/blockframes/blockframes/issues/6040) has been created for that matter.

**Comment by Jackseed** [comment]
Looks good to me. Better check with @GrandSchtroumpf if we can use different buttons in screening list from the invitation list

**Comment by RemcoSimonides** [comment]
@RemcoSimonides Create dev issue
