### ISSUE TITLE
Selection price - Facilitate no price offers

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5892]
During user tests we saw that buyers tend to send an offer without a price. 
It looks like it's too early in the process to have a price to offer at that point. 

Our objective as a platform is to get as many offers as we can. Price is something that can be discussed after but as long as buyers don't send their offers we have nothing to work on. 

This issue is a first step to try and search for alternatives that would switch our mindset: instead of having a price by default and a feature to request a price to sellers; we would favour an offer without price and propose a feature to add a price if requested by the buyer.

**Comment by 2amarkina** [comment]
**[Access to wireframes is here](https://www.figma.com/file/oUCgDCGJndPiVhel04GdIH/%5B-Archipel-Content-Renaissance-%5D?node-id=3343%3A144889)**

**Comment by Jackseed** [comment]
Validated with @GrandSchtroumpf suggestion of a simple hint.
@RemcoSimonides could you create an issue based on the last wireframe please?
![image](https://user-images.githubusercontent.com/14964443/123799337-6a28c080-d8e8-11eb-98de-706c8ca62a52.png)

**Comment by RemcoSimonides** [comment]
Sure I can! But before I do I have a question about "If no price entered, Seller will receive Asking Price" @2amarkina 

Asking Price means the price that the seller asks for the Movie. Is that what you want? Or is it more meant as 'buyer is asking for the price'? Because the seller can't currently enter the 'Asking price' anywhere, right? 
[https://www.merriam-webster.com/dictionary/asking%20price](https://www.merriam-webster.com/dictionary/asking%20price )

P.S. wireframe says recieve instead of receive ;)

**Comment by 2amarkina** [comment]
Exactly, "asking price"=price a Seller wants for a movie. 

Currently, if a Buyer puts "0$" for a film it means that s/he wants to know the price. 

To represent better this situation, with new elements seller and Christophe will receive a message like (will prepare screens on my side): 
_Buyer requested Asking Price._ 

- For the Seller - he won't be able to enter any price, it would be like 0$ for him, for example. 
- Christophe will be able to enter the last price decided after the negotiation.

**Comment by RemcoSimonides** [comment]
Made issue for dev ☝️
