### ISSUE TITLE
Learn how it works gifs 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5953]
2 explanation gifs are needed for the avails section in the title view:
- world map 
- calendar view

**Comment by 2amarkina** [comment]
**Business questions** 
Ok if title is real and org is fake? 
Solution apportée: show click on "Add to Selection", but do not show the Selection page with Title's name. 
Solution confirmed with Marie and Christophe


title used: THE RETURN OF THE CAMELIDS

**Short Map Scenario** 
1. choose VOD rights (to show that have many Rights)
2. highlight fields : exclu, dates
3. choose countries 
4. highlight expansions (open, not fill in)
5. add to selection (click only, not go to selection page)

**Short Calendar Scenario** 
1. choose VOD rights (to show that have many Rights)
2. highlight exclu 
3. choose Belgium 
4. highlight expansions (open, not fill in)
5. add to selection (click only, not go to selection page)

Long scenarios include adding versions / changing dates. 
Problem with long scenarios: as using gifs, user can't pause and / or play back. So short scenarios are privileged. 

Dev team confirmed that we could use videos instead of gifs, which is better for a user: can pause a video or come back. 

[Videos are accessible here]. Choose "Learn Map" and "Learn Calendar" (https://drive.google.com/drive/folders/1ECqTsHwdqo9crtso6ErFygIjwlxBNFjC?ths=true)

**Comment by Jackseed** [comment]
All good for me thanks! @RemcoSimonides could you pass it to devs so we include it for that release if that's possible?

**Comment by RemcoSimonides** [comment]
Videos are implemented.
