### ISSUE TITLE
Filter by Release Year on Catalog

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6066]
The tests showed that buyers were interested in having a possibility to filter the Titles with Production Year. This filter only needs to be implemented in the Catalog app

![Снимок экрана 2021-06-11 в 17.02.41.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/9195627e-e5fa-4539-8fc2-407530fc2273)

**Comment by SamirTouira** [comment]
What do you think about this:


https://user-images.githubusercontent.com/52285231/124799746-2ae81880-df55-11eb-98a0-43995ad38374.mp4



I used the release year from Algolia because we only have this one to be able to filter but nothing about the Production Year (which is different of release year), so should the wording be different than "Production Year"?

Also in the slider, I sliced the years in "10" steps  (5 slices in the slider view). How many steps should we really have?

And the minimal year that I writed in the code is 1970. 2030 for the max year. What is the real values you want?

Thanks by advance for the answer :)

**Comment by RemcoSimonides** [comment]
- [ ] Remove 2030 label
