### ISSUE TITLE
Can't publish a movie after switching it to draft

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6156]
url: https://staging.archipelmarket.com/c/o/dashboard/tunnel/movie/PWN0W8A8ZkTxKYDXFNSp/summary
user: dev+winnifred-exb@blockframes.io

I switched this movie to draft and can't publish it anymore. It says that all mandatory info are not filled in but none seems missing. 
No console error nor Sentry. 

![Kapture 2021-06-30 at 19.49.24.gif](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/e12a66e9-b4fa-4b86-b88e-e93911f714ba)

**Comment by phpgeekfr** [comment]
@Jackseed  It looks like that error is due to new title attributes ( country on boxoffice for example) added during apps development.  

If a movie was set as published 10 months ago, we added new attributes to movie object, so if you put a title to draft, and try to publish it again it will throw errors.

If summary page does not say that there is an error, this is because we have an error on a field that is not belonging to current app, so it is not displayed.


If you create a new film, publish it, put it back to draft and publish it again, it should work ok.

**Comment by Jackseed** [comment]
@phpgeekfr I was a bit afraid of that.. shouldn't our migrations do the job of making old movies fit the new data model?

I've indeed test the movie form and looks good for new movies but we do need to make sure that old ones are consistent with our current data model.

What do you suggest? To me it looks like we should list what's missing to old movies and add it through migrations

**Comment by phpgeekfr** [comment]
Yes but how to define data to put ? For example, old movies are missing "country" in box office. We cannot guess that.

Quicker solution is to check movies via catalog, festival and financiers tunnel to spot missing information and correct them on prod

**Comment by Jackseed** [comment]
Ok so after discussion:
- I'll manually remove the empty box office objects that mess up with the new model
- Bruce is creating a script to have a list of movies that have version issue (languages selected but no version checked)
- I'll change manually the versions as well
We should keep an eye on other old model issues and, in the future, prepare migrations when change like these are made.
