### ISSUE TITLE
Homepage - Thinner top banner

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6175]
- [ ] Remove unessential information and reduce margins
![image.png](https://images.zenhubusercontent.com/5ed89f5adc98f2d44c81b9c0/f0d0c544-10d0-487e-bf1a-89bb175c9e08)
Link to discussion in design issue: #5836

**Comment by Mussuranae** [comment]
Can you put more details about the specs ? What padding do we have to put here now (currently padding of 80px). There are several queries for different sizes of screen, we will need to do some demo to the UI team or get more mockups/wireframes for those different size of screen.

**Comment by RemcoSimonides** [comment]
@stephanie-cascade8 @2amarkina Do you know exact measurements or should the dev do a proposal?

**Comment by stephanie-cascade8** [comment]
> @stephanie-cascade8 @2amarkina Do you know exact measurements or should the dev do a proposal?

We decided to close to issue finally. (no need anymore since our work on the search and filters component )

**Comment by RemcoSimonides** [comment]
Hee @stephanie-cascade8 , this issue is about this section
![image](https://user-images.githubusercontent.com/27687382/127106564-8289c985-99ed-40b2-b85d-afdcba18ca98.png)
Are you sure you want to close it? ^^

**Comment by stephanie-cascade8** [comment]
Oups ! No I thought it was about the toolbar sorry. I'm taking care of it
today

**Comment by RemcoSimonides** [comment]
@stephanie-cascade8 if you have time ☝️

**Comment by stephanie-cascade8** [comment]
> @stephanie-cascade8 if you have time ☝️

Sorry I left this one on hold. I want to discuss this with François this afternoon (on our UI tech meeting) and live test with him.

**Comment by stephanie-cascade8** [comment]
- [ ] Replace margin-top on filled-button by 32px (instead of 80px)

<img width="1109" alt="Capture d’écran 2021-08-30 à 10 02 53" src="https://user-images.githubusercontent.com/66258851/131306896-855ebdce-53b7-4f55-85d5-c4c7a1fc4efa.png">

- [ ] Replace the section padding by 38px (instead of 60px)

<img width="1400" alt="Capture d’écran 2021-08-30 à 10 00 42" src="https://user-images.githubusercontent.com/66258851/131306921-be59667e-e0be-4dbd-ae12-a3db051673b8.png">

- [ ] Show large screenshot of result here and ask for stephanie-cascade8 and Jackseed valid

Expected result
<img width="1440" alt="Capture d’écran 2021-08-30 à 10 00 56" src="https://user-images.githubusercontent.com/66258851/131306948-ed374f8f-c648-44db-b0dc-c3c74725c11b.png">

**Comment by RemcoSimonides** [comment]
The marketplace home page on festival and catalog are using the CMS. If you want the description to disappear then a blockframes admin can simply remove the description in the banner. Note also that any other banner used on this page will have smaller margin-top and margin-bottom too.

This is the result.

![image](https://user-images.githubusercontent.com/27687382/132694883-5ae85661-54bd-48d9-84da-72cd73a95828.png)

![image](https://user-images.githubusercontent.com/27687382/132694936-cc8825e2-6ba0-4ec8-a2ca-edc5635dbb0d.png)
