### ISSUE TITLE
Movie form - New error snackbar message

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6181]
Currently when a field has an error but all the mandatory fields are filled in correctly, if you submit the movie you'll get a snackbar error message: "Missing mandatory fields."

Instead it should be "Errors within the form." (and keep the "Missing mandatory fields" message for, well, mandatory fields missing).

**Comment by Jackseed** [comment]
Side question for the one taking this ticket: could we update the "Missing mandatory fields" message with the name or amount of fields missing?

**Comment by Mussuranae** [comment]
@Jackseed I think it will be hard to add the name of the field, because they are not in a static and it will be the name we registered in the DB, so, some of those would have no sens maybe for the user, or won't be adapted for him.
Also, there is a sentence for fields in error (look at the screenshot), I'm not sure that can be very understandable for the user (do you figure out for which field is it ? ;) ). And the sentence isn't very adapted I think. Do you want to keep it ?

![image](https://user-images.githubusercontent.com/48033264/125433494-f4f28ed2-0661-4a51-be2a-b1d9153ef546.png)
Answer : that's for the language version.
