### ISSUE TITLE
MF - Open discussion email is broken

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6210]
Template ID: `d-e902521de8684c57bbfa633bad88567a`
This template has been broken with our 2 last changes:
- [x] `userSubject` is not working in this email (it should replace the investor variable)
- [x] `org.denomination` neither
- [x] `from` used to be a number but now it's our email address so we should change the name of that variable in the template (I would say `min` `max` instead of `from` `to`)

Current result of my test:
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/6c204b3a-e852-4ccc-abc9-21c28d956957)

**Comment by Mussuranae** [comment]
This one isn't handle by our backend functions.... Maybe we have to change that ?

**Comment by Jackseed** [comment]
Oh ok got it... how complex would it be to handle it with our backend functions? 
Cause I may still rollback the email template to previous version that doesn't use org and user objects. The only remaining issue would be the `from` that is automatically send with our emails so we would need to change it anyway.

**Comment by phpgeekfr** [comment]
- [ ] add 2E2 test on this

**Comment by Mussuranae** [comment]
@Jackseed this email is now updated. I also update the template for the `from` and `to` to a little object `scope: { from, to }` so that we have no problem to display the value of the form.
It would be good to have a discussion with @phpgeekfr about this email, it looks like it is a little different from the others emails we have and its purpose was a little different. So when you came back from Cannes, maybe we can organize a call together.
I will now work on an e2e test for this.

**Comment by Jackseed** [comment]
Ok good! what's different from the others? with pleasure to discuss that next week. 

Also what do you think of integrating other emails to backend functions like the new offer email (`Template ID: d-94a20b20085842f68fb2d64fe325638a`) and mb other I miss?

**Comment by Mussuranae** [comment]
It can be nice, let's see next week ;)
