### ISSUE TITLE
Event invitation/request status 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6212]
Accept & decline buttons are being changed but we shall change the invitation (or request) status as well. 
Current problem:
- not pretty
- users click it
- text is not explicit enough

@maltmayer could you propose the text? It's about the current "Accepted" | "Declined" | "Pending"
Could be a sentence or more words at least. 

@jdrns already has some proposition re UI

**Comment by jdrns** [comment]
Suggestions of improvement UX (need to check with @2amarkina and with dev) 
- [ ] Add a tooltip on status pending explaining that they just have to wait 
- [ ] Add button when status declined (maybe "contact seller")
- [ ] Add button when screening is finished (maybe "contact seller", or "next screenings" taking to screening page)

Suggestions of improvement UI
- [ ] Remove the primary colour on the status (will reduce its affordance in order to discourage users to click on it) 
- [ ] Replace with a foreground 700, a less contrasted colour as the status is a secondary information (the rest is on white on a dark background so it will stand out more) 
- [ ] Add an icon on the right of status: establishment of design rules summarised [here on notion](https://www.notion.so/cascade8/Buttons-WIP-b7723d605f084a4ba73f63ab0fb94ac0) about where to put icons (left or right of label)

All the different states of screen are [on zeplin](https://zpl.io/2Gqmdw4)

Preview 
![image](https://user-images.githubusercontent.com/79836137/125956687-9f4f0768-07c5-4b8d-80f8-ef69d6bd5d8e.png)
![image](https://user-images.githubusercontent.com/79836137/125956780-895c922a-1b97-4fe0-8925-ad0168ff5618.png)

**Comment by Jackseed** [comment]
All good for me, except small thing, I would go for "Pending Invitation" instead of just "Pending". 

Since it's really the core of screenings, I would prefer @maltmayer to confirm as well before validating business

**Comment by maltmayer** [comment]
> All good for me, except small thing, I would go for "Pending Invitation" instead of just "Pending".
Shouldn't it be "Pending Request" here? As the pending invitation is when they have to Accept or Decline.

Otherwise everything looks good to me. I just have a comment on the Accepted icon. Should it be circled to stay consistent with the other pages?

**Comment by Jackseed** [comment]
yep you're right, "Pending Request"

**Comment by Jackseed** [comment]
@jdrns could you make these 2 tiny changes please? then it may go to dev review :)

**Comment by jdrns** [comment]
@Jackseed Updates have been made :)

**Comment by jdrns** [comment]
- [ ] Need testing to see if we can use dark foreground 700 in highlights banner

**Comment by Jackseed** [comment]
@RemcoSimonides this one is ok for devs as well

**Comment by RemcoSimonides** [comment]
So to understand correctly; the platform should be the same as all 7 different states in the design?
![image](https://user-images.githubusercontent.com/27687382/129905226-56ceee02-7269-42fb-b49c-a31c17de402f.png) I don't see all suggestions from [Jade's comment](https://github.com/blockframes/blockframes/issues/6212#issuecomment-881477205) in the design like a tooltip or a 'contact selller' button when declined.

I see the last Zeplin design includes the countdown component. That means this [issue](https://github.com/blockframes/blockframes/issues/6225) is also ready for dev?

**Comment by RemcoSimonides** [comment]
Dev issue created #6482
