### ISSUE TITLE
Jump from event to film pages

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#6223]
**_Priority: low_**

Design remark to check with UI, when switching from event page to the film page, there is an illusion of “jump” as not the same margins are used. 
Maybe introduce an animation to make it smoother? 
Maybe get rid of the margins? 

![margins2](https://user-images.githubusercontent.com/55499036/124596673-d7959d80-de62-11eb-80bc-d88f7f765a63.gif)

**Comment by Jackseed** [comment]
Good catch and UI question indeed, I remove the UX label

**Comment by stephanie-cascade8** [comment]
The problem seems to come from a forgotten css class. There should be a .mat-body-1 on the text description. (text size should be 16px and here it's more).

See the excepted result with the right font-size bellow (the text and buttons content on the right shouldn't be higher than the poster img). 

<img width="1093" alt="Capture d’écran 2021-08-11 à 19 05 09" src="https://user-images.githubusercontent.com/66258851/129072565-e278315b-7171-4963-962f-dedc5cf75302.png">

**Comment by cams-goussale** [comment]
@RemcoSimonides @2amarkina @dmoncadalv are you able to tell me if this is still a relevant issue? has it been fixed since last year?^^

**Comment by RemcoSimonides** [comment]
Did the structure of the event page change? Because the movie section is quite far down so it doesn't look as jumpy as it does in the gif. So I think this issue is not relevant anymore
