### ISSUE TITLE
Improvement of "Thanks for joining" 

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#6224]
**_Priority: high_**

**It seems that users do not feel confident on the Join Us page.** 
Solution is to get rid of the current title's text and keep with a more explicit title: “We are checking your profile”. Need to observe in time if it would be easier.

**Comment by Jackseed** [comment]
For the record, current page:
![image](https://user-images.githubusercontent.com/14964443/124625680-4c2a0580-de7e-11eb-80bc-237e59f3542e.png)

@maltmayer could you propose new text here please? what we'd like to achieve:
- change the title so it's clear that we need to verify the profile before accessing the platform
- reduce the amount of sub text
- add an estimation on how long it will take for us to approve the org (and btw do you have one?)


Regarding other challenges that we discussed I think we still need to find UX solutions:
1. users are blocked in this page and it's stressful (and sometimes buggy) so we want to give them a way to get back to landing
- currently once a user is connected s/he can't go to landing. We could change that but it works pretty well and will imply a lot of changes
- otherwise we could log out the user when s/he clicks on the logo and redirect to landing. But then user may be disoriented when trying to log in again and that we ask for her credentials again
> I would personally go for 2nd option with a warning when user clicks on the logo

2. Page should be refresh automatically without needing to click on the refresh button

3. Re-send verification email button is misleading as users can't know if they already did it or not. I think we'd better to:
- add a new icon meaning that action is needed to be done
- put that icon for both email validation & org approval
- replace "Refresh Page" with "Send validation email again" (or similar text)

**Comment by maltmayer** [comment]
That's perfect, I suggested this in the text inventory:

**Title:** Last step
**Subtext:** 
The *App Name* team will come back to you shortly.
Meanwhile, please verify your email to help us authenticate you. 

Feel free to contact us if you have any questions.

**Comment by Jackseed** [comment]
@maltmayer thanks (and I should have looked to text inventory first..). Would you have an estimation of our validation time as well? 
It's a good practice so users know if they should wait here or not

**Comment by maltmayer** [comment]
It can vary between 5min and a few days. Sometimes we miss some soo it can be even more. It would actually be nice to have reminders for those we miss. Maybe have a pending status and an "ignore" (we don't answer the request but it's voluntary)

**Comment by Jackseed** [comment]
Ok then what about something like
The ((App Name)) team will come back to you within 48h business hours.

?

**Comment by Jackseed** [comment]
It looks like we gonna need to have 2 different sub-text: 1 for `festival` and another for other apps. 

What about:
festival: `The ((App Name)) team will come back to you within less than 15 minutes during an open screening session, 48h business hours otherwise.`
others: `The ((App Name)) team will come back to you within 48h business hours.`

Feel free to change that I'm not fully satisfied ^^

**Comment by 2amarkina** [comment]
Wireframes for that part: 

**1. Festival** 
![Снимок экрана 2021-07-23 в 14.13.36.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/201c9ecb-4ed0-401d-9b70-3db20ddc0032)

**2. Usual**
![Снимок экрана 2021-07-23 в 14.13.26.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/ef7084a0-9963-4fab-8a0d-e0eed0390979)

**Comment by Jackseed** [comment]
thanks @2amarkina, last thing regarding the comment below; what do you think we should do?

> 1. users are blocked in this page and it's stressful (and sometimes buggy) so we want to give them a way to get back to landing
> 
> * currently once a user is connected s/he can't go to landing. We could change that but it works pretty well and will imply a lot of changes
> * otherwise we could log out the user when s/he clicks on the logo and redirect to landing. But then user may be disoriented when trying to log in again and that we ask for her credentials again
>   -> I would personally go for 2nd option with a warning when user clicks on the logo

**Comment by 2amarkina** [comment]
Ok for me to click on the logo and redirect to landing. Still, i think that warning is important. Here is the proposition. ![Снимок экрана 2021-07-23 в 15.48.53.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/ed600795-23b8-4b33-9ea8-bcc2fc8f4967)

**Comment by jdrns** [comment]
Regarding this issue, I think it requires some more thinking from a UI perspective, from the analytics we saw many users being confused by the "resend email" icon, potentially for: 
- its colour being the same as a "success colour" because it is used when a step is validated 
- for the fact that it is in the same column as the "status" of each step

**Comment by Jackseed** [comment]
business review: all good for UX, need a UI work on it for icons and then ready for devs

**Comment by 2amarkina** [comment]
Updated wireframes: 

**1. Festival**
![festival.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/f6da19f5-0caa-42d7-9794-65b60813d028)

**2. Other apps**
 ![normal.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/a4f84c22-02a3-4590-9774-7600a30cf55a)

**Comment by jdrns** [comment]
[Mock ups](https://zpl.io/ag1qWdN) are ready for business review 
- [ ] Check tooltip text for task status
- [ ] Check text for modal 

Preview 
### All apps
<img width="1085" alt="Screenshot 2021-08-20 at 14 38 04" src="https://user-images.githubusercontent.com/79836137/130234291-ded12139-571b-44b2-95fc-f2ccc2f312f2.png">

### Market
<img width="1062" alt="Screenshot 2021-08-20 at 14 39 28" src="https://user-images.githubusercontent.com/79836137/130234662-38deffda-7f43-4cf7-95a5-ad3a4ced02ab.png">

### Tooltips
<img width="1060" alt="Screenshot 2021-08-20 at 14 39 23" src="https://user-images.githubusercontent.com/79836137/130234677-ae31517f-5fcf-41df-abe9-21a7e36983ba.png">
<img width="1059" alt="Screenshot 2021-08-20 at 14 39 18" src="https://user-images.githubusercontent.com/79836137/130234700-07f25ac3-e8f3-4b6f-baaf-c644cf0bd6cb.png">
<img width="1080" alt="Screenshot 2021-08-20 at 14 39 13" src="https://user-images.githubusercontent.com/79836137/130234710-9ff52b6e-0f75-43b6-9417-23fcf0351f07.png">

### Modal
<img width="1064" alt="Screenshot 2021-08-20 at 14 45 51" src="https://user-images.githubusercontent.com/79836137/130235179-515c2d17-b4d4-4a46-b9ec-14889f7763ac.png">

**Comment by Jackseed** [comment]
@RemcoSimonides re this one, a slight change to precise to devs on top of mockups is that the subtitle text ("The [App name] team will come back to you within 48 hours."); 48 business hours and 15 minutes should be bold
