### ISSUE TITLE
Firestore Rules - Incomes Bug

### ISSUE THREAD

**Issue by pldespaigne** [blockframes/blockframes#6357]
When querying a single income like that, everything works fine.

```TypeScript
const ref = db.collection('incomes').doc(incomeId); // OK
```

But when you query multiple income like this, we get a permission error.

```TypeScript
const ref = db.collection('incomes').where('offerId', '==', offerId); // Permission denied
```

After some quick investigation the data seems to be ok, and the problem seems to come from this line in the `firestore.rules`

```
match /incomes/{incomeId} {
   allow read: if userOrgId() in getContract(incomeId).stakeholders // <-- this line seems to cause the bug (line 372)
```

**Comment by phpgeekfr** [comment]
@pldespaigne Yes, rules are not filters, so your query must reflect the rules when you query multiple rows.

So your initial query must contain all condition required in rules.

With 
```
const ref = db.collection('incomes').where('offerId', '==', offerId); 
```

when evaluating rules, google does not know if userOrgId is in  `getContract(incomeId).stakeholders` .

Since the rule is calling another collection you cannot do something like this to match the rules..:

```
const ref = db.collection('incomes').where('stakeholders', 'array_contains', orgId).where('offerId', '==', offerId); 
```

So my first guess is that you need to fetch contracts where `'stakeholders', 'array_contains', orgId` and then fetch income rows by their Id (not using `where` you will encounter same issue but with akita `getValue`)

**Comment by pldespaigne** [comment]
Indeed it was not a rule problem, but a query problem
