### ISSUE TITLE
filter-by-date pipe issue

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#6422]
`libs/utils/src/lib/pipes/filter-by-date.pipe.ts`

The pipe used in invitation list have some bugs:
```
<ng-container *ngIf="(invitations | filterByDate: timeFrame) as invitationList">
```

On july 07/29, if invitation date is :
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/b405ea14-1c3d-40aa-83e2-40dfd19eaba3)

It will be displayed.

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/43f3bf46-6192-4e12-a74f-73fc4641ab22)

If I change date for :
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/422ba2ce-dd94-4878-a9f4-23ffd566a3d8)

I get : ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/0bd2df41-8ded-4809-bb44-8eba16547dfe)

Looks like the pipe have some issue with "last week"

**Comment by Mussuranae** [comment]
For the pipe, there is several issue. On today, July 29th, the `Last Week`  begins in fact on July 21st and last until the July 15th. The July 22nd is a "ghost day", that means it is not take into account at all. I found a fix for this bug, but a big improvement could be appreciable.
We actually look for the "sliding" week instead of the "calendar" week (not sure for the wording sorry). So the week is defined by the actual day and it is not from Sunday to Saturday.
example : for today (July 29th) my last week is from July 21t to July 15th.
But with a calendar week, it would be from July 24th to July 18th. And only the day from today to 25th would be displayed like `Saturday, Friday` etc...

I hope it's understandable.
![image](https://user-images.githubusercontent.com/48033264/127493686-17937381-b689-40c3-8474-c0ea3f02a484.png)
