### ISSUE TITLE
[Release Test] Contract: creation, email, excel import

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6554]
Tester: @iPR0D1G1
Debugger: @pldespaigne 

To test
Avails filter
Add to selection button
Cards on selection page
World map view
Calendar view
Connected as an admin, import of contracts.

Let me know what you've tested for this so I can write those test scenarios in this issue next release

**Comment by iPR0D1G1** [comment]
To test
Avails filter
Add to selection button
Cards on selection page
World map view
Calendar view
Related to: #6553
To avoid merge conflicts, below are only those specific to this tests.

# [Page Avails -> Preselected Rights](https://staging.archipelcontent.com/c/o/marketplace/title/NnhsksCPbqMRzux0hPiT/avails/map)

[] Territories dialog
Doesn't show the list of additional territories.
<img width="1440" alt="Bildschirmfoto 2021-09-01 um 10 25 30 AM" src="https://user-images.githubusercontent.com/22674720/131658257-0de3ba01-d066-4308-bcba-646ac24ab990.png">

**Comment by iPR0D1G1** [comment]
# [Imports page -> Contracts]
(https://staging.archipelcontent.com/c/o/dashboard/import)

- [ ] Importing contracts as admin provides wrong information.
Using the attached template.
[e2e contracts Kopie.xlsx](https://github.com/blockframes/blockframes/files/7090761/e2e.contracts.Kopie.xlsx)

As indicated in the image, it says there was an error.
<img width="1438" alt="Bildschirmfoto 2021-09-01 um 12 31 01 PM" src="https://user-images.githubusercontent.com/22674720/131666295-9b5a33ac-a4c9-45ca-a8fc-0b63e1f30a08.png">

Listing contracts actually indicates there are no contracts.
<img width="1438" alt="Bildschirmfoto 2021-09-01 um 12 50 12 PM" src="https://user-images.githubusercontent.com/22674720/131666426-8072fb60-9bb2-427a-b0ab-db36b2a6bfd2.png">

**Comment by Jackseed** [comment]
url https://staging.archipelcontent.com/c/o/dashboard/contracts/co-517861/efuTTLhCrf7GlQwYqIgZ
user: dev+caesar-val@blockframes.io
- [ ] Contract header loading indefinitely due to permission issue
![image](https://user-images.githubusercontent.com/14964443/131814039-dac1f936-87e7-4941-9e11-64bf02a33b5e.png)

**Comment by Jackseed** [comment]
- [ ] Contract view - holdbacks: remove "Versions" column
![image](https://user-images.githubusercontent.com/14964443/131822250-45f07a15-f263-4811-a1dd-d7a213434f92.png)

**Comment by Jackseed** [comment]
- [ ] It looks like there is no rules to protect dashboard contract view, I was able to [access a contract `FleRh9KYRetDbgEdJVsR`](https://staging.archipelcontent.com/c/o/dashboard/contracts/co-800577/FleRh9KYRetDbgEdJVsR) with orgId `ySt7UnrX3zaRUrwPeJTw` (user dev+karolann-xqr@blockframes.io) even though this org is not a stakeholder of this contract nor offer

**Comment by Jackseed** [comment]
- [ ] Empty offer list, CTA should be accent color
![image](https://user-images.githubusercontent.com/14964443/131824552-3bac4e59-1caf-47d9-a18d-5852e5a25ae2.png)

**Comment by Jackseed** [comment]
- [ ] CRM contract view (`/c/o/dashboard/crm/offer/offerId/contractId`): add a snackbar when click on "Update" button with text "Contract updated."
![image](https://user-images.githubusercontent.com/14964443/131825478-3434fce2-7a2c-47a8-a482-cc8a4a7742c3.png)

**Comment by Jackseed** [comment]
- [ ] Dashboard contract list, change empty state to be different than the empty state used in marketplace. 
Instead it should be:
Title: "You have no offer yet." (without s to contract)
Text: "You will be notified as soon as a buyer makes an offer on your titles."
![image](https://user-images.githubusercontent.com/14964443/131839432-899d2fa3-3577-4ec8-9143-f949c112dfb8.png)

**Comment by Jackseed** [comment]
> # [Imports page -> Contracts](https://staging.archipelcontent.com/c/o/dashboard/import)
> * [ ]  Importing contracts as admin provides wrong information.
>   Using the attached template.
>   [e2e contracts Kopie.xlsx](https://github.com/blockframes/blockframes/files/7090761/e2e.contracts.Kopie.xlsx)
> 
> As indicated in the image, it says there was an error.
> <img alt="Bildschirmfoto 2021-09-01 um 12 31 01 PM" width="1438" src="https://user-images.githubusercontent.com/22674720/131666295-9b5a33ac-a4c9-45ca-a8fc-0b63e1f30a08.png">
> 
> Listing contracts actually indicates there are no contracts.
> <img alt="Bildschirmfoto 2021-09-01 um 12 50 12 PM" width="1438" src="https://user-images.githubusercontent.com/22674720/131666426-8072fb60-9bb2-427a-b0ab-db36b2a6bfd2.png">

I tested it as well and it worked for me with fresh titles. Contracts created through import are not listed in the contract list because you have to add the org name as Stakeholder within the excel import. 
Did it with these files:
[import contract test sept 21.xlsx](https://github.com/blockframes/blockframes/files/7098849/import.contract.test.sept.21.xlsx)
[import titles test sept 21.xlsx](https://github.com/blockframes/blockframes/files/7098850/import.titles.test.sept.21.xlsx)

**Comment by Jackseed** [comment]
user dev+foster-fdn@blockframes.io
url https://staging.archipelcontent.com/c/o/dashboard/title
- [ ] Dashboard title list, column Sales (Gross receipts) didn't update with a new contract being accepted. 

![image](https://user-images.githubusercontent.com/14964443/131886354-fd46e5d1-68a9-4720-9138-c4703ba74d74.png)
![image](https://user-images.githubusercontent.com/14964443/131886379-64c94f62-0eb5-4ae1-bfed-04cb8056644a.png)

**Comment by pldespaigne** [comment]
@Jackseed
> - [ ] It looks like there is no rules to protect dashboard contract view, I was able to access a contract FleRh9KYRetDbgEdJVsR with orgId ySt7UnrX3zaRUrwPeJTw (user dev+karolann-xqr@blockframes.io) even though this org is not a stakeholder of this contract nor offer

That's normal, anyone should be able to read contracts in order to see what is available or sold in the avails search. In contrast `offers` and `incomes` are indeed private.
It's not possible to change that with the current data model.

A user should not be able to access the dashboard contract view of a someone else's contract without a direct url.
And in any case even with direct url the user will not be able to modify it.

`firestore.rules` line 361
```
allow update: if (userOrgId() in existingData().stakeholders)
                    && isOnlyChangingContractStatus()
                    && notInMaintenance();
```

We could however put a guard to prevent user to see the dashboard contract view, but that would not be a real security.

**Comment by Jackseed** [comment]
Ok @pldespaigne then I would opt for a guard. I understand that this is public info but could give a really bad opinion if someone randomly ran into a contract view that is not theirs. 
@GrandSchtroumpf could you confirm a guard is ok there? If that's too much for that release we can wait for next one
