### ISSUE TITLE
do we need to allow user to remove their account for GDPR ?

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#6574]
Question asked by @RemcoSimonides in https://github.com/blockframes/blockframes/issues/6528

**Comment by RemcoSimonides** [comment]
Searching around a bit about this. Companies should give the ability to delete a users' data. Contacting us and ask us to delete their data is valid. But easiest for the user is of course to have a button on profile page or something themselves...
@Jackseed what do you think?

**Comment by Jackseed** [comment]
Since being able to delete on request is enough we are in line with GDPR and it's only a question of feature prioritisation.
So far we've chosen not to allow user or org deletion from users since it would mean complex flows (what happen to related movies, invitations, deals,..) that will require efforts to handle. It looks too much since no one ever asked for that and we preferred to focus on features that would make the apps more useful.
