### ISSUE TITLE
Build avails on mobile

### ISSUE THREAD

**Issue by frenchyrules** [blockframes/blockframes#6627]
- [ ] Give each button it's own line
![image.png](https://images.zenhubusercontent.com/611a265d2ea95c7880c91192/b0adda7e-9eef-4d8b-b007-e16bac01cbf5)

**Comment by stephanie-cascade8** [comment]
UI: 3 days

**Comment by stephanie-cascade8** [comment]
Some Mockups [here](https://www.figma.com/file/4fLdSu3hkg0fzj2WWKu2j3/Title-Details?node-id=19%3A1146)

**Comment by stephanie-cascade8** [comment]
@cams-goussale During the last sprint review we decided to put this one on hold until we decide what to do with the avails on the calendar (single territory version). 
Let's first check that it actually works on mobile (for me it didn't). 
Then,  we need business to decide if we optimize it on mobile or just put a message saying it's available only on desktop.

(note: even if optimized for mobile, it will be hard to use since we need to drag inside the calendar to zoom on a cell, then drag again to select the start date but year and month will hardly be visible at this point).

I suggest that either we build it entirely for mobile (which would be UX/UI and dev time consuming of course), or we tell the user it's not available.

**Comment by stephanie-cascade8** [comment]
The first screen of this page (the movie header) will be done in this #7333

**Comment by RemcoSimonides** [comment]
Created dev issue for this #7975
