### ISSUE TITLE
add some space at the bottom on the modal to open images

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#6637]
created from https://github.com/blockframes/blockframes/issues/6527#issuecomment-912316725

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/95d06713-6d09-45ad-9ed5-fd6181d66caa)

right now it is `margin: 24px 24px 72px 24px;` but it looks like it is not a good practice.

**Comment by KevinDurand974** [comment]
With the new modal system, I've these modal like this :
![image](https://user-images.githubusercontent.com/89908055/165779846-ea67de10-04d2-4daa-a5d5-383fb13c1ac5.png)

Already in large style with some large padding: 72px (default)
So, If the issue was to add some space at the bottom, its already done. @cams-goussale 
For the cross, I think 18 is a bit small, the default one is good, i'm not taking the decision anyway.

PS: My viewport size is 1366 x 622 pixel on my working PC

**Comment by cams-goussale** [comment]
I know it's your last day but @stephanie-cascade8 could  you take a look at this last comment? :D and maybe @dmoncadalv as well

**Comment by stephanie-cascade8** [comment]
@KevinDurand974 @dmoncadalv let's have a call and find a solution together. When we go on staging we see the previous version. We need to analyse what's on your branch.

**Comment by KevinDurand974** [comment]
New version :
![image.png](https://images.zenhubusercontent.com/62286a6af2db6b665200f133/16c61494-bde0-4ffc-85bb-d36cf21c7277)
