### ISSUE TITLE
No email received by admin when requesting a demo

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6641]
- [x] Tried 3 times to request a demo but didn't get any email as admin. mb I'm checking wrong email address but it looks like email is not sent
- [x] remove unsubscibe link
- [x] add await in front

**Comment by phpgeekfr** [comment]
Email is sent, just tried on my local.
But what you could do @Poppe-A  is to remove the unsubscribe link : 
![image](https://user-images.githubusercontent.com/1194344/132650859-0597c37b-4f58-48b1-8d11-cf263821717a.png)

I suggest that you first take a look yourself to find out how (there are existing examples on the repo)

@Poppe-A in front, also add an await for `this.sendDemoRequest(information);`

@Jackseed you did not received it because of the bouncing emails

**Comment by Poppe-A** [comment]
#6650
