### ISSUE TITLE
Remove Sentry error "The password is invalid or the user does not have a password."

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6651]
This [error](https://sentry.io/organizations/cascade-8/issues/2251632603/?project=1540126&referrer=slack) spawns every time a user tries a wrong email address.
It's not a code error and it shouldn't be within Sentry logs

**Comment by phpgeekfr** [comment]
I ignored the issue in Sentry and this should not occur anymore since we now catch the error to display a custom snackbar error:
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/2aadf413-52c2-4b19-8977-cfe00c34e105)

Remaining errors are still here because some users still have old code in their browser cache
