### ISSUE TITLE
[Feat]: Add password reset email workflow E2E test for Financier App 

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#6721]
Add tests to check password reset by email scenario. 

To start with we will use the Financier App and then introduce this for other apps.

**Comment by Jackseed** [comment]
Should be ok to do it on only one app since it's a shared component (@RemcoSimonides?)

Basic test would be to use an existing account and:
1. Connect with it first to be sure account is valid
2. Log out
3. Go on login page
4. Click on reset password
5. Fill in email address 
6. Catch email
7. Click on email link
8. Fill in a new password and confirm
9. Login again with new password
10. Test is complete if you're redirected to homepage

**Comment by RemcoSimonides** [comment]
I confirm it's a shared component
