### ISSUE TITLE
Slate Presentation Placeholder Image

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6902]
We need a placeholder image that we can display for example in the events slider for homepage (#4731) 
This placeholder will be used for slate presentation screenings, meaning that a seller will mashup a few trailers of their new titles to come. 

Here are some ideas/symbols of what could be on this placeholder:
- something related to the company
- symbols of multiple films
- novelty
- short
- mashup
- trailers

**Comment by stephanie-cascade8** [comment]
Hey there ! I've read all your reco on ideas to illustrate but when trying (novelty, mashup, screenings, org..) I thought those concepts are too precise to illustrate for a placeholder. 
I think the idea of presentation might work better to show more of the general aspect of the object. 
plus it's better if we want to play on the "emptiness" criteria of the placeholder. Tell me what you think.
(I don't think light version would be used anywhere since where displaying this on highlight sections with dark backgrounds but I made it in case)

![slate-presentation](https://user-images.githubusercontent.com/66258851/151529103-376990dd-9c0c-4ad2-9c3d-798b74de4906.png)


![slate-presentation](https://user-images.githubusercontent.com/66258851/151528048-ee0fe6d2-b1d7-465d-95f2-db4aa050c773.png)
<img width="787" alt="Capture d’écran 2022-01-28 à 11 23 31" src="https://user-images.githubusercontent.com/66258851/151530508-311399b7-ff8a-4a67-9669-acd4234940a9.png">

**Comment by stephanie-cascade8** [comment]
Zip svg to download here (wait for business validation though)
[svg-to-download.zip](https://github.com/blockframes/blockframes/files/7957892/svg-to-download.zip)
