### ISSUE TITLE
Update fields / placeholders for filters

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#6987]
_Can go directly to dev_

### Cross-app filters
**Filter name: Country of Origin**
Label: Type and select Country
Placeholder:  Country of Origin 

**Filter name: Language & Versions**
Label: Enter Languages
Placeholder:  Language

**Filter name: Company's Nationality**
Change the _select_ by _select+input_ as we use for Country of Origin 
Label: Type and select Country
Placeholder:  Country 

### Archipel Content
**Filter name: Avails**
Field: Exclusivity
Case: only if filter was cleared
Label: Select exclusivity

### Media Financiers
**Filter name: Partner**
Label: Search for a Partner

**Comment by yspringfield** [comment]
location: https://staging.mediafinanciers.com/c/o/marketplace/title
In the partner dropdown, there's a typo ( additional s on partners) in the input placeholder text.
As can be seen in the image.
<img width="1106" alt="Bildschirmfoto 2022-02-16 um 12 53 00 PM" src="https://user-images.githubusercontent.com/22674720/154259972-bc15a547-8ca7-42b0-a68e-10dee52f1bfa.png">


Otherwise, everything looked good to me.
