### ISSUE TITLE
Improvement for Original version sentence

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#7152]
> ### MOVIE PAGE / Additional tab
> * [ ]  Original version should say "available" at the end. It should just be "French" not "French available"
>   ![image](https://user-images.githubusercontent.com/55785823/141800826-099747e6-2390-4ff6-ac7a-a077c6f975f3.png)

Marie suggested to remove 'Available' from this line, but that doesn't work when it's saying 'Unavailable' instead. @2amarkina What would you suggest we change it to, to make it easier to understand for the user.

**Comment by 2amarkina** [comment]
The best would be to say if the version is available, then show only language "French", if version is not available then show "not available". If it's not possible, then I would say let's keep it as it is for this release and let's see this issue during next sprint, because this part is used in many places (movie tunnel, dashboard, marketplace, avails section of Content). 

Also, for this thing I tried to do the tests, but when I wanted to check out the view of Available versions on Marketplace (Archipel Market, Title name: _Film with versions_, User: Lucas Stoltenberg) and got again the error with Producer and Distributor that blocks me to publish a title (And I didn't go to this section at all)
<img width="940" alt="Снимок экрана 2021-11-17 в 10 06 09" src="https://user-images.githubusercontent.com/55499036/142170876-d2226ae2-e683-4acf-8c14-d63c8a8ed36c.png">

**Comment by Jackseed** [comment]
I prioritize this issue as it will overlap with #7045 that should go to devs in a short time

**Comment by 2amarkina** [comment]
**Possible solution, that can be the quickest one:** 
Change the section's name from "Available versions" to "Versions". 

So, on the **Movie tunnel** we get this 
![Movie Tunnel.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/a52cc493-ec3a-4982-bbdd-91e91c3aa2db)

For the **Dashboard** we got this: 
_Available_
![Additional_Dashboard.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/ee79187e-471d-492e-8aa4-18c5d8d73d7c)
_Not available_
![Additional_Dashboard (1).png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/72dbfcc8-744e-47c8-977b-19a9b475c4d6)

For the **Marketplace** we got this
_Available_
![Additional_Marketplace.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/fc1cc4ae-795c-4781-ab4b-f614d7bbf6eb)

_Not available_
![Additional_Marketplace (1).png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/b1db378b-540a-442c-bb95-a2b83d7162c5)

**[Wireframes can be found here](https://www.figma.com/file/qwQUGSXRIJorTNWYMMpywr/Original-Version?node-id=24%3A11971)**

**Comment by 2amarkina** [comment]
see .pdf with many versions

**Comment by 2amarkina** [comment]
Should be already on the dev side in progress with[ this one ](https://app.zenhub.com/workspaces/dev---sanity-team-5f6b0067599064680cd2c617/issues/blockframes/blockframes/7045)
