### ISSUE TITLE
countRouteEvents for goBack button

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#7179]
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/be6cef75-479f-4590-8c22-8ff3c30fda16)

created from https://github.com/blockframes/blockframes/pull/7167#discussion_r752106738

**Comment by RemcoSimonides** [comment]
@GrandSchtroumpf `this.location.back()` only goes back 1 step in the history list. Since changing tabs, changes the url and thus adds to the history, it is stepping back in the tabs. To prevent this, we cound how many steps we have to go back in order to skip all the tab changes. How would you have solved this issue? Should we reworking how tabs work to not change the url but maybe add parameters to the url instead? like `movie/id#title`

For reference: it's about file `libs/movie/src/lib/movie/dashboard/shell/shell.component.ts` in PR https://github.com/blockframes/blockframes/pull/7124/files
