### ISSUE TITLE
replace ngx-mat-select-search with material autocomplete

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#719]

**Comment by Maxstgt** [comment]
@phpgeekfr I checked the possibility and come to the conclusion, that if we want to keep the style, we can use this lib https://github.com/malothnaresh/mat-select-autocomplete/blob/master/projects/select-autocomplete/src/lib/select-autocomplete.component.ts 
OR
if we want a regular search, we can delete mat-select and make just a classic input mat autocomplete pattern

**Comment by Maxstgt** [comment]
@phpgeekfr I don't see a neat way to implement the mat autocomplete component into a mat select component. There are some libs for that, but I guess this will miss the idea of this issue here, right?

**Comment by Maxstgt** [comment]
you can replace the ngx component with 
```      <mat-optgroup>
        <input autocomplete="off" placeholder="Search..." aria-label="Search" matInput [formControl]="genresFilterCtrl"
          autofocus>
      </mat-optgroup>``` 
but the problem is now that if you type something inside the search bar, and choose a genre, you overwrite the value in the parten form what you maybe selected without using the search bar.

**Comment by phpgeekfr** [comment]
OK thanks for the update.

**Comment by phpgeekfr** [comment]
So `ngx-mat-select-search` seems to be the better candidate for our usage so far?

**Comment by Maxstgt** [comment]
I don't know what the motivation was for this issue, but there is also a pending PR in the angular repo that wants to add the search functionality in the mat select component but it is pending since 2017. So I suggest, that we keep that if it makes no trouble and doesn't explode our bundle sizes. Or we change form mat select to mat chip for example and we can use autocompletion and delete this lib. Maybe ask Mathilde...

**Comment by phpgeekfr** [comment]
>  So I suggest, that we keep that if it makes no trouble and doesn't explode our bundle sizes.

Me too ;)

**Comment by Jackseed** [comment]
Discussion closed then
