### ISSUE TITLE
Add a search bar in the Screening list

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7195]
### Description

We have seen several users searching for a specific title in the screening list. We want to add a Search bar to make their search easier.

### What's new

- [ ] Search bar on Screening list page: c/o/marketplace/event
- [x] Remove Sales agent filter

**Comment by cams-goussale** [comment]
@2amarkina do you think this issue still makes sense? This was a behavior we noticed on yandex. Do you know if this pattern was repeated by several users or was it an isolate case?

**Comment by 2amarkina** [comment]
The behavior that was detected and described in the issue was reproduced by several users.  I will pay a special attention fo this part in the further researches. For the moment, the last people I saw were just scrolling down the screening list page (might be related to the fact that returning users already know that there is no search bar). 

To my mind the search bar would be still "nice to have", at first - to keep up with consistency of the pages,  secondly - users do not have to scroll a long list screenings (if ever) and could access the desired information quicker (without passing through each title)
