### ISSUE TITLE
[DISCUSSION] Drop Algolia

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#7216]
Currently we pay around 100€/month for Algolia for 1 page & around 10€/month for Firestore for all the apps.
Algolia is expensive mainly because of CI and testing.
Also it's of no used on Archipel Content because we cannot do the avails filtering on Algolia, so it's only really useful for Archipel Market's title page.

I think we can drop Algolia to : 
- Reduce price
- Reduce code complexity (expecially on devops side)

We would have to fetch all the titles locally and filter them on the frontend, which is what we already do for Archipel Content anyway.

**Comment by Jackseed** [comment]
If we filter client side, could we still perform filtering on larger amount of data (let say a thousand movies) without client crashing?

**Comment by GrandSchtroumpf** [comment]
yes, data memory should be fine.

**Comment by george43g** [comment]
just another comment to add:
- e2e testing is difficult due to algolia, there is no test mode and presents issues with various PR e2e tests interfering with eachother
- to mock a response from algolia is complex and the only way to solve this

see
read the last comment on this: https://discourse.algolia.com/t/mock-js-client-for-instantsearch-ui-intergration-testing/9751
```
Hi there,

We don't provide an official mock for algoliasearch. However it's pretty trivial to write a mock with jest, we are actually doing it for some internal projects.

If you are doing UI test it's a bit more complicated as you are not in a unit testing env.
But If you are using the new AlgoliaSearchJS client (v4 at the time of writing), you can simply override the http Requested by your own and return the data appropriate for your tests.
```

and also

```
if you just want the answer to your initial question: there is no specific command to create an index, just send records to the name of the new index and it will be automatically created, as documented here: Manage Indices | API Reference | Algolia Documentation 1
```
This was from another google page. This means we are presented with the same clash issues that we have with sharing storage among tests. Algolia makes some tests almost impossible to write or fix

**Comment by Jackseed** [comment]
Also, we were aiming to introduce a general navbar that would perform a search into multiple collections (movies, orgs, users at least). 
Would it be still an option with a custom search?
