### ISSUE TITLE
Buyer Preferences modal less aggressive

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#7326]

**Comment by stephanie-cascade8** [comment]
@2amarkina can you put the wireframe link here ? (there was no mockup for this issue)

**Comment by RemcoSimonides** [comment]
https://www.figma.com/file/vTxVOIxGEEvuldEa4kbzRE/%5B-Buyer's-preferences-%5D?node-id=15%3A1817

**Comment by stephanie-cascade8** [comment]
After meeting with Vincent, Camille and Anastasiia, we said keeping the modal is mandatory. We only can improve with quick css fixes. 

Let's reduce the modal's content width to 80% and have it centered inside the modal. 
Same for the paragraph (it's more balanced on two lines).
Replace h3 'rights" 'territories'... by p class="body-1". 

Here is the result : 
<img width="1081" alt="Capture d’écran 2021-12-07 à 20 30 21" src="https://user-images.githubusercontent.com/66258851/145094273-1d4abc6c-13e1-4c8e-b76e-d3aeaf19a881.png">

@Jackseed and @cams-goussale I think it's better like this. What do you say?
I wouldn't try an illustration there  (it would not make less agressive, on the contrary). 
Putting two fields side to side on one line is also not possible since the fields can have multiple selections.

**Comment by 2amarkina** [comment]
I think that we could use directly the field labels and not the titles (h), like in the example below
<img width="536" alt="Снимок экрана 2021-12-08 в 09 42 23" src="https://user-images.githubusercontent.com/55499036/145176713-4ba27f17-9dd3-4021-992c-a93d980943c7.png">

Like that we will gain more space. Also we could use exactly the same fields (with icons for the rights and territories) that would make the modal a bit more "fun".

**Comment by RemcoSimonides** [comment]
I could make the modal less wide instead of increasing padding on the side of the fields
Also, this is the result without the titles suggested by Ana
![image](https://user-images.githubusercontent.com/27687382/145179435-901b03f4-0a9c-464c-8770-9ee0e1103c96.png)

**Comment by Jackseed** [comment]
Ok looks way better! Indeed Ana is right, using the icons also would help make it more friendly. 
@maltmayer could you confirm the wording please? Also, I just thought about it but with Screen operation we have a lot of 'random' users that are in fact not buyers. 
@RemcoSimonides would it be possible to add one more filter before showing that to users depending on their org activity..?

**Comment by RemcoSimonides** [comment]
Sure, what would it be?

**Comment by maltmayer** [comment]
Title: What are you looking for?
Text: For a more personalized and curated experience on Archipel, we offer you to specify your content preferences. 
Fields:
- Rights
- Territories
- Languages
- Genres

**Comment by Jackseed** [comment]
> Sure, what would it be?

Marie doesn't think it's worth making a difference so nvm we'll keep it as it is 👍
