### ISSUE TITLE
Images not uploading

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7336]
## Your environement
- OS: Windows and Mac
- Browser (& version if possible): Chrome

### Localization
- App name: Festival
- Page: Movie tunnel/Promotional Elements
- Url: c/o/dashboard/tunnel/movie/[movieId]/media-videos
- User used (if anonymized): 38rjqqlz0hMlYKOugRv5hh4UyA73
- Sentry error that might help:
[Prod one](https://sentry.io/organizations/cascade-8/issues/2485237942/?environment=production&project=1540126&query=is%3Aunresolved) (from Marie, using Movie tunnel)
[Staging one](https://sentry.io/organizations/cascade-8/issues/2485237942/?environment=staging&project=1540126&query=is%3Aunresolved) (from me, using CRM)

### Context
Marie and I tried to upload 2 images on a title and we were not able to have it displayed. It only bugged with these 2 specific images.
![TTB_20201112_09340r (1)](https://user-images.githubusercontent.com/93206363/144636693-8564ed7e-f1a1-4876-9072-f03346185bbe.jpg)

![TTB_20201006_02579r (1)](https://user-images.githubusercontent.com/93206363/144636865-e03bcce2-ca15-4a8e-8b83-9f2d20766c74.jpg)

In staging, I tried to upload them on movie id ckdjrRuFoUaZbhLi6QGL
Here is the result sent to db
![image](https://user-images.githubusercontent.com/93206363/144637002-55565737-26d3-4924-ae05-70fca7a2cbab.png)

And here is what happened on Marketplace view
![image](https://user-images.githubusercontent.com/93206363/144637077-2e4f1a91-8d59-4cfa-b70e-7fb4d9ec497c.png)

**Comment by RemcoSimonides** [comment]
This issue is caused because of its file size after a needed conversion in the code. This conversion is done _after_ cropping, so it's already past the moment of initial selection of the file.

Most of the time, the size of the file is similar before and after the conversion but for some reason it isn't with these images. So this error is an exception.

I would suggest to show an error despite it feeling weird that you select a file of 3.3MB and get a warning when selection it saying that file size is too big even though it looks like below the max of 5MB.

We could either show it immediately when selecting the file (that would mean doing the conversion to test its size earlier and perhaps having bit worse performance), or because it only happens rarely, to show the warning after cropping the image. For this last solution we probably need to remove the file again so the user doesn't upload it accidently.

@2amarkina @cams-goussale  what do you think would be best?
