### ISSUE TITLE
Release 3.6 - Event

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#7349]
Issues fixed in this release so please double check
- #7160 (only the checked checkboxes)
- #7004
- #7169
- #6978

**Comment by 2amarkina** [comment]
OS: Mac BigSur, 11.6
Browser: 15.0

- [ ] Following this #6978, when I create a screening event and do not select a title to display, I can't see any chip that appear, nor any warning.

**Comment by 2amarkina** [comment]
**Events without connexion** 

Meeting Event Page 
- [ ] now when we connect with anonymous user (Public event) in our Meeting event page layout the logo of organization leads to the account creation page (when a user is connected it leads to the Organization page). So, wouldn't it be better to lead an anonymous user to the Landing page instead of account creation? @Jackseed @cams-goussale 
![Снимок экрана 2021-12-08 в 13.08.54.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/59d7fa0d-7a76-478c-b6fb-4d04b3e9ddda)

**Comment by Jackseed** [comment]
> **Events without connexion**
> 
> Meeting Event Page
> 
> * [ ]  now when we connect with anonymous user (Public event) in our Meeting event page layout the logo of organization leads to the account creation page (when a user is connected it leads to the Organization page). So, wouldn't it be better to lead an anonymous user to the Landing page instead of account creation? @Jackseed @cams-goussale
>   ![Снимок экрана 2021-12-08 в 13.08.54.png](https://camo.githubusercontent.com/9b1fcbace59976717c3d6bd95f59fa5955ec0f784e45b01a915681458867125f/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564643534353238633063636433303030313336373263332f35396437666130642d376137362d343738632d623666622d346430346233653964646461)

Indeed, if we can it would be better to lead to landing. And I would say even better not to be clickable at all for anonymous users but this I don't know if that's doable..

**Comment by cams-goussale** [comment]
- [ ] Invitations in /crm/event/[eventId] stopped showing

![image](https://user-images.githubusercontent.com/93206363/145211481-c0febecf-6c71-48ba-85ef-0da0b1efc611.png)

**Comment by 2amarkina** [comment]
**Events without connexion**

Protected meeting event / Guest side

- [ ] As a guest I received an email, clicked on it, filled in the little form and got access to the event page where I could answer an invitation. Tried to click on "accept invitation", but nothing happened. Same for decline. 
![protected meetning.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/0a576c06-d5d9-43e7-bfca-105749619467)

**Comment by RemcoSimonides** [comment]
> > **Events without connexion**
> > Meeting Event Page
> > 
> > * [ ]   now when we connect with anonymous user (Public event) in our Meeting event page layout the logo of organization leads to the account creation page (when a user is connected it leads to the Organization page). So, wouldn't it be better to lead an anonymous user to the Landing page instead of account creation? @Jackseed @cams-goussale
> >   ![Снимок экрана 2021-12-08 в 13.08.54.png](https://camo.githubusercontent.com/9b1fcbace59976717c3d6bd95f59fa5955ec0f784e45b01a915681458867125f/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564643534353238633063636433303030313336373263332f35396437666130642d376137362d343738632d623666622d346430346233653964646461)
> 
> Indeed, if we can it would be better to lead to landing. And I would say even better not to be clickable at all for anonymous users but this I don't know if that's doable..

Leading to landing page means logging out the user

**Comment by 2amarkina** [comment]
**Meeting Event with participants**

Seller 
- [ ] When sharing a video and access the full screen view, everything works well. But when want to exit the full screen mode, the icon for closing it does not work 

![Снимок экрана 2021-12-08 в 14.11.35.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/adfc093f-9516-4c30-8ba3-3aa9455f8157)

**Comment by stephanie-cascade8** [comment]
> OS: Mac BigSur, 11.6 Browser: Safari 15.0
> 
> **Screening Creation**
> 
> * [ ]  Following this [Event form - Add a chip to warn users there is no screener #6978](https://github.com/blockframes/blockframes/issues/6978), when I create a screening event and do not select a title to display, I can't see any chip that appear, nor any warning.
> 
> **Meeting creation** _Sorry if duplicate_
> 
> * [ ]  Need to add more space between "Add files" and Selected section (I would suggest to add about 20px, but better to check out with @stephanie-cascade8 )
>   ![Снимок экрана 2021-12-08 в 12.17.41.png](https://camo.githubusercontent.com/499e49863c93e100439e9b33b483fcef7aad0458b87df233580266c67b8d1db5/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564643534353238633063636433303030313336373263332f30663964333136342d633933612d343961612d626432332d666131323333303735343835)

We only use multiples of 4 for spacing. Here as the content nedds to be grouped together, let's add 16px not 24.

**Comment by 2amarkina** [comment]
**Invitations for events**

Seller
- [ ] When we click on "more details" of an invitation that was accepted (declined or if there is someone who requests access to event) it leads us to the Event Creation page with the Statistics tab directly. 
Was it something that was excepted? 
If we can choose a tab to show maybe it makes sense to lead it to Invitations tab in such case? Or do we want to cover the use case when a Seller clicks on "more details" after a screening was finished (but it has less sense i think)? @Jackseed @cams-goussale 

![invitations.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/dae4240d-22f5-48d2-af4d-4c3645629730)

**Comment by Jackseed** [comment]
> [x] When we click on "more details" of an invitation that was accepted (declined or if there is someone who requests access to event) it leads us to the Event Creation page with the Statistics tab directly.
> Was it something that was excepted?
> If we can choose a tab to show maybe it makes sense to lead it to Invitations tab in such case? Or do we want to cover the use case when a Seller clicks on "more details" after a screening was finished (but it has less sense i think)?

Ok, we saw with Ana that it's in fact the desired behaviour (if event is ongoing or finished it leads to stats). The weird thing is that if it's finished it still leads to the "edit" view whereas it should be the non editable view but this look too complex to handle and not really a problem

**Comment by cams-goussale** [comment]
**Review on Public / Protected Event**

1- To complete @2amarkina notes above:
>Protected meeting event / Guest side
As a guest I received an email, clicked on it, filled in the little form and got access to the event page where I could answer an invitation. Tried to click on "accept invitation", but nothing happened. Same for decline.

This happens when the Protected event is in the future and the guest in question already has an account.


2- Here also adding some content on @2amarkina review:
>Following this Event form - Add a chip to warn users there is no screener #6978, when I create a screening event and do not select a title to display, I can't see any chip that appear, nor any warning.

This issue was related to when the title selected in the Event form does not have a Screener.
It doesn't take into account cases where the organizer is not selecting a title at all.
Fix : could we add similar warnings when user saves the event and hasn't selected a movie?
- a chimp on top of the form "No title selected"
- a red warning below the Title selection "No title selected"


3- When there is a Protected event in the Screening list (c/o/marketplace/event), user who is not invited to the event can Ask for Invitation. But when entering the Event page, this action is not available anymore and it says "Invitation accepted".
Fix: could we keep the CTA "Ask for Invitation" in the Event page?
![image](https://user-images.githubusercontent.com/93206363/145246098-77e1f30f-8dbf-4adf-a6e4-15e58ccb3469.png)

![image](https://user-images.githubusercontent.com/93206363/145246114-e25236c4-a604-466f-82af-ce9b28cfa4f1.png)

**Comment by 2amarkina** [comment]
One more bug found: 

**Marketplace side / Public Event Page**
When trying to add a public screening to calendar, the button doesn't react 
![add to my calendar.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/904fd3d7-d95e-45f5-a7c0-8736597fe2bb)

**Comment by cams-goussale** [comment]
hello @phpgeekfr I have seen a random bug on Private events. Wondering if it's linked somehow to the "Email verification" that we withdrew?

I just created on staging a private meeting (id au2T05gQX3HDTVwQ8L4M) and I invited 5 users which have different cases:

1. cgoussale+meeting8@cascade8.com and cgoussale+meeting7@cascade8.com
-Users without Archipel account
-When invitation sent, their icons immediately changed to "blue" as if they had accepted already
-In email, I receive the structure 1- JOIN EVENT 2- ACTIVATE ACCOUNT ([template sendgrid](https://mc.sendgrid.com/dynamic-templates/d-5123a0ceda2d463db60717dc94005b65/version/9178f554-c088-4bc6-8320-6d062980b077/editor))
-Actually in this case, users should receive structure 1- ACTIVATE ACCOUNT 2- JOIN EVENT ([template sengrid](https://mc.sendgrid.com/dynamic-templates/d-ce3e57248a694cefacad49bc4c820078/version/e57ca86c-9e2d-46ff-8694-f6b12f624e17/editor))

2. cgoussale+meeting6@cascade8.com
-User without Archipel account but was previously invited to an event
-When invitation sent, its icons is immediately changed in "blue" as if he had accepted already
-In email, I receive the structure 1- JOIN EVENT 2- CAREFUL YOU DIDN4T ACTIVATE YOUR ACCOUNT
=> all good here

3. cgoussale+meeting9@cascade8.com
-User without Archipel account
-When invitation sent, its icons was in "grey" to show he hasn't accepted the event yet
-In email, I receive the correct structure 1- ACTIVATE ACCOUNT 2- JOIN EVENT
=> all good here

![image](https://user-images.githubusercontent.com/93206363/145389147-c53b2827-0dbe-44b0-b586-ce5baeb0573d.png)

**Comment by phpgeekfr** [comment]
> hello @phpgeekfr I have seen a random bug on Private events. Wondering if it's linked somehow to the "Email verification" that we withdrew?
> 
> I just created on staging a private meeting (id au2T05gQX3HDTVwQ8L4M) and I invited 5 users which have different cases:
> 
>     1. [cgoussale+meeting8@cascade8.com](mailto:cgoussale+meeting8@cascade8.com) and [cgoussale+meeting7@cascade8.com](mailto:cgoussale+meeting7@cascade8.com)
>        -Users without Archipel account
>        -When invitation sent, their icons immediately changed to "blue" as if they had accepted already
>        -In email, I receive the structure 1- JOIN EVENT 2- ACTIVATE ACCOUNT ([template sendgrid](https://mc.sendgrid.com/dynamic-templates/d-5123a0ceda2d463db60717dc94005b65/version/9178f554-c088-4bc6-8320-6d062980b077/editor))
>        -Actually in this case, users should receive structure 1- ACTIVATE ACCOUNT 2- JOIN EVENT ([template sengrid](https://mc.sendgrid.com/dynamic-templates/d-ce3e57248a694cefacad49bc4c820078/version/e57ca86c-9e2d-46ff-8694-f6b12f624e17/editor))
> 
>     2. [cgoussale+meeting6@cascade8.com](mailto:cgoussale+meeting6@cascade8.com)
>        -User without Archipel account but was previously invited to an event
>        -When invitation sent, its icons is immediately changed in "blue" as if he had accepted already
>        -In email, I receive the structure 1- JOIN EVENT 2- CAREFUL YOU DIDN4T ACTIVATE YOUR ACCOUNT
>        => all good here
> 
>     3. [cgoussale+meeting9@cascade8.com](mailto:cgoussale+meeting9@cascade8.com)
>        -User without Archipel account
>        -When invitation sent, its icons was in "grey" to show he hasn't accepted the event yet
>        -In email, I receive the correct structure 1- ACTIVATE ACCOUNT 2- JOIN EVENT
>        => all good here
> 
> 
> ![image](https://user-images.githubusercontent.com/93206363/145389147-c53b2827-0dbe-44b0-b586-ce5baeb0573d.png)

For the first point: 
`When invitation sent, their icons immediately changed to "blue" as if they had accepted already` That means that the event was not in the right privacy setting. I guess that you changed the privacy setting from `public` to `private` and sent the invitations without saving the form before sending the invitations.

@cams-goussale  can you confirm ?
If yes, this bug is already described in #7134 :  `On event edit page, invitations should be sent only after saving the event form `

I think you did the same for point 2, because invitation icons should not have been blue for private events.

For point 3, I guess that you saved the form before sending this invitation

**Comment by cams-goussale** [comment]
@phpgeekfr okok, yes you're 100% correct
I saved after sending invitations to users 6, 7, 8. And then I invited user 9.

**Comment by 2amarkina** [comment]
I've just retested this part and saved the event before. But still have "accept" and "decline" buttons and they are not clickable.

**Comment by phpgeekfr** [comment]
> Antoine : Can not reproduce. @phpgeekfr can you check ?
> 
> **Meeting Event with participants**
> 
> Seller
> 
>     * [ ]  When sharing a video and access the full screen view, everything works well. But when want to exit the full screen mode, the icon for closing it does not work. Same for the documents and for the participants view.
> 
> 
> ![Снимок экрана 2021-12-08 в 14.11.35.png](https://camo.githubusercontent.com/4b9700fc2a7d3c9c1545663f9cdc31bfde2c81c0ce7a43cc03b48b68448df26e/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564643534353238633063636433303030313336373263332f61646663303933662d393531362d346333302d386261332d336161393435356638313537)
> 
> ![Снимок экрана 2021-12-08 в 14.14.57.png](https://camo.githubusercontent.com/b078d0d856174be3f5ab516978b088e67691884bdfa6a872e684cd7db2140e92/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564643534353238633063636433303030313336373263332f61396462633634392d653735322d346232612d396438312d306437386330383662373761)

@Poppe-A I think this is referring to ` Safari: the full screen button once on full screen is not closing the full screen` in #7161

**Comment by RemcoSimonides** [comment]
If it's Safari ☝️ i'll fix it

**Comment by phpgeekfr** [comment]
> @phpgeekfr I've just retested this part and saved the event before. But still have "accept" and "decline" buttons and they are not clickable.

OK this is not the same issue as Camille described. When we invite an already existing account to a protected event, if the user is not connected and choose to login as anonymous, invitation is not already accepted and user cannot accept it since he is not logged. The solution would be to force user to login if we detect that the email belongs to an existing account but this might be complete to achieve.

**Comment by phpgeekfr** [comment]
- [ ] **BRUCE** If I invite an user to my org and then invite him to an event, he will receive 3 emails : 
- one for the org invitation (normal)
- one for the event invitation (normal)
- one for the event invitation when notification is triggered (not normal)

**Comment by phpgeekfr** [comment]
- [ ] if I invite a new user to an event and then invite the same user to my org, he will  receive invitation to event email but not the org one. @cams-goussale  I'm not sure this is a big issue, because user will receive his credentials in the event email, and if he decide to create an account, form will be filled with org data coming from invitation

**Comment by cams-goussale** [comment]
Yes it should be ok @phpgeekfr. It looks like an edge case which shouldn't block the release. I guess it's more natural to invite someone to join your org first and second to an event rather than the other way around. Maybe in the future we can think of the possibility to re-send invitations (events, joinOrg)

**Comment by phpgeekfr** [comment]
> When there is a Protected event in the Screening list (c/o/marketplace/event), user who is not invited to the event can Ask for Invitation. But when entering the Event page, this action is not available anymore and it says "Invitation accepted".
Fix: could we keep the CTA "Ask for Invitation" in the Event page?

@cams-goussale 
I fixed the button "ask for invitation" not showing but I did not see the "Invitation accepted" sentence.

**Comment by cams-goussale** [comment]
- [ ] When entering a public Screening page, the logo and the back arrow don't work anymore (url is **/event/[eventId]/r/i**)
