### ISSUE TITLE
Buying preferences in CRM

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7425]
We need to be able to extract the buying preferences data. Ideally we should add the 4 columns to user list in the crm and add these same columns to the csv export.

_Originally posted by @RemcoSimonides in https://github.com/blockframes/blockframes/issues/7345#issuecomment-988704663_

**Comment by RemcoSimonides** [comment]
Hee @cams-goussale, adding the buying preferences to the users list doesn't work with the UI because there can be many values in it. This UI issue could be improved if we cut the sentence after a certain amount of characters, but still it won't look nice if you filter on a value but you don't see it in the field (e.g. filter on 'French' but then only thing you see it "Arabic, African, Albanian ...")

I can add it to the csv export because there the UI doesn't break

**Comment by cams-goussale** [comment]
@RemcoSimonides no problem if it's not on the user list. Can you confirm it will be on the user/[userId] page?
Indeed, let's add it to the csv export, which will be the most important view.

**Comment by RemcoSimonides** [comment]
No, I can't confirm that. But if you want me to add it there, I can do it. Just outputting all values there can be too much though. Would you like me to make it clickable and see all the details in a modal if there are too many values? Or do you think not many users will have too many values and thus it's ok if everything is displayed.

**Comment by cams-goussale** [comment]
Lets go for the clickable data + modale
