### ISSUE TITLE
Optimize the text when event is deleted

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#7538]
Start from: https://github.com/blockframes/blockframes/pull/8070

Propose the text that helps users to easily understand that the invitations that have been already sent can't be deleted and the invitation link integrated wouldn't work.

**Comment by cams-goussale** [comment]
@maltmayer can you give us a text proposal so we can push this in the release next weeK?

**Comment by maltmayer** [comment]
Can you give some context please? I don't understand the situation here

**Comment by 2amarkina** [comment]
It's about this modal 
<img width="987" alt="Снимок экрана 2022-01-17 в 16 48 02" src="https://user-images.githubusercontent.com/55499036/149800785-cbe5193c-be1c-40fb-9447-efc5be070c8c.png">

We need to prevent users that even if they delete this event, the invitations that have been sent will always exist and the guests risk to come to a screening that doesn't exist anymore.

**Comment by 2amarkina** [comment]
No problem, that is exactly the problem with the present text. 

The invitations will still exist, if they were sent, as we can't delete the invitations form the user's mail box

**Comment by 2amarkina** [comment]
- [ ] validate the text with Marie 
- [ ] check in text inventory

**Comment by cams-goussale** [comment]
hey @maltmayer sorry we threw you in the issue without much context.

Currently if you create an event, send your invitations, it will send emails to your invitees. If for any reason you decide to delete the event afterwards, you will see the modale above 👆 with the following text:

`All the invitations and requests associated to it will be deleted.`

This is not really true. If the email invitation has been sent, we can't take it back from user's email box. So we should change the text to a warning sentence like "watch out, if you've already sent out invitations, we can't delete them"

This issue has been raised because @2amarkina spotted a user from Pulsar who deleted a screening **after** having sent some invitations.

**Comment by maltmayer** [comment]
Ok I get it. I have 2 questions still:
- Will the invited user be able to see the invitation in his invitation page?
- What will the page look like if the invited user clicks the event link in his invitation email? 

In any case I would write something like:
"Are you sure you want to delete this event?
Invitations cannot be taken back, your guests might get confused..."

Thinking about it, I'm thinking that it's not a good way to put things... They should be able to cancel an event easily. Here we're nearly saying "hey it's a bad idea what you're doing"
To me, this raises the following issue: ideally, this should send out an automated notification email to the invited guests saying "(Org Name) just canceled their event (Event Name)". Or suggest something to the seller saying: "Here is the list, you might want to contact them to let them know this event won't be happening/invite them to a future screening".

**Comment by cams-goussale** [comment]
> Will the invited user be able to see the invitation in his invitation page?

No, it disappears after organizer deleted the event.

> What will the page look like if the invited user clicks the event link in his invitation email?

It actually redirects to AM homepage (because the event id has been deleted, so the url doesnt exist anymore)

An automatic email sent to invitees when the organizer deletes the event sounds like a good solution to me but might take a bit of time to be implemented. So in the meantime, I suggest we update the text of the modale:

`If you've already sent invitations, please note they can't be deleted. Contact them to let them know this event won't be happening.` (Marie please review the wording:)))
+table with invited emails

**Comment by maltmayer** [comment]
`If you've already sent out invitations, please note that the invitation emails cannot be taken back as they were already sent. You might want to contact the people concerned to let them know this event won't be happening.`

**Comment by 2amarkina** [comment]
![Снимок экрана 2022-01-21 в 16.11.21.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/7548a80e-e8fc-41b3-ad6c-0f3b05c58775)

**Comment by 2amarkina** [comment]
Ready to be implemented

**Comment by phpgeekfr** [comment]
Right now, only one `<p>` tag is allowed but we can add another one quite easily in the generic confirmComponent we use for popins like this.
But putting a part of a sentence in strong is more complicated and require a bigger refactoring. @2amarkina can we do without the bold text ?
