### ISSUE TITLE
Release 3.7 - Profile/Users

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#7557]
Issues fixed in this release so please double check
CRM:
- https://github.com/blockframes/blockframes/issues/7425

**Comment by 2amarkina** [comment]
Following the space issue inside Buyer Preferences Modal quoted [here ](https://app.zenhub.com/workspaces/design---ux-60ab5f37bd1f990011c933a2/issues/blockframes/blockframes/7556)

Need to do the same work with Buyer Preferences on the Profile level 


- [ ] Put the same space between all the fields 
cc: @stephanie-cascade8 
![Снимок экрана 2022-01-20 в 13.09.56.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/a945e3f6-f358-4887-b23e-4d431c040685)

**Comment by cams-goussale** [comment]
- [ ] Buyer Preferences should show all the time on the Profile level. Currently it shows only to some users, but not all.
(I couldn't find 2 examples on staging, so one is prod, and another one is staging)

![image](https://user-images.githubusercontent.com/93206363/150336582-ccabfb3a-c7eb-489b-9178-af968e43e56e.png)

![image](https://user-images.githubusercontent.com/93206363/150336565-fd6d088f-3f46-47c4-a0ec-3dfd4a95ad72.png)

- [ ] Do buying preferences create tags in Mailchimp? We saw a video in metrika of a user saving some preferences. And all his preferences were Tagged in Mailchimp. However, when clicking on the Tag report, it's empty.

![image](https://user-images.githubusercontent.com/93206363/150336795-c34cde40-b0b5-4c34-810e-2a2e9ce16aee.png)

- [ ] There seem to be some bugs in firebase to save these preferences. I am still trying to specify this bug. But the user we saw in Metrika was not saved in the db.

**Comment by cams-goussale** [comment]
This is the user video i mentioned above:
https://drive.google.com/drive/folders/17HsPbeCIZAT88E4y3kzeQOaKVBqYGjeX?ths=true

user id oul9cjKkMgODyEisS9HvhzKM46d2

**Comment by 2amarkina** [comment]
@Jackseed @cams-goussale As we are going to get rid of the members' roles (see [the issue here](https://app.zenhub.com/workspaces/design---ui-60ab5f96c64ec50014c46754/issues/blockframes/blockframes/6753)) maybe we could already do something for these release ?

- [ ] delete the text "grant permissions" 
- [ ] remove the "grant permissions" from the dropdown 
- [ ] change the UID column to Actions

![Снимок экрана 2022-01-20 в 16.16.47.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/a65f9d95-3979-4f2f-bf35-b36274d2864a)

![Снимок экрана 2022-01-20 в 16.21.24.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/0000b837-cb5f-4104-af41-5a2759340dfe)

**Comment by Jackseed** [comment]
I would prefer wait for doing this properly and all at once

**Comment by RemcoSimonides** [comment]
What is a tag report? You should be able to see the users' tags when you go to their page
![image](https://user-images.githubusercontent.com/27687382/150992494-01f39ac3-576a-4a8d-8a05-ad438f63a407.png)

Also, I have not been able to reproduce the bug of the buying preferences not being saved in the database. Maybe this user removed them again via Profile > Buying Preferences? There are other users who have their buying preferences saved in the db.

I have however noticed a different bug; the tags aren't added to the user if the user doesn't exist in mailchimp yet. Maybe this wasn't an issue on production because all users are added automatically to mailchimp. However, for it to be more reliable this issue should be done https://github.com/blockframes/blockframes/issues/7297

**Comment by cams-goussale** [comment]
Oh okok i see! Tag report is in mailchimp > Audience > tags > Tag report. But I probably opened the wrong report, because i just checked other tag and it had some data indeed.

Ok about the related issue, I will see if we can push it a bit in the backlog.

It looks like this is good to close. There is this unidentified user case who doesn't have its preferences saved, but there is not much we can do if we don't specify the bug.
