### ISSUE TITLE
Release 3.7 - Deal Negotation

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#7558]
Issues fixed in this release so please double check
- https://github.com/blockframes/blockframes/issues/7446
- https://github.com/blockframes/blockframes/issues/7482
- https://github.com/blockframes/blockframes/issues/7119
- https://github.com/blockframes/blockframes/issues/7389

**Comment by 2amarkina** [comment]
**OS:** MacOS (BigSur)
**Browser:** Safari, 15.0 / Chrome 97.0.4692.71

### Marketplace
- [ ] On the Homepage we can see a lot of titles, but when connecting to the Library we've got a message "Sorry, we didn't find anything." (same when using menu burger and CTA Library)
[Library](https://drive.google.com/file/d/13KHBxc7t5NRE6qIUSaTf1hbi0KTejYnd/view), [Library 2](https://drive.google.com/file/d/1FLmk52gGA46iTzOCL81DiqanjmZDFO2-/view)

_N.B. Putting the links to drive for the videos as my tool to make gifs doesn't work properly anymore_

- [ ] On the Offers and Deals page the table stops showing the content after we switch the tabs
[table tabs bug](https://drive.google.com/file/d/1roBQ3y1PJixi1ww1lWOLkJYhAZDUFYtj/view)

- [ ] Same for the filters. After entering the information that can't be filtered, and after cleaning it up, the content doesn't reappear
[table filter bug](https://drive.google.com/file/d/1SSP8GW12bjSO7D0Td6d6t1Rh5lbMT58X/view)

- [ ] When filtering by info that can be filtered, everything goes well. The bug concerns all the tables of that kind. 
[table filter bug repeat](url)

- [ ] When we go to from Library page (for example) to the Offers and Deals page, the scroll is blinking
[scroll blink bug](https://drive.google.com/file/d/1orhPqeHI1VRigylUm9RjJIDPJKFB15a_/view)

- [ ] FYI there was a moment that everything worked well on Chrome, but Safari was "frozen". It lasted for about 10min and then came back to normal. 
![safari.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/dbd590f2-94fe-4c23-b703-fcc476ec8a48)

- [ ] Need to put extra space between the titles in the header of the Selection page **Title 1, Title 2**
![selection.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/0bd21202-8192-4cef-a96d-3a28da24517a)

- [ ] Need to introduce the Standard Terms page as for the moment we've got an error and user sees this button everywhere and even needs to accepted to be able to create an offer @Jackseed @cams-goussale 
![standard terms.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/952ca790-16bb-4c29-b6a0-877d5e72ff6e)

- [ ] Seems that we need a mat-button instead of clickable icon here @stephanie-cascade8 
![mat button.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/56dba72e-a6e7-4209-bd3c-d9e31b0f9508)

- [ ] The column should be called "duration" and not "duration again" in Holdbacks section :) 
![holdbacks.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/7dfffed9-73e8-43d3-89f8-0754dbd311ea)

- [ ] @cams-goussale @Jackseed shouldn't these two buttons become TV and Movies and lead to the pre-filtered library page? 
If not, I guess that @isseymiyuki also asked to remove the Seller's page, so if the TV and Movie is not possible we could have "Library" only? (as putting wishlist or selection can make a disappointing effect even if i would prefer to keep both)

- [ ] Change the text in the notifications: when a seller receives an offer it should say "An offer has been made on one of your titles."
![notification text.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/3d1b33d1-5151-456b-9ba7-2090b47deb50)

- [ ] When a seller receives an offer with no price (asking price requested) he has two actions: "accept" (disabled) and "negotiate". We need to add a tooltip to the "Accept" one with the following text: You can not accept a contract without price. 
![tooltip to add.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/39b3e992-2ef4-45bf-aaec-acf5ff7d293f)

- [ ] Add some ponctuation signs to the reference 
Ref**.:** XXX-XXXXXX
![ponctuation.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/67042d0a-46cb-44e1-9326-c01425879b53)

- [ ] @Jackseed @cams-goussale do we agree that when user (buyer or seller) is in the negotiation mode s/he can't add new rights, but can only modify those rights that were already added? If yes s/he can't add new rights, then delete the "Add" button 
![add.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/cf8a854d-946f-46e2-92ce-bb1a7a3b62e1)

- [ ] Add a "come back" button to the negotiation mode 
![come back.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/510375af-83fc-4a33-9f23-87913be91a07)

### Dashboard
- [ ] On the My Deals page the order of the tabs should be the following: 
All, New, Ongoing, Accepted, Declined 

- [ ] If a contract has a status in negotiation it should go to the "Ongoing" tab
![my deals.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/c6a4fa8c-6856-4382-a055-3d9a5d103a55)

- [ ] When a user sends a counter offer (clicks on Submit in the negotiation mode), then the notification text should be the following: Your counter-offer was successfully sent. 
![counter offer.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/680c6f94-9fc2-4a75-b9cc-c0a7ab52e74c)

- [ ] When an offer was declined, add a snackbar to give a feedback (both dashboard and marketplace):  
"You declined contract for  [ Title’s Name ]." @maltmayer is it ok for the text ? 
![refusal.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/b5396605-6fb2-44fe-bb96-b6838f1630d6)

**TABLE IN THE MAIL**
- [ ] To optimize the mail let's align everything left (title and column infos too)
- [ ] Put the language with the first capital letter
- [ ] Delete spaces for versions: ( dubs ) should become (dubs)
- [ ] If no languages, then put "-"
- [ ] Maybe to gain the space we could use only first three letters of the month? like 18 jan 2022, @Jackseed @cams-goussale what do you think?
![mail optimisation.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/c986ba00-e453-48eb-9905-b893a58696d1)

![mail optimisation 2.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/11ba9c16-f62b-4d67-8699-1257efce65b9)

![mail optimisation 3.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/0f867c56-94a2-41b0-b5e2-350c54db86b4)

- [ ] Put a comma after the name in all mails
![name.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/1c3bea0d-06da-4967-acee-0a975948e17b)

- [ ] Uniform the counter-offer
![uniform.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/8af5eee6-f2d1-463f-8583-e6dc6aae454e)

- [ ] When an offer goes for signature, we need to show only the accepted contracts in the mail
![mail.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/5fbe8f0d-f78e-4257-97f1-51c08bb46388)

**Comment by cams-goussale** [comment]
Answers to @2amarkina 

> Need to introduce the Standard Terms page as for the moment we've got an error and user sees this button everywhere and even needs to accepted to be able to create an offer @Jackseed @cams-goussale

Working on it, will send it soon!

> @Jackseed shouldn't these two buttons become TV and Movies and lead to the pre-filtered library page?
If not, I guess that @isseymiyuki also asked to remove the Seller's page, so if the TV and Movie is not possible we could have "Library" only? (as putting wishlist or selection can make a disappointing effect even if i would prefer to keep both)

- If we want to get rid of `Sellers` and keep only the Library button => up to Yuki in CMS
- Having the split TV / Movie will be done with the related issues (so hopefully will be ready next release)

> @Jackseed @cams-goussale do we agree that when user (buyer or seller) is in the negotiation mode s/he can't add new rights, but can only modify those rights that were already added? If yes s/he can't add new rights, then delete the "Add" button

Agreed but I thought this was a reused component. If the `Add` can be easily removed, let's go ahead, but it's not blocking for the release

> Maybe to gain the space we could use only first three letters of the month? like 18 jan 2022, @Jackseed @cams-goussale what do you think?

Yes good idea

**Comment by cams-goussale** [comment]
My review [WIP]:

- [ ] Many emails are missing the signature
```
Best regards,
The Archipel Content Team
```
Al[l wording here](https://docs.google.com/spreadsheets/d/1OflJnj5dcEyWeorBVhHsIqWSovRldJpk5yYd20U5_Mw/edit#gid=657134932)

**Comment by isseymiyuki** [comment]
I confirm the two buttons should become TV and Movies and lead to the pre-filtered library page. Until then, I think that we keep both "Library" and "Sellers"; otherwise having just one option is not an option (rather no bottom is that case?)

**Comment by 2amarkina** [comment]
**Context** 
When a **Buyer declines an offer** s/he can choose the reason (via select) and write a message. 

When a **Seller receives an email** with the text "We are sorry to inform you that the offer for  [Title name] was declined." 

- [ ] We need to add one more variable right under: "Reason:  [Reason from select]." 
- [ ] And on the next line: "Message: "[Text from the text field]" (show this line _only if_  there is some text in the field.)


**Context**
When a **Seller declines an offer** s/he can also choose the reason (via select) and write a message. 

When a **Buyer receives an email** with the text "We are sorry to inform you that the offer for  [Title name] **was declined**." 

- [ ] We need to add one more variable right under: "Reason:  [Reason from select]." 
- [ ] And on the next line: "Message: "[Text from the text field]" (show this line _only if_  there is some text in the field.)
cc: @cams-goussale , @Jackseed

**Comment by Jackseed** [comment]
### Dashboard contract list
`/c/o/dashboard/sales`
![image](https://user-images.githubusercontent.com/14964443/150373279-126b3a60-1fdd-4648-a57d-a6c883bc8810.png)
- [ ] Status not showing properly here contracts have a status `pending` but it's showed as empty
- [ ] Also when status is empty best is to use `-` instead of `[]`

### External sale view
![image](https://user-images.githubusercontent.com/14964443/150374155-7dded0bb-e962-4696-949a-f152073cd8ef.png)

- [ ] Status is not display properly, instead of `NEW` it should be `PENDING`
![image](https://user-images.githubusercontent.com/14964443/150373840-e64ea5d3-b30c-40cd-9adb-76bbc852d901.png)
- [ ] Status select is not working, I got this error
```Uncaught (in promise): FirebaseError: [code=invalid-argument]: Function WriteBatch.update() called with invalid data. Unsupported field value: a custom e object (found in field status in document contracts/5N1v7IwyV03Kd8rGPySd)```
- [ ] Organization name is empty, best would be to use the name saved in the excel import on the "Licensee name" column; if that's not possible right now we should have "External Organization" instead

**Comment by cams-goussale** [comment]
Hello @yspringfield i hope i can help you prioritize the reviews above. I've marked in each point if it's:
A- necessary for the release
B- (i hope) an easy fix than can be done for the release
C- can be postpone for after the release

cc @RemcoSimonides

**Comment by yspringfield** [comment]
It's of much help, thanks.

**Comment by cams-goussale** [comment]
- [ ] Last wording check for the emails. In the table can we have instead of true false in the Exclusivity column:

`Exclusive`
`Non exclusive`

**Comment by RemcoSimonides** [comment]
Created https://github.com/blockframes/blockframes/issues/7633 for last open tickbox

**Comment by cams-goussale** [comment]
Remaining fixes need for #7639

**Comment by cams-goussale** [comment]
This review hasn't been taken into account yet https://github.com/blockframes/blockframes/issues/7556#issuecomment-1018387748

**Comment by RemcoSimonides** [comment]
Do you want this to be fixed before the release? Or can it be fixed after

**Comment by cams-goussale** [comment]
Email fixes pending #7641

**Comment by cams-goussale** [comment]
> Do you want this to be fixed before the release? Or can it be fixed after

Yes the emails & standard terms need to be fixed for the release

**Comment by cams-goussale** [comment]
- [ ] Missing modal on the map avails #7644
