### ISSUE TITLE
Difference in font weight on notification action

### ISSUE THREAD

**Issue by frenchyrules** [blockframes/blockframes#7691]
Different font weights on same button
![image](https://user-images.githubusercontent.com/85220905/151789492-d0179620-f726-44c8-8922-e03441c5fed4.png)
![image](https://user-images.githubusercontent.com/85220905/151789561-17f46e57-4d54-49aa-bfaa-fbdc8ffaabbe.png)

**Comment by RemcoSimonides** [comment]
The bold button is a link to email. We defined globally that these links should be bold. What we could do is to change the text of this action to something like "Email reply"

**Comment by RemcoSimonides** [comment]
Btw, I've updated the issue title to be more precise otherwise we might never find it back ^^'

**Comment by cams-goussale** [comment]
To maintain consistency, we could go for the text `Start Discussions` (it's the cta we have in emails). About the bold inconsistency, i am not sure i understand. Should it be bold in absolutely all notifications?

**Comment by RemcoSimonides** [comment]
The bold font weight for email links is globally defined for all the apps everywhere, not only in notifications.

**Comment by cams-goussale** [comment]
Idea: currently the `More details` option leads to the Buyer email adress. That's why it's a link and that's why it's bold. Why don't we 1/ change the text for Start Discussions 2/ redirect user to the Buyer's page

This way, it won't be a link anymore, am I correct @dmoncadalv @2amarkina ? Plus, this issue was only detected on AM, so it makes sense to redirect to the Buyer page.
