### ISSUE TITLE
(A) Sellers' Analytics - Dashboard - Interactions

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#7834]
[Wireframe](https://www.figma.com/file/FhY2dJqeYrVTXh7Q7HA0m7/%E2%9A%99%EF%B8%8F-Sellers'-Dashboard-(DONE)?node-id=438%3A145660)
[UI Design](https://www.figma.com/file/aNbs0XSJBqIvKrffJSzViH/Dashboard?node-id=78%3A2478)

![image.png](https://images.zenhubusercontent.com/5ed89f5adc98f2d44c81b9c0/db2bd2c1-63ac-432d-8d3d-282075f29c15)

**Comment by cams-goussale** [comment]
@RemcoSimonides here is the review on Seller's Analytics. I'm gathering everything in this issue.

user: Bettie Renner (dev+bettie-ctu@blockframes.io)

- [ ] (B) There is a jumps from loading from the "empty" to "full" state. Maybe need to calculate the that the empty state size = the full state to avoid it?
 
![jump from empty state.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/47e1516a-b1c8-4559-9d69-e0c76684e522)

- [ ] (A) The subtitle explanations are missing (maybe Remco you are still working on it?)

![minitext.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/ff01734c-8a23-4fd2-9900-12de5b7f9cb6)

title: `Split by Company Activity`
subtitle:` Learn who are the users who were interested in this Title.` 

title: `Split by Company Territory` 
subtitle: `Learn where are the interested people from.`

title: `Interactions`
subtitle: `Learn how people interact with your Title.`

title: `Film Page Views`
subtitle: `See how many Buyers viewed your Film Page recently.`

- [ ] (B) In the block "Split by Company Territory", could we zoom the map on the most popular country? Like that if there is only one country, it will be more visible.

- [ ] (B) in the block "Split by Company Territory", we limit the territories (in the text) to show up to 3. Always show the territories at the bottom of the card.

![country.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/b2d78338-0b6d-4681-980f-b70c657bcccb)

- [ ] (B) Tell me if i'm wrong, but the "View all Titles Activity" is a mat button, and it's usual behavior is to get a "squared" background on hover, (as in our footer for example), now it's rounded only in active state (nothing on hover), @stephanie-cascade8 could you please confirm what form should it take and if hover should be added? 

![mat button cosistency.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/bf5b7db3-bb2a-44e4-8030-ce94a6210461)

- [ ] (A) On the page Titles' Activity we have all the table that doesn't show the International Titles. At the same time, on the Dashboard page we have Bigfoot title that is published.

<img width="802" alt="image" src="https://user-images.githubusercontent.com/93206363/164414810-9c44a5c9-9e88-428f-8b8b-73d76e500205.png">

- [ ] It seems that even not published movies are in this table, but we should show only the Accepted titles, because only accepted Titles are published on the Marketplace.

![empty title activity.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/692e3fe5-c531-4314-b0ed-69e07a580d99)

**Comment by RemcoSimonides** [comment]
@cams-goussale Something like this? It looks good if there aren't too many dots, but if I switch to day, then there are too many and the line isn't visible anymore. If you zoom in using the tools, it's all fine again.
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/27687382/164462267-c8f01dfb-4a23-40d6-8ab9-b5fdbcfceecd.png">

**Comment by RemcoSimonides** [comment]
> - [ ] (B) In the block "Split by Company Territory", could we zoom the map on the most popular country? Like that if there is only one country, it will be more visible.

No, we cannot.
 
> - [ ] (B) in the block "Split by Company Territory", we limit the territories (in the text) to show up to 3. Always show the territories at the bottom of the card.

In this case there is only one country available. Would you like me to show 2 random countries with a 0? 😅 @2amarkina

**Comment by cams-goussale** [comment]
> @cams-goussale Something like this? It looks good if there aren't too many dots, but if I switch to day, then there are too many and the line isn't visible anymore. If you zoom in using the tools, it's all fine again.

Yeah it looks good. Let's go with the dots for now!
