### ISSUE TITLE
Disable preview in Film Poster

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#7862]
In the movie tunnel a user uploads a Poster mage and a Banner image. Then goes to the Summary Page. On the Summary Page user still sees "Missing" near the Poster and a Banner image, even if s/he has just uploaded them. Also, when a user clicks on a preview near Poster or Banner image on the Summary Page, there is a Modal with "Sorry, we can't display this format" even if the format is alright. 

**[See a video example here](https://drive.google.com/file/d/1CEDN8fiikiVeugVNPIqUg_FKFOUU4iCh/view)**
_P.S. one more bug appears with "jumping" page._ 

Solution: use the same system we use for the Promotional images: 

- [ ] disable preview 
- [ ] add a tooltip "Save and close to finalize" 
- [ ] do not show "missing" text 

<img width="263" alt="Снимок экрана 2022-02-24 в 11 10 20" src="https://user-images.githubusercontent.com/55499036/155504415-14b9c045-e4a2-48c4-a741-f2d06cea40b1.png">

_P.S. if possible put a tooltip closer to the eye_

_Originally posted by @2amarkina in https://github.com/blockframes/blockframes/issues/7759#issuecomment-1041924952_

**Comment by cams-goussale** [comment]
These rules should actually apply to all media uploaded in the movie tunnel

**Comment by phpgeekfr** [comment]
issue mentionned in `https://docs.google.com/spreadsheets/d/152BY91BxRHMksMK-t9Xw_WzKAnxLhl0M4jtex9NY32Y/edit#gid=0`

**Comment by cams-goussale** [comment]
I think this issue is partially done with the latest changes done during release 4.2 (https://github.com/blockframes/blockframes/issues/8299#issuecomment-1118478820)

Yet I still find this very unclear ^^ I have spotted 3 different status of the eye icon:

when media is completely uploaded and user can preview it:
![image](https://user-images.githubusercontent.com/93206363/168287000-c7697064-f4c9-4649-b182-f6414ad40a5b.png)

when there is no media to see:
![image](https://user-images.githubusercontent.com/93206363/168287275-77766db9-05b0-4815-807c-5a0d414a72b8.png)

when user should save and close to be able to preview:
![image](https://user-images.githubusercontent.com/93206363/168287419-a63adec8-04cc-4eb0-b4cd-6f2ef8554818.png)

@2amarkina do you think this should go back to UX so we think about it in depth? The tooltips also needs to be discussed with business as I don't really understand what they mean.

**Comment by 2amarkina** [comment]
> I think this issue is partially done with the latest changes done during release 4.2 ([#8299 (comment)](https://github.com/blockframes/blockframes/issues/8299#issuecomment-1118478820))
> 
> Yet I still find this very unclear ^^ I have spotted 3 different status of the eye icon:
> 
> when media is completely uploaded and user can preview it: ![image](https://user-images.githubusercontent.com/93206363/168287000-c7697064-f4c9-4649-b182-f6414ad40a5b.png)
> 
> when there is no media to see: ![image](https://user-images.githubusercontent.com/93206363/168287275-77766db9-05b0-4815-807c-5a0d414a72b8.png)
> 
> when user should save and close to be able to preview: ![image](https://user-images.githubusercontent.com/93206363/168287419-a63adec8-04cc-4eb0-b4cd-6f2ef8554818.png)
> 
> @2amarkina do you think this should go back to UX so we think about it in depth? The tooltips also needs to be discussed with business as I don't really understand what they mean.

I remember that in this one there were also some tech issues, so it would be better and clearer for everyone if we put this back to UX in order to rediscuss together with devs and test all the cases. 

Following this step and having a clearer image we could discuss new wording with business accordingly.

**Comment by phpgeekfr** [comment]
For me this should be discussed along with the cropper/upload refactoring

**Comment by RemcoSimonides** [comment]
There is a [solution](https://github.com/blockframes/blockframes/pull/8426) for this issue but Francois doesn't like it and suggests rethinking the whole movie form. I think it's a downside of how we handle media in the app and don't see how we can 'solve' it without again refactoring how we handle media.

**Comment by Jackseed** [comment]
If it goes to UX, it should be a simple issue:
- manage the 3 existing states to be clearer with wording and UI but that's it not adding more complexity to that subject

**Comment by 2amarkina** [comment]
Wireframes are [here](https://www.figma.com/file/3McgZsJNB4wcm6MsUyo6dR/%E2%8F%B3-Preview-Icon-Behaviour)

Proposed scenarios to be checked with dev: 
1. If a file is not uploaded in the Movie Tunnel, then show "Missing" with no preview icon.
2. If a file uploaded in the Movie Tunnel, but not saved, then show "Uploaded" with no preview icon.
3. If a file is uploaded and saved, then show the name of a file and a preview icon
