### ISSUE TITLE
Refactoring of Medias parameter (catalog)

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7893]
After a legal discussion, the Medias parameter on Archipel Content should be updated to the list below:

## TV
Pay TV
Free TV
Pay Per View

## VOD
EST
N-VOD
A-VOD
F-VOD
S-VOD
T-VOD

## Ancillary Rights
Boats
Inflight
Hotels
Educational

## Video (DVD, Bluray)
Rental
Sell Through

![image.png](https://images.zenhubusercontent.com/617811d92b89e7733866d8a0/9987af75-5b2b-469a-b042-956fa3c294d3)

Places impacted:
- [ ] The db
- [ ] Filters on the /marketplace/library
- [ ] Filters on the /marketplace/title/[titleId]/avails/map
- [ ] Filters on the /marketplace/title/[titleId]/avails/calendar
- [ ] Filters on the /dashboard/avails/
- [ ] Filters on the /dashboard/avails/[titleId]/map
- [ ] Filters on the /dashboard/avails/[titleId]/calendar
- [ ] Excel imports: Movies, Contracts

**Comment by phpgeekfr** [comment]
@cams-goussale should `theatrical` be removed ( it exists in the list we have in code but is not listed here)?
If yes, developer that will tackle this issue should take care of `[withoutValues]="['theatrical']"` and unit tests that use this `Media`.

By looking at the existing list in `static-models`, `boats` is already existing but not displayed in `static-select` because it is not part of any `groups`, so it looks like it is only need to add it to correct group

**Comment by cams-goussale** [comment]
@phpgeekfr @KvnMrs we won't be using `theatrical` anymore, so you can remove it.
Also, it was asked if we can add `festival` `Festival` into the list, under Ancillary Rights section
