### ISSUE TITLE
Update Request Asking Price button with a spinner

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7899]
This was mentionned during a release, but it wasn't fully implemented everywhere. Could we add buttons with a spinner on all the `Send my request` modal of the Request asking price?

The screens where this modal can appear are:
- Title page
- Screening list
- Ongoing Screening
- Finished Screening session

https://user-images.githubusercontent.com/93206363/156398437-c9429c51-906c-4695-8978-f319c5288ed6.mp4

**Comment by phpgeekfr** [comment]
Spinner should be displayed once clicked on button :
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/5926b9cc-af4c-419d-b4ed-a187ec241850)

use the same logic as this button :
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/cd75b19a-81cd-4529-8414-fba222f08fae)

libs/event/src/lib/components/request-screening/request-screening.component.html

**Comment by KevinDurand974** [comment]
We found a event problem on custom FormControl

`libs\movie\src\lib\movie\components\request-asking-price\request-asking-price.component.html`

On click (`(click)="send()"`), this form is disabled with `this.form.disable()` but the state hasn't changed.
Who, doesn't trigger `[disabled]` passed in parameter which allow to disable the button and avoid another click.

After some researches with Bruce, Kévin M. and Kévin D., we found that the problem came from
```ts
this.form.disable();
```
In : `libs\movie\src\lib\movie\components\request-asking-price\request-asking-price.component.ts`

The disable form is called by `libs\ui\src\lib\static-autocomplete\group\group.component.ts` line `109+`

```ts
@Input() get disabled() { return this._disabled; };
set disabled(value: boolean) {
  this._disabled = coerceBooleanProperty(value);
  this._disabled ? this.form.disable() : this.form.enable();
  this.stateChanges.next();
}
```

This line (▼) is the cause of the problem
```ts
this._disabled ? this.form.disable() : this.form.enable();
```

For this to work (in our case), we need to change this :
```ts
this._disabled ? this.form.disable({ emitEvent: false }) : this.form.enable({ emitEvent: false });
```
This one prevent the event from being launched, which return the right value after `this.form.disable()` is called.

Now, doing this may impact another area.
