### ISSUE TITLE
Decline invitation to the org

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#8035]
**Context:**
As there is an ongoing work on notifications and there is a question about keeping or not a notification about joining the org. 

**Remarks:**
- For the moment user can't invite a member, who has already been attached to company. 
- User receives the following message if this happens ![Снимок экрана 2022-03-18 в 12.23.26.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/a3d7b6d6-5b04-4b26-af3e-e57c363c9612)

**Task:**
- [ ] Check all the flows to be sure if we keep the present logic and do not let users invite people with orgs
- [ ] In any case, rework the snackbar feedback

**Comment by cams-goussale** [comment]
> Check all the flows to be sure if we keep the present logic and do not let users invite people with orgs

This flow is good imo. It does not make sense that a user belongs to 2 orgs, plus it might create lots of side effects if we were to allow this. I wouldn't dig further as this seem to be the expected behavior.

> In any case, rework the snackbar feedback

I think this is already handled with this [suggestion ](https://docs.google.com/spreadsheets/d/11mgu0-s9i0KIBRgRUAlE-WjuJQLOaTmMcdrVLEUKwAk/edit#gid=0&range=A35:M35) in the inventory.
