### ISSUE TITLE
Invitation pending not showing the name of the member

### ISSUE THREAD

**Issue by vwmathilde** [blockframes/blockframes#809]

**Comment by ioaNikas** [comment]
### Reproduce the bug

When we send the invitation, we trigger `getOrCreateUserByMail`, which first create the new user account in Authentication.

A backend function react to this event and create a document with the new user in `users` collection.

Meanwhile (right after the creation of the user in Authentication), we create an invitation, set it in Firestore, and then our store tsee the change and update himself, but the id of `invitation.userId` leads to nothing as the invitation is created before the user in the database.

### Expected behavior

The user document must exists in the database before we create the invitation.

### Clues on how to solve this issue

Wait for the user to be set in the database and only then create the invitation.

**Comment by Jackseed** [comment]
done > closed
