### ISSUE TITLE
User still receive mail & notifications despite deactivating the notification settings

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#8436]
Originally posted by Camille in [Release 4.2 - Profile/User](https://github.com/blockframes/blockframes/issues/8350#issuecomment-1115970229)

- [ ] After desactivating all email and notifications in the page /c/o/account/profile/view/notifications user still received a notification and email for Content Management (in this case, when title submitted and when title accepted)

**Comment by cams-goussale** [comment]
@Poppe-A you're right, there should be another notif for "movie submitted". I've added a line (only for AC because this notif does not apply in AM). I also have 2 additional questions:

- `A user's request to join your organization is declined.` -> this one is not received, either by email, either by in app notification. If Im not wrong, it should disappear with this issue #8026. Therefore we should also remove it from the Notification Settings. Let me know if this sounds correct to you too

- `Your offer is now under signature or validated by all parties. (RECOMMENDED)` -> I think you've mentionned this one to Vincent. Indeed, this notif isn't sent anymore so we should remove it from the Notificaiton settings.
