### ISSUE TITLE
Request Screening Flow - Pre-fill buyers' name in invitations section

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#8438]
Originally posted in [Release 4.2 - Events](https://github.com/blockframes/blockframes/issues/8302#issuecomment-1117119665)

> - [ ] (B) When a Seller answers the request of screening, we have a preselected title on the event creation form. Could > we also pre-fill the Buyer's name who has asked for a screening in the invitations section? 

@2amarkina @cams-goussale 
Yes, it is possible. This can be done in three ways:
- Easy solution: Add buyer information to the email sent to the seller. With this only 1 buyer can be pre-filled (not all buyers who requested)
- Medium solution: Get information from Analytics to see which buyers requested screening
- Hard solution: Refactor the whole flow to use invitations (of type 'request') instead. This wasn't done from the start because this feature wasn't in the scope.

**Comment by cams-goussale** [comment]
Easy solution seems more than enough to me!

**Comment by 2amarkina** [comment]
All the screens are [here ](https://www.figma.com/file/c62IFnbBC2UFcHZFY861jV/%F0%9F%8E%80-New-Market-Interactions?node-id=728%3A27927 )

**Comment by RemcoSimonides** [comment]
- [ ] Invite user without sending a notification

**Comment by cams-goussale** [comment]
Lgtm, thanks for the explicit wireframes. I'm sending this to devs directly. As far as I know, this was the initial flow when we implemented the Buyers Interactions. It might have been lost in translation ^^

In any case, for devs, the scope of this issue is:

- [ ] When seller answers a request to organize a screening, the buyer's email should be prefilled
- [ ] In the notification, can we make the User name in bold (as we have in invitations)
- [ ] In the notification, can we have the Movie name clickable and underlined (redirect to movie page on dashboard side)

**Comment by cams-goussale** [comment]
Open question: send directly the email to the buyer
Rename for "send a screener"
