### ISSUE TITLE
Mandate/Term creation.

### ISSUE THREAD

**Issue by yspringfield** [blockframes/blockframes#8763]
Test issue for #8668.
Any issues should be indicated here.

**Comment by yspringfield** [comment]
https://github.com/blockframes/blockframes/issues/8668#issuecomment-1178775887

**Comment by cams-goussale** [comment]
# Review 08.07.22

### 1- Creating new Terms

- [ ] When clicking the first time on the rights card to create a term, there is a jump and user must click on Add button after the jump. Console error `Cannot read properties of undefined (reading 'value')`

https://user-images.githubusercontent.com/93206363/177962746-25be9bb7-9954-4cb8-a454-fe9cc2bf629d.mp4

- [ ] When creating terms, could the timestamps always be `2:00:00 AM UTC+2`? (same as we have when we import mandates with the excel)

- [ ] When creating avails, the dates of the Rights card is prefilled. Can we have end date set to today + 1 year? Currently we have start date == end date. Can we also set Exclusivity parameter to `Exclusive` by default?

![image](https://user-images.githubusercontent.com/93206363/177963853-c5dc2c22-69cc-4396-bff5-b02a916b9fb5.png)

- [ ] Once terms are created, user should be redirected to My Avails page.

https://user-images.githubusercontent.com/93206363/177966726-33e8a88c-1bbe-48ed-a755-df535dcdbd5e.mp4

### 2- Editing existing Terms

- [ ] When clicking on Edit Avails on the My Avails page, I get this error
`TypeError: Cannot read properties of undefined (reading 'value')`

![image](https://user-images.githubusercontent.com/93206363/177959671-1175cedc-b343-4bae-b945-4f5cccb38049.png)

- [ ] When clicking on the Edit button of the Term, could it anchor to the top of the page where the card can be edited?

https://user-images.githubusercontent.com/93206363/177960064-2a33993b-f5ac-4446-a6a2-b0c264547a6f.mp4

- [ ] When editing an existing term, there is a jump on the size of the card.

https://user-images.githubusercontent.com/93206363/177960539-46f0e779-0d60-4d16-9359-0c0a49d4ce43.mp4

- [ ] I edited termId `1ZtZEqSfKlNDkZKAxYrA` and removed 1 media of the list (`Pay Tv`) but it didn't reflect the change in db

![image](https://user-images.githubusercontent.com/93206363/177961588-20f29944-be67-4423-8e7f-8feb3a8940f4.png)
![image](https://user-images.githubusercontent.com/93206363/177961633-e97a5915-3df9-4279-8321-3f65f9cbf5ce.png)

- [ ] I edited mandateId `cb9TvU6KYa6d6D09heno` and instead of modifying existing terms, it created a 2nd mandate with the modified terms

![image](https://user-images.githubusercontent.com/93206363/177965951-25758312-2ba3-41c8-b3f8-7a7ce3f18aef.png)
![image](https://user-images.githubusercontent.com/93206363/177966297-26cd4fdb-efe6-469b-bccd-f1b90f0dad36.png)

- [ ] After Editing terms, the snackbar says `Terms created`. Ideally, it should say `Terms updated`.

- [ ] When editing terms in CRM, if blockframesAdmin clicks on the back arrow and then edits another term, it loads infinetely.

https://user-images.githubusercontent.com/93206363/177967538-5dc27743-14d7-4c47-a298-b4bc214fc918.mp4

**Comment by cams-goussale** [comment]
> When creating terms, could the timestamps always be 2:00:00 AM UTC+2? (same as we have when we import mandates with the excel)

- [ ] This is still incorrect. Currently it creates the timestamp at `1:00:00 AM UTC+2` instead of `2:00:00 AM UTC+2`


- [ ] I get this error when submitting the movie at the end of the movie tunnel. This is a bit out of scope because it relates to the movie tunnel, not the mandate creation, so we can ignore if irrelevant.
![image](https://user-images.githubusercontent.com/93206363/178294538-a6b0933c-c30d-4bf5-b208-27aaa55d3ca5.png)
