### ISSUE TITLE
Can't use Angular Router after the disconnexion of the user (current fix is ​​to reload the page)

### ISSUE THREAD

**Issue by Hugo-Hontans** [blockframes/blockframes#879]

**Comment by Maxstgt** [comment]
since we are using akita ng fire, we either can do some redirecting when the sync function fails in the guard, or we just call window.location.reload(), in the hook of onSignout, which is the current state. And I talked to @GrandSchtroumpf and he thinks it is okay to cal window.localtion.reload(). So this issue can be closed now. Reopen if you want to have a different behavior
