### ISSUE TITLE
Incoherency between the event statistics and the statistics shown on title report page.

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#8804]
Something is incoherent between the event statistics and the statistics shown on title report page. Start a discussion and figure out what exactly should be shown on both pages.

![image](https://user-images.githubusercontent.com/93206363/179482915-31539588-4df7-4c6b-9cee-20d147f9c8d5.png)

![image](https://user-images.githubusercontent.com/93206363/179483047-7ad43b51-f04c-4adf-8f00-70f66684c74f.png)

It seems each time a user is clicking on Ask for a Screening, this user enters in the analytics related to screenings. Here, we are on the user report page, and as the user asked for a screening, he is shown on this section. Though in reality this user never went to a screening

![image](https://user-images.githubusercontent.com/93206363/179484259-7acbe500-d83d-4281-a66c-c1fedead23f8.png)

_Originally posted by @cams-goussale in https://github.com/blockframes/blockframes/issues/8769#issuecomment-1186981988_

**Comment by cams-goussale** [comment]
WIP

I made some tests as follow. I organized a screening event and invited 3 users. A 4th user requested access to the screening, but was never accepted (remained as a pending request).

## Statistics on Event page
(`dashboard/event/{id}/statistics`)

![image](https://user-images.githubusercontent.com/93206363/180471543-c8a7fd2e-2065-4dac-aea0-4b43ff6c74fb.png)
Here I think we should discuss each statistic meaning:

- [ ] Guests: as a Seller this should represent the people I invited (my guests). Currently it shows guests + requesters.
- [x] Attendees: people with watch time > 0
- [x] Average watch time: total watch time / total_attendees
- [ ] Participation rate: (total_attendees/total_invitations) * 100. Here same problem as before, we should consider invitations only the ones sent by the organizer. Not the requests to join event.
- [ ] Traction rate: total_requests/total_invitation * 100. Here, invitations should be all types of invitation, whether it is sent by the organizer or whether it is a request.

## Statistics on Title Report Page
### Before Request Access
![image](https://user-images.githubusercontent.com/93206363/180470505-da45d8d3-0683-4989-b337-0e1d5d155017.png)
### After Request Access
![image](https://user-images.githubusercontent.com/93206363/180470593-e36a68b9-e0b6-41fe-a2b1-cae7dad8cb75.png)
### Conclusion
I think there was a confusion here because initially it was supposed to show just the statistic of the Last screening organized. Now I understand it shows all the statistics from all the screeningS organized for this title. Which is great, but i think we should chnage the wording as follow:

- [ ] Header: `Screenings Performance`
- [ ] Sub text: `Check the cumulative statistics of this title's Screenings.`

**Comment by cams-goussale** [comment]
@Jackseed can you confirm you're aligned on the Statistics calculation? (the first part of my comment)

**Comment by Jackseed** [comment]
> [ ] Guests: as a Seller this should represent the people I invited (my guests). Currently it shows guests + requesters.

I'm not sure of this one, I agree that "Guests" should mean invited people but I think it's more interesting to have the overall amount of guests+requesters so I would keep the actual calculation but rename the card
Though I must say I have no idea on possible wording sorry :x

**Comment by cams-goussale** [comment]
Ok, then let's keep Guests as it is
