### ISSUE TITLE
[Open discussion] Creating an offer on a multi-term mandate

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#8807]
@Jackseed could we discuss this sometime, about Archipel content.

When a Buyer makes an offer which affects 2 terms of a mandate, it will create 2 offers. Example:

MandateA contains:
-- TermA {France, VOD}
-- TermB {Germany, VOD, TV}

Buyer wants to buy {France, Germany, VOD}. This will trigger 2 offers, one attached to TermA and one attached to TermB

This logic was described here #7919 by Springfield when we worked on multi-terms mandates. It was a request from Francois because he said you discussed this together during a long time, and it was necessary to track the watefall.

**Comment by Jackseed** [comment]
Ok so it looks like:
- it's the correct behaviour if we want, in the long run, to be able to split revenues correctly in-app. Indeed, each term could have its own revenue share so we must split it per term and not per contract
- since we have no waterfall calculation implemented in AC, I think that creating a contract per mandate instead of per term would be easier for everyone
- though there are edge cases (mandate split in 2 terms because of duration, let's say TV France 2021 + 2023) that would demand to create 2 contracts to be correct
All things considered I think we should keep with what we have and try when importing mandates to create split terms based on rights or dates not territory, to avoid the example you give @cams-goussale 
Open to discuss that ofc
