### ISSUE TITLE
Promotional Elements Uploaded double-click on Save

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#8914]
Before leaving, Remco detected a bug in the movie tunnel, when clicking twice on the Save button of the movie tunnel. Here are the 2 behaviors (the one buggy, the one working well).

Buggy behavior:
1- upload promotional elements (pdf files, video files, images)
2- click on save the movie, it'll start uploading the files
2bis- check summary, files seem uploaded correctly
3- re click on save
4- close movie tunnel, all files have been erased

Good behavior:
1- upload promotional elements (pdf files, video files, images)
2- click on save the movie, it'll start uploading the files
2bis- check summary, files seem uploaded correctly
3- close movie tunnel, everything is correctly uploaded

**Comment by phpgeekfr** [comment]
I found a solution that seems to work pretty well except for one location:
 `libs/movie/src/lib/movie/form/media-videos/media-videos.component.html` ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/b9fb3802-ad27-4b9f-acc3-324387972ce7)

This is because this component is using `bf-form-list` to handle multiple files upload and compromise the array index (because we don't re-enter ngOnInit). So if user change page (go to summary for example) and click save, uploads will be lost

for `libs/movie/src/lib/movie/form/media-notes/notes.component.html` ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/3349da58-147b-4574-8fcc-ddcf4d3323c5)
we could also have weird behaviors but this looks like to be working because `keepFormOpen` is not set.

**Comment by phpgeekfr** [comment]
- [ ] also, only for `otherVideos` upload, another issue can happen with `fileId` field: if we click on save when storageVideo is defined on db document (ie: linkFile, move from tmp dir) but before `jwPlayerId` is set, the field `fileId` is removed, preventing `jwPlayerId` to be defined. 
This should be solved by adding `fileId` formControl in 
```
function createMovieVideoControl(movieVideo: Partial<MovieVideo> = {}) {
  const file = createStorageFile(movieVideo);
  return {
    privacy: new FormControl(file.privacy),
    collection: new FormControl(file.collection),
    docId: new FormControl(file.docId),
    field: new FormControl(file.field),
    storagePath: new FormControl(file.storagePath),
    title: new FormControl(movieVideo?.title ?? ''),
    description: new FormControl(movieVideo?.description ?? '', Validators.maxLength(1500)),
    type: new FormControl(movieVideo?.type ?? ''),
    jwPlayerId: new FormControl(movieVideo?.jwPlayerId ?? ''),
  };
}
```

**Comment by phpgeekfr** [comment]
If saving was prevented due to missing jwPlayerId, a sentry error is pushed: 
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/1f6b8e93-cb0a-4c7f-96a2-cbd9a7301465)

**Comment by phpgeekfr** [comment]
- [ ] in this PR, also debugged the file moving (from public to protected dir or vis-versa ) when changing video privacy. ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/bda12c12-16e5-4703-87ae-208764746066)

**Comment by phpgeekfr** [comment]
- [ ] jwPlayerId is retrieved directly when copying file from tmp dir to final destination and not in a second step as before

**Comment by phpgeekfr** [comment]
- [x] added a new sentry error if invalid metadata for an upload.
- [x] prevent form saving (save button and publish) during 3 seconds after upload completed
