### ISSUE TITLE
Send orgId when user adds terms to selection with icon feature

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#8946]
It seems we currently have different behaviors when a user adds terms to his/her selection.

-> If user adds a term through the marketplace avails page, it sends orgId in db collection `bucket`.
-> If user adds a term through the icon "add to my selection" on the library page, then orgId is empty in the `bucket` collection

Ideally, both behaviors should be the same. Need to investigate if that impacts other places

**Comment by phpgeekfr** [comment]
not having this orgId set in bucket contracts generate an error when `auditDatabaseConsistency` is performed
![image](https://user-images.githubusercontent.com/1194344/193549768-f8a0a203-b49c-4d2d-82ed-a1111d8fe0e6.png)

**Comment by phpgeekfr** [comment]
I identified the issue and was able to fix it by adding the orgId when a term is added via "add to my selection" so both methods now behave the same. 

But I have the feeling that this field is not used because `createOffer` in `libs/contract/src/lib/bucket/service.ts` is always setting `centralOrgId.catalog` as `sellerId`. Maybe at first it was supposed to be the `orgId` (mandate orgId) specified when adding to selection but it was then decided to put our orgId

**Comment by phpgeekfr** [comment]
OK so either :
- we keep the orgId field in both situation, safer but laziest solution
- we look deeper to find if it is used and if we can remove it completely

@cams-goussale I would suggest to go for the first solution now and merge this fix for current release (4-5-4) and then update this ticket to go deeper in the future ?

**Comment by cams-goussale** [comment]
sounds ok to me. @Jackseed ok for you too?

**Comment by phpgeekfr** [comment]
created #9036
