### ISSUE TITLE
Semi-Public access to the line up of a Seller

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9124]
**Context:** During the communication campaign the last year we have distributed the QR codes to the Sellers attending the film market. The QR code contained a link to the line-up of each particular Seller (/c/o/marketplace/organization/orgID). 

**Problem:** The campaign went pretty well, but some Sellers were not connected to the application via their mobile and/or didn't have a personal account, so the access to the page was complicated. 
We also want to give Sellers analytics on their line up page so we need to have a bit of personal info on buyers.

**Possible solution:** To avoid such situations we would like to give a semi-public access to the Sellers' line-ups (as we have for the protected Screenings on the Archipel Market). 

**Details discussed:** 
1. If a user is connected to the app, s/he should be directly redirected to the Seller's line-up of a scanned QR code (/c/o/marketplace/organization/orgID). 
2. If a user is not connected, we should grant the protected access: first name, last name, email. 
3. If possible, do not show Seller' member emails on Team section in the Contact tab for semi-anonymous users.  
4. If a user clicks on the Title in the line-up we should show the normal login page/create an account page.  

**Questions:**
1. If the access is protected, does that mean that nevertheless we should invite a user within his/her email address BEFORE they access the app? If so, we might think about having "public" access as for screenings (first and last name only). 
2. It might be confusing for a user that there are two different ways to log in ("I've just entered my infos and if I click on the title it asks me to re-enter my informations"), so create an account might be preferable. 
__To discuss:_  if possible, create an intermediate state with a modal "You're about to quit the public mode. To access these details you need to be full registered. CTA: Full register (link to the Create account page)"_
3. If not possible to hide the members' emails in the Team section inside the Contact tab, then discuss other possibilities (e.g. if user clicks on Contact tab s/he is redirected to the Create an account page)
4. What about users with emails already registered as users?

**Comment by phpgeekfr** [comment]
- [ ] check & create an estimation

**Comment by 2amarkina** [comment]
**Not to forget:** 

- [ ] See if we are able to quickly connect the users who already have their accounts to the platform via semi-public access

**Comment by phpgeekfr** [comment]
@2amarkina @Jackseed 
**My questions:**

- [ ] firstName, lastName & email of anonymous users checking an org line-up should be stored. In analytics collection ?
- [ ] what if user clicks on a title, is asked to login (we checked that he already have an account) but his account does not have access to current app or marketplace module ?
- [ ] is this issue for festival or catalog app, or both ?
- [ ] `If a user is not connected, we should grant the protected access: first name, last name, email.` What if user already have an account but is not connected ? We don't let him the choice to directly log-in instead of using semi-public access ?


**Your Questions:**
_1. If the access is protected, does that mean that nevertheless we should invite a user within his/her email address BEFORE they access the app? If so, we might think about having "public" access as for screenings (first and last name only)._ 
 => no need to invite user, we will just not check email (so anyone can use anyone else email, firstname & lastname)

2. It might be confusing for a user that there are two different ways to log in ("I've just entered my infos and if I click on the title it asks me to re-enter my informations"), so create an account might be preferable. 
__To discuss:_  if possible, create an intermediate state with a modal "You're about to quit the public mode. To access these details you need to be full registered. CTA: Full register (link to the Create account page)"_

=> this should be possible, like when we leave a screening page

3. If not possible to hide the members' emails in the Team section inside the Contact tab, then discuss other possibilities (e.g. if user clicks on Contact tab s/he is redirected to the Create an account page)

=> This should be possible but note that someone with javascript skills will be able to see emails

4. What about users with emails already registered as users?

=> they will be able to use semi-public login as well

**Comment by Jackseed** [comment]
Thanks for your answers & estimation,
Here are mine:

> * [ ]  firstName, lastName & email of anonymous users checking an org line-up should be stored. In analytics collection ?
Yes

> * [ ]  what if user clicks on a title, is asked to login (we checked that he already have an account) but his account does not have access to current app or marketplace module ?
To confirm with @2amarkina but I would say: we show user login page (and not sign up), with email already pre-filled (bonus) and once connected we continue the classic flow so we show the page to request access if no app access or dashboard homepage if the user hasn't marketplace module (shouldn't happen since it's for festival only)

> * [ ]  is this issue for festival or catalog app, or both ?
festival only

> * [ ]  `If a user is not connected, we should grant the protected access: first name, last name, email.` What if user already have an account but is not connected ? We don't let him the choice to directly log-in instead of using semi-public access ?
Indeed a link to login would be best, and even better a hint or something appearing if we see that the email used is attached to a user. 
@2amarkina could you work on a flow + wireframes for these pages? It looks like we need it for clarity.

> * [ ]  what should look like the analytics part on seller dashboard ? and on CRM ?
Adding this on sellers' dashboard is nice to have but let's discuss it to see what it would require.

**Sellers' dashboard**
I think best would be to add this stat on the user related to movies analytics (on top of add to wishlist, movie page views,...) with something called "Line-up views". 

**CRM**
I would prefer to add this new stat to the existing user/Title analytics csv (and thus avoid to add a new export). Not 100% sure so glad to discuss this but right now I would go for:
- adding a new column "analytics type" with org/title
- adding a new column "visited orgId" that replace movieId when it's an org type analytics
- counting line up views in "page views" column and counting it also in festival interactions
