### ISSUE TITLE
Urgent Bug Avails - AC

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9293]
**Context:**
When a user is on the Dashboard view and wants to modify the avails, the CTA "Validate" is disabled (Dashboard / My avails / Manage Avails). 
When trying to apply modifications, the CTA remains disabled. 

![avails_management](https://user-images.githubusercontent.com/55499036/229748597-bf37a1ec-99bb-47c2-a279-5b71bb9a5e84.png)

It seems that the old films are impacted. 

**Films concerned:** 
- on production: films from Loco (organization) ; 
- on staging:  this user (rzf1Zw3fxTXYp56UlJj01pSbaCG3) ; this film (qUottvWKewtMw1o9tpAv/manage)

**Comment by phpgeekfr** [comment]
This is because terms are using medias and territories that does not exists anymore:
for this film `qUottvWKewtMw1o9tpAv` :
medias:
- `theatrical`

territories:
- `mayotte`
- `reunion`

This terms are quite old (2021) and migration was not performed to update medias & territories on existing terms

Removing this from the terms associated to this movie should do the trick

**Comment by 2amarkina** [comment]
> 

Is it possible to obtain the exact list of the elements that were removed?

**Comment by phpgeekfr** [comment]
Would be best to create a migration for this indeed

**Comment by phpgeekfr** [comment]
PR with migration : https://github.com/blockframes/blockframes/pull/9297
