### ISSUE TITLE
Distributors’ Statements

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9524]
**Context:** 
The most detailed issue, as the first one. The next Statements and Revenue Declarations would be pretty much the same. 

**Screens:** 
To access the Distributor's Statements, need to use [this link](https://www.figma.com/file/bu5jFTcdDk4frztQ3v7nFA/Redditions?type=design&node-id=471-23129&mode=design&t=5YuUPLdXY7zbRaNL-0 )

### Pre-settings
When a user adds a Distributor’s Statement for the first time : 

- There is a modal that appears and users can choose an already existing distributor or add a new contract. 
- If a user chooses an existing distributor the information about territory and media appears.  
- If a user chooses a non-existing distributor, then the new contract form appears.
- Users also are able to add the conditions to the new contract. User clicks on “add conditions” link and is redirected to the Waterfall Conditions creation page.
- After filling in the contract form and saving it, users should be able to find this contract in the Documents / Local Distributors’ List.
- When a Contract is added, the user is redirected to the statement’s editing page for the first time. 

_The same principle will exist for other Statement creation._

### Statement Creation 
- User is able to provide the period of the statement. 
     - If it's not the first statement, there’s an arrow to get back and the user can see all the previous information in non-editing mode. 
     - If every user wants to fill in the next period, the date is calculated automatically according to the Periodicity. 
     
- Periodicity field should contain : 
     - Monthly, 
     - Semesterly, 
     - Yearly.

- The navigation tabs for the DIstributor's Statements _might_ the followings : 
     - Theatrical 
     - TV
     - Video
     - Miscellaneous
     - Expenses
**BUT THEY WILL DEPEND ON WHAT THE USER HAS DECLARED IN HIS CONTRACT**

- The page body block adapts accordingly to the navigation tab. The block contains the supplementary elements that can be added to the main table as new columns. 
   
- On the Expenses Page user can find the blocks per media according to the Media precised on the Contract Page 
If there is a CAP, it needs to be shown. 
     - If the amount that the user enters is higher than the CAP, then it should be highlighted with the red color. 
     - If amount approaches the CAP, then it should be highlighted with yellow color
**TO BE UPDATED ACCORDING TO THE LAST UPDATES ON 18/10**

### Summary Page 
(will be used also for the .pdf . For the .pdf all the elements in the expansion panels are opened by default)

**TO BE UPDATED ACCORDING TO THE LAST UPDATES ON 18/10**

### Modifications 
- When a user doesn’t agree with our calculation, s/he needs to tell us about it. Also, a new version should be created. 
- User sees an “alert” highlighted icon with the following tooltip text : “Do not agree with calculation? Click here to edit the value”. 
- After clicking, there is a modal that appears. Modal contains the following: 
     - Provide the new value field
     - A field where a user can explain why s/he wants to edit the value 
     - To apply the modifications, the user should enter the “SAVE” word in the last field. 
     - The CTA “Confirm changes” is disabled as the new value and the “SAVE” are not correctly provided. 
- Then there is a comment, there is a comment icon that appears on the line. 
- Clicking on the icon opens the modal with the History and text of the comment 
     - History contains the date of modification, name of the editor and the modified value in the following format : 
_“04/10/2023
Org Name has changed Distribution Fee from € 20.000 to € 50.000”_

**Comment by Jackseed** [comment]
A few comments:
## Pre-settings
- What if there is no distributor on the film yet? (re the dropdown)
- I'm not sure the flow works the way we want when there is no contract since we redirect the user to rights creation, how could the user be redirected to the statement form afterwards? I think we need either to embed contract form & waterfall form to the pre-settings modale or think of something smarter.. discussion with devs would be useful to get what's possible
- 
## Statement form
### Period
- when you go to previous/next statement, if it's still in draft, couldn't it be editable?
- when user clicks on previous/next we should save the form or show the modale "you're leaving the form.. save/cancel"
- when user is on the last existing statement: should we show the next arrow and confirm a new statement creation if user clicks on it or just remove the arrow?
- precision for devs: if periodicity is filled on a statement we use it for the next one + then end date to predict new statement dates 
eg: statement n°2 is periodicity `Semesterly` from 01/01/23-30/06/23
Statement n°3 will be default to `Semesterly` from 01/07/23-31/12/23

### Navigation tabs
- Tabs are created by listing all the rights related to the distribution contract and then listing all the revenue sources related to these rights; we then display each 'media family' tab related to the sources (eg if a source is `EST` we show `Video` tab and if there is also a `SVOD` source then we display the 2 receipts tables inside the `Video` tab)

**Comment by phpgeekfr** [comment]
- [ ] @phpgeekfr check `TODO #9524` in code
